### ISSUE TITLE
Proposal: Add `method_added` hook and `method_removed` hook

### ISSUE THREAD

**Issue by MakeNowJust** [manastech/crystal#1065]
Ruby has  [`method_added`][] and [`method_removed`][]. `method_added` hooks defining a method, `method_removed` hooks removing a method.

This proposal makes many things possible. For example, one thing is auto HTTP server routing on defining a new method implicitly.

- `method_added` specs

  1. It is called by compiler when method was defined or added (detect `def` block).
  2. It is passed a `Def` object as a argument. This `Def` object is a defined method.

- `method_removed` specs

  1. It is called by compiler when method was removed (detect `undef` statement).
  2. It is passed a `Def` object as a argument. This `Def` object is a removed method.

[`method_added`]: http://ruby-doc.org/core-2.2.2/Module.html#method-i-method_added
[`method_removed`]: http://ruby-doc.org/core-2.2.2/Module.html#method-i-method_removed

**Comment by jhass** [comment]
We don't have `undef` as far as I'm aware, and given `previous_def`, method overriding as well as method overloading I see  no reason to add it.

**Comment by Exilor** [comment]
@jhass http://play.crystal-lang.org/#/r/95x

**Comment by MakeNowJust** [comment]
I hardly use `undef` in Ruby and Crystal. However, I want it for symmetry between `added` and `removed`, or because Ruby has it.

**Comment by jhass** [comment]
Ugh we have `undef`? oO What for?

**Comment by vendethiel** [comment]
@jhass Bottom type? Reminds me of [this](http://stackoverflow.com/questions/4787421/how-do-i-use-fix-and-how-does-it-work#comment5303037_4787421)

**Comment by MakeNowJust** [comment]
@vendethiel No.  Let see [this](http://stackoverflow.com/questions/543774/undef-why-would-you-want-to-undefine-a-method-in-ruby) rather than it.

**Comment by vendethiel** [comment]
I meant for the joke, but you're right ;-)

**Comment by MakeNowJust** [comment]
@vendethiel Oh sorry. I'm not good  at Englsh. I can use Crystal better than English!

**Comment by asterite** [comment]
I remember we introduced `undef` for linking against SDL: SDL defines it's own `main`, or something like that. But... now I can't find that `undef`, maybe we found some other way to do it. And I never used `undef` in Ruby, so we can probably remove it.

But `method_added` and `method_removed` macros might be good ideas. It would be nice to have use cases to know what could be done with that.

**Comment by bcardiff** [comment]
I would vote against having `undef`. I've never used and the only examples I can think of end in code smells everywhere.

The `method_added` sounds interesting as a way to hook before compilation. I think it might be better to have the hook act when the type information of arguments is known (i.e. when the def is turned in typed_def). Every transformation that can be done in an untyped AST it can be done in the typed one. It will be more slow due to repeated transformation probably, but I thinks is better in this case.

I see `method_added` as a specific case of transforming the code between the type_inference and the compilation. But, the things that might simplify things is that you would not need to take care of propagation of changes in types since `method_added` will hook right before the method is been used.

That been said, if the `method_added` works over non typed def I think they are still very useful. :-)

**Comment by ysbaddaden** [comment]
I believe Minitest::Spec in Ruby uses undef to clean up classes. I also used it sporadically sometimes. That being said, I won't regret the loss.

**Comment by MakeNowJust** [comment]
I implemented `method_added` and `method_removed` and I found some issues.

- `method_removed` should be passed `Undef` object? (this implementation is such that)
- `undef` can remove multiple methods, so `method_removed` should be passed `ArrayLiteral(Def)`?

**Comment by jhass** [comment]
Implemented by #1090 

Note `method_removed` wasn't implemented because `undef` was removed from the language.
