### ISSUE TITLE
*splat on arrays

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1096]
In Ruby, I can expand an array to an argument list:
```
a = [1,2,3]
puts *a     # equivalent to puts(1,2,3)
```
I cannot do this in Crystal, because splats only work with tuples. Unfortunately, tuples can't be dynamically created like arrays can:
```
a = [1,2,3]
a << 4
puts *a    # puts(1,2,3,4)
```
So essentially, the splat is pretty much useless. Any chance of array support?

Come to think of it....dynamic tuples would be awesome as well. Essentially arrays with different types for each element:
```
a = {"fred", 26}
a << 3.14
puts *a     # a string, an int, and a float
```

**Comment by asterite** [comment]
Using tuples for splat allows using tuples as arguments to methods, so you can for example forward them between methods. Using arrays won't work because their length is not know at runtime, and they mix all types.

There's no way the compiler can figure out how to expand that `puts *a` because it won't know the number of arguments.  For `puts` we could add an overload that accepts an array (or enumerable), and print each of them. Then you can just do `puts a` and the array overload will be selected. I think this is what Ruby does (obviously without overloads, just runtime checks), so if you do `puts [1, 2, 3]` it's like calling `puts(1, 2, 3)`... but that's not very intuitive, so we chose (for now) not to do that.

Maybe `puts` is a bad example. There's for example [File.join](https://github.com/manastech/crystal/blob/master/src/file.cr#L237-L275) which accepts a splat, and also array/tuple (maybe it should be enumerable). So you can do:

```crystal
File.join "foo", "bar", "baz"

paths = {"foo", "bar"}
File.join *paths

paths = ["foo", "bar"]
File.join paths
```

This means that you can always provide a splat version and an array version for your methods, if you think it makes sense to pass multiple arguments. 

For your particular case, you can do `a.each { |e| puts e }`. I know it's longer, but there's no way to do it with splats.

**Comment by stugol** [comment]
Ah. So, essentially, a Tuple is an array where the length and parameter types are known at compile-time?

But isn't the type of an array known at compile-time also? Not the length, obviously.

Incidentally, how would I go about creating an untyped array? Like, an array whose elements may be of any type?

Furthermore, is there some neat, convenient way (possibly with macros?) of having a hash table whose values can be of different types? For example, if I say ```hash[:name] = "Fred"``` and ```hash[:age] = 25```, the compiler will know that ```hash[:age]``` is an integer? So I can write things like ```hash[:age] += 1``` without the compiler bitching that I can't add numbers to strings?

**Comment by asterite** [comment]
Create un untyped array: you can't, this is a typed language. In the future you might be able to say `Array(Object)` but to invoke methods on the objects you'll have to cast them to the type you expect them to be.

And there's no way to create that hash table you want. But classes/struct with methods and types solve the problem, and they give you type safety. You can define `[]` to check at runtime "if it's 'name' then name, if it's "age" then age, otherwise raise an error", if that's what you really want to. For example [this](http://play.crystal-lang.org/#/r/9mz). But unless you really need that dynamism, your code will end up being slower, harder to understand, and will probably have more runtime errors that won't be, of course, catched at compile time.

**Comment by stugol** [comment]
Yeah, a normal struct would probably be a better option. Oh well.
