### ISSUE TITLE
Bug: Docs broken in Firefox

### ISSUE THREAD

**Issue by gottlike** [manastech/crystal#1107]
I tested in Chromium and FF. Chromium works fine, but in FF I get this when I click any menu item (on the left):

![screen shot 2015-08-05 at 09 59 01](https://cloud.githubusercontent.com/assets/278766/9080958/a366e0d6-3b58-11e5-9ce9-aba054284832.png)

**Comment by vyp** [comment]
Works for me on firefox 39.0.

**Comment by gottlike** [comment]
Hmm.. interesting. I just opened a private window and there it worked too. Don't know the exact cause, but obviously has to do with my system/browser. Closed.

**Comment by vyp** [comment]
This is obvious so I apologise, but have you tried restarting firefox?

Or perhaps it's an addon? You could try disabling all addons too and trying again. Or maybe disable each addon one by one.

**Comment by vyp** [comment]
Actually, I believe private mode still has addons enabled, so it's probably not an addon if it works in private mode. I guess if it still persists in normal firefox, you could try clearing the cache (with care).

**Comment by gottlike** [comment]
I think I found the issue: I did a search once for "channel" and nothing was found, that's why it says "channel" and no menu item is displayed. Everytime I click the menu the search is apparently rerun and as such the menu disappears. I was able to replicate this behaviour in Chromium too.

**Comment by vyp** [comment]
Okay I think I get what you are doing:

1. Go to http://crystal-lang.org/docs/

2. Click the search icon to pull down the search text box and type in "channel" here, and notice there are no results, and the menu becomes empty.

3. Click the search icon again to get rid of the search text box.

4. Click on any menu item and observe that the search box is pulled down again with "channel" still there.

  - So this means the menu is now empty again when it probably shouldn't be?

I did this on firefox 39.0.

Clearing "channel" from the search text box just before step 3 obviously fixes this.

And I guess the fix, if this is actually considered a bug, would be to somehow determine if toggling the search box will hide it (instead of making it appear), and then clearing the contents of the search text box.

**Comment by gottlike** [comment]
Yup, that sums it up pretty well. I agree with your fix proposal. When the search is closed, it shouldn't be active until one deliberately reactivates it again. Also the field content should be cleared right after closing the search in any case.

**Comment by asterite** [comment]
We are using [GitBook](https://github.com/GitbookIO/gitbook).

I was able to reproduce this in a [random gitbook](http://mlewistw.gitbooks.io/gitbook-introduction/content/chapter_1__why_gitbook/what_is_markdown.html).

Could you report the bug [there](https://github.com/GitbookIO/gitbook/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search), if it doesn't already exist? Thanks!

**Comment by vyp** [comment]
@asterite Ah right of course, I completely forgot! It seems to already exist: https://github.com/GitbookIO/gitbook/issues/783.

**Comment by gottlike** [comment]
Alright, I'm going to close it then. Thx everyone!
