### ISSUE TITLE
Iterator implementations: struct vs. class (Unify)

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#1130]
Browsing the [Iterator source code](https://github.com/manastech/crystal/blob/master/src/iterator.cr) I noticed that some of the real iterator implementations are implemented using `class` but most of them are using `struct`.

For instance right now `Take` is implemented through a `class` while `Select`/`Reject` are implemented in a `struct`.

I don't know much more about structs than [what I just read in the docs](http://crystal-lang.org/docs/syntax_and_semantics/structs.html). I'd think that all of the iterators could be implemented using either struct or class.

I think for consistency it might be good to **stick with either class or struct**. If there's a reason why some are class and some are struct I'd love to know it - but not required as people probably have more important things to do.

**Comment by Exilor** [comment]
The rule of the thumb is: if no instance variables are ever reassigned (AKA it's immutable) you can use a struct, otherwise use a class.

**Comment by asterite** [comment]
@Exilor has the answer.

The thing is, if a type has a bunch of instance variables that are assigned once in the constructor and are never re-assigned, then you can safely make that type a struct. This will reduce memory usage and, because the struct is effectively immutable, you won't run into strange behaviour with copies and mutation.

So, `Map` is a struct because it just holds the iterator and the proc to apply the mapping, but these are never reassigned. If we made `Take` a struct and somebody hold a reference to that take iterator while somebody else iterates it, the original reference wouldn't see that change... so it needs to be a class.

From the outside, the iterators are hidden (they have `# :nodoc:`) behind the methods that create them, so their users doesn't care, nor needs to care, if they are classes or structs. But the implementors (we) decided to use structs in a few places to optimize things. I don't think we'd like to make everything a struct or a class just for consistency's sake.

However, I can see that `Cons` is a struct and it reassigns an instance variable in the rewind method, so that's a mistake we need to fix :-)

**Comment by Exilor** [comment]
@asterite call me crazy, but it would be so cool if the compiler was able to tell if a class was mutable or not and it was the one in charge of deciding whether to use class or struct. It's not like mutable structs are advisable anyway.

**Comment by bcardiff** [comment]
I was thinking of building some sort of check after @asterite 's comment. But i would not suggest it for all structs. For iterators yes. Although not admisible, mutable value types are useful from time to time. 



—

**Comment by asterite** [comment]
@Exilor definitely not crazy, it's an idea we also had in mind. Maybe we can do it as an optimization in the codegen, but it will only mean that a class' memory would be allocated on the heap and it would be passed by value (if it's small in size). We can't change the type to inherit Struct because a struct doesn't have an object_id, and has a potentially different set of methods. So, we would also need to check that `object_id` wasn't invoked, for example.

**Comment by PragTob** [comment]
@asterite @Exilor :heart: :heart: :heart: - thanks for the patient explanation, learned a lot :)
