### ISSUE TITLE
Improve templates for `crystal init` proposal

### ISSUE THREAD

**Issue by krisleech** [manastech/crystal#1147]
I think the lib and app template could be improved:

* Should create MyLibrary, not Mylibrary
* <del>Add a Code of Conduct as per Crystal itself</del> (revoked, see comments)
* The app README library specific, I assume if shouldn't have `dep do`.

There is currently only one difference between app and lib templates and that is gitignore.

I'd be happy to submit a PR.

.

**Comment by krisleech** [comment]
This thread is relevant to the CoC suggestion: https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/gq-t15bpXCg

**Comment by ervumlens** [comment]
Regarding the Code of Conduct generation: 

The cultural and religious norms that go into forming one Code of Conduct are not inherently appropriate for those working under a different set of norms. In other words, there is no universally accepted Code of Conduct to generate. The only people who can determine the right Code a Conduct for a project are the project owners themselves. (I'm sure you can see how insisting that one Code is best for every project runs afoul of the typical Code of Conduct itself.)

Also, obligating the conscientious project owner to delete or replace the generated Code with each project is an unnecessary point of friction that I'm afraid will reflect poorly on the Crystal community.

For comparison, imagine a programming tool written by a religious group that needlessly generates a proselytizing message with each execution. They insist their own values are correct (who doesn't?), but is the tool the right place to delineate and promote those values? And is the promotion of the message greater than the benefit provided by the tool itself, such that losing users over it is a reasonable trade-off?

I admire the concern for others that's motivating the Code of Conduct movement. I hope that concern entails leaving the choice of a Code of Conduct to the project owners, and that you will make the Code of Conduct generation optional.

**Comment by krisleech** [comment]
Contrary to my first thought that since Crystal has a CoC, that precedent should be promoted, opt-out initially (this PR), then opt-in eventually (some future PR), I now think - either there should be no CoC or it should be opt-in. There should be no opt-out.

Reinforced by points in [PR thread for bundler](https://github.com/bundler/bundler/pull/3305.) and [CoC thread](https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/gq-t15bpXCg) on the Crystal Group.

**Comment by asterite** [comment]
@krisleech Thanks for opening this issue. The fix for "Should create MyLibrary, not Mylibrary" sounds good, I think `String#camelcase` should work if it's put in the correct place :-)

About the code of conduct, I also wouldn't like to force one to users. I also wouldn't bother much about trying to provide one by default. Let's try to keep `crystal init` simple, after all it's just a skeleton that will later be modified.

I don't understand the README specific part, but don't worry too much about the `deps` part because that will change.

**Comment by waterlink** [comment]
+1 for camel case and +1 for README part, should provide some instructions
on how to build and run an application, instead of instructions on
installing library (when template is for application).

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-12 23:31 GMT+02:00 Ary Borenszweig <notifications@github.com>:

**Comment by krisleech** [comment]
> I don't understand the README specific part,

I think the app README is wrong. Unless I am mistaken you wouldn't add the application itself to `Projectfile` as indicated in the generated README:

```
deps do
  github "..."
end
```

**Comment by krisleech** [comment]
I have started a PR here: https://github.com/manastech/crystal/pull/1234

**Comment by krisleech** [comment]
Second PR: https://github.com/manastech/crystal/pull/1324

**Comment by waterlink** [comment]
Looks like all bulletpoints from this issue were already merged in aforementioned PRs. @krisleech can this issue be closed?

**Comment by asterite** [comment]
I'll close tihs, the bulletpoints seems to be done and it's already been 2 weeks :-)

**Comment by rhysd** [comment]
:+1:
