### ISSUE TITLE
github pages travis script fails on PRs

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#1148]
I'm faily certain that the script used on the gh-pages branch (to build and push the docs) fails on PRs and therefore fails the build, which is a bit annoying. (see gh-pages PRs on travis [1](https://travis-ci.org/manastech/crystal/builds/74957022) [2](https://travis-ci.org/manastech/crystal/builds/74805115) [3](https://travis-ci.org/manastech/crystal/builds/74802933))

e.g. the specified script is this: `test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "gh-pages" && ./travis-build.sh`

`$TRAVIS_PULL_REQUEST` is probably true and that's why it fails. I think travis has deploy hooks, these seem to be more appropriate to do work like this than the script used for the test script.

I might be wrong, of course :) But that's what it seems like to me.

**Comment by bcardiff** [comment]
I mostly base what is done from http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

The idea was not to generate the docs on gh-pages PR since there are no place to actual commit them.
It seems it is failing for PR.

If should fail if something went wrong in `./travis-build.sh` for sure.

Maybe I'm wrong, but using travis after_success won't do any different in this scenario. They are commands to run in case specs passes. In gh-pages there are not specs.

We do need to just skip on PR. We should use `if` instead of `test` I bet :-)

**Comment by PragTob** [comment]
I think `after_success` is more appropriate. The `script` step is used to specify the script to execute tests - if that exits with everything but `0` the build is marked failing. Hence I think `after_success` is more appropriate or even the [deploy](http://docs.travis-ci.com/user/customizing-the-build/) entry - there doesn't seem to be a deploy support for github pages though. Which is too bad as `deploy` [skips all PRs by default](http://docs.travis-ci.com/user/deployment/)

But yeah maybe switching it up to if would also work (I'm not that proficient in shell scripting, sadly). Many ways lead to the goal!

**Comment by jhass** [comment]
Fixed this now actually.

**Comment by PragTob** [comment]
thanks @jhass !
