### ISSUE TITLE
Getting more than one Readline autocompletion result possible?

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1162]
Given

```crystal
require "readline"

def check_input string
  case string
    when "d"
      ["debug", "debounce"]
    else
      nil
  end
end
 
Readline.autocomplete { |input| check_input(input) }

loop do
  command = Readline.readline("> ", true)
  exit(0) if command == "q" || command == "quit"
end
```

when I press ```d``` TAB on the prompt, I never get the second result ("debounce"). Am I missing something?

**Comment by asterite** [comment]
You are right, it seems readline expects something else. I looked at what Ruby does and I don't quite understand it, it seems it returns a first string as a result indicating what to autocomplete, and the rest are the matches. I'll try to fix this, should be easy. The hard case is figuring out the common lowest prefix of all the completions.

**Comment by asterite** [comment]
Fixed by https://github.com/manastech/crystal/commit/4285f8fcbf46322582bcd4e8fd75521d0a36d6d7

@sardaukar Please try it now. I tried with this program:

```crystal
require "readline"

LIST = [
  "search", "download", "open", "operate", "opening",
  "help", "history", "quit",
  "url", "next", "clear",
  "prev", "past"
]

Readline.autocomplete { |s| LIST.grep(/^#{Regex.escape(s)}/) }

while line = Readline.readline("> ", true)
  p line
end
```

It's from the Ruby snippets found in the [Readline docs](http://ruby-doc.org/stdlib-2.1.0/libdoc/readline/rdoc/Readline.html), but I added some more options to the "o" letter to check it completes until a common prefix.

**Comment by sardaukar** [comment]
thanks for fixing this so quickly!
