### ISSUE TITLE
How to access individual bits?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1164]
Is there an idiomatic way to access individual bits inside fixnums? For example, to split a 32-bit number into a pair of 16-bit words, I need to reference bits 0-15 and 16-31. Currently I do the following, which I presume is hideously inefficient:
```
struct Fixnum
	def [](range)
		binary = self.to_s(2).rjust(range.max + 1, "0")
		binary[binary.length-range.max-1..binary.length-range.min-1].to_i(2)
	end
end
```
Sure, I guess I could do some bit-shifting with ```<<``` and ```>>```, but when I did that in Ruby, I ended up with insane answers. I guess Ruby "helpfully" increased the size of the int or something.

**Comment by bcardiff** [comment]
I would say that mask + shift is the way to go. Expressing the mask in `0b1101 # == 13`, `0o15 # == 13` or `0xD` might be comfortable. 

BitArray does not support setting multiple elements at once from an Int, but might be handy to do that and mix ranges to slice the array... just thinking out loud.

**Comment by Exilor** [comment]
I'm thinking something like [this](http://play.crystal-lang.org/#/r/b53) but don't trust my numbers too much. It's late here and I'm sleepy :)

**Comment by stugol** [comment]
@Exilor Hmm, that code won't work for 64-bit integers, nor will it allow for selection by range. Is there a way to programmatically determine the number of bits in a given variable? Presumably one could then assemble a mask that represented the desired range, and using bit-shifting and masking, extract the binary?

**Comment by bcardiff** [comment]
@stugol yes you can use `typeof` and `sizeof` http://play.crystal-lang.org/#/r/b55

**Comment by stugol** [comment]
How's this? http://play.crystal-lang.org/#/r/b5d

**Comment by bcardiff** [comment]
I knew this was discussed before. Check https://github.com/manastech/crystal/pull/981 there were some vote against indexing an Int. 

Maybe a wrapper around a value that allows bit access is nice way to go.

**Comment by stugol** [comment]
Odd. That thread talks about bit-access in Ruby using ranges. I can tell you for definite that this doesn't work - at least in Ruby 2.0.0.

**Comment by stugol** [comment]
Anyhow, I'll just monkey-patch the Int struct. Problem solved ;)

**Comment by asterite** [comment]
@stugol Masks and shifts are the way to go:

http://play.crystal-lang.org/#/r/b6m

I'd use that. Crystal is not Ruby, ints overflow and have the "usual" C semantics, so you can expect them to behave just like in C (which is very convenient once you want to see things as bits and bytes).

If you care about performance I wouldn't use the solution you proposed because it allocates memory, and this shouldn't be needed at all.

**Comment by stugol** [comment]
My solution may allocate memory, but your solution requires knowing the mask ahead of time and typing it manually into the code. Maybe it'd be justified in a critical part of the code where performance is everything; but sacrificing flexibility for speed isn't always the best way to go.

Perhaps a macro could abstract this inflexibility away, but macros are - as I understand it - global. You can't have a macro inside a class, masquerading as a method....can you?

**Comment by bcardiff** [comment]
Macros are not necessarily global http://play.crystal-lang.org/#/r/b6w

**Comment by stugol** [comment]
It doesn't seem to work here. Am I doing something wrong?

http://play.crystal-lang.org/#/r/b70 ```undefined method 'at' for UInt16```

**Comment by bcardiff** [comment]
Macros are not methods. In order to make something neat and performance the way would be to have a macro bits that will get two arguments: the obj and the range of bits (or bounds). The main thing is to build **in compile time** the mask to used. So the time is used in compilation but not in runtime.

somthing like this might work

```crystal
macro bits(obj, range)
  {% low = 0..range.begin %}
  mask = 0b{% for x in range %}1{% end %}{% for x in low %}0{% end %}
  (obj & mask) >> range.begin
end

pp bits(18_u16, 4..8)
```

but `RangeLiteral` does not have a the `#begin` method exposed in macros. We are happy to receive a PR for exposing `#begin`,`#end`, `#excludes_end?` in macros that so in HEAD or next release you can have that neat macro in your app.

Note: Range#min is from Enumerable, and is O(n). While Range#begin is O(1).

**Comment by stugol** [comment]
@bcardiff That's a nice macro you have there. I like the neat way you generate the mask. I wouldn't have the faintest idea how to modify the Crystal source to expose the ```begin``` method to macros, however. Seriously, I wouldn't even know where to start.

**Comment by bcardiff** [comment]
@stugol Glad you like it. Eventually it will compile. When RangeLiteral exposes it's methods to macros. 

Meanwhile, a similiar commit would be https://github.com/manastech/crystal/commit/5bfee485b20f456aa9f8f0e7a367b72e95b730ee . If you have time and interest you could try to use it as a guide to expose the tree main properties of a RangeLiteral.

Notice that although the macro seems to receive a range it actually abuse that it receives a RangeLiteral. If the range is stored in a variable it would not work.
