### ISSUE TITLE
Request: Not needing to instantiate exceptions

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1166]
In Ruby, you can ```raise MyException```, but in Crystal, you have to ```raise MyException.new```. This seems a little redundant to me. Can't we have it implicitly instantiate unless otherwise specified? I can't imagine a reason for this being deliberately omitted.

**Comment by asterite** [comment]
No, it's not redundant at all. I tried this in Ruby:

```ruby
class ParseException < Exception
  def initialize(message, file, line, column)
    super(message)
  end
end

begin
  raise ParseException
rescue Exception => ex
  p ex
end
```

I get: `#<ArgumentError: wrong number of arguments (1 for 4)>`

So I try with a message (as the [docs](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-raise) say):

```crystal
raise ParseException, "oops"
```

I get: `#<ArgumentError: wrong number of arguments (1 for 4)>`

Should I pass all the arguments there? Let's try:

```crystal
raise ParseException, "oops", "foo.cr", 1, 2
```

I get `#<ArgumentError: wrong number of arguments (5 for 0..3)>`

So I think the only way to do this is by actually instantiating the exception:

```crystal
raise ParseException.new("oops", "foo.cr", 1, 2)
```

Now it works.

So, apparently the `raise Exception` or `raise Exception, message` works only when the exception class defines a constructor with 0 or 1 arguments. So it "sometimes" works.

We don't like special cases. You need to document them and people have to learn all these ways to raise exceptions. Just look at that method documentation, instead of saying "raises the given exception" it has to detail all the possibilities. Plus, it's not that hard to write `.new`, just four chars.
