### ISSUE TITLE
alias_method block bug!

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1169]
The following code:
```
def fn1(&block)
end
alias_method :fn2, :fn1

fn2 { puts "Hi!" }
```
Causes the error ```'fn2' is not expected to be invoked with a block, but a block was given```. Surely this is wrong?

**Comment by bjmllr** [comment]
`alias_method` doesn't work if the method being aliased takes a block. This is a known limitation. From the doc for `alias_method` (http://crystal-lang.org/api/Object.html):

> due to current language limitations this is only useful when neither named arguments nor blocks are involved

In particular, your alias_method macro call expands to:

```ruby
def fn2(*args)
  fn1(*args)
end
```

but you need:

```ruby
def fn2(*args, &block)
  fn1(*args, &block)
end
```

and right now we can't write one macro to handle both cases. It's possible to write another macro to handle this specific case only, if you think you will use it a lot, but I think the intention is to make macros more capable so that `alias_method` can eventually be enhanced to handle both cases (and others).

There is some discussion of the topic here: https://github.com/manastech/crystal/issues/252

**Comment by asterite** [comment]
This is not a bug and it's even documented, as @bjmllr mentions.

I don't use `alias_method`, but `delegate` is used in the [compiler's code](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/types.cr#L1536-L1546). `delegate` suffers from the same issues as `alias_method`: doesn't work with blocks, doesn't work with named arguments. But here it's used internally so it's not that problematic.

I think I'd like to remove `alias_method`. We copied it from Ruby "just because", but in Crystal we tend to avoid aliases. So removing that method would go well with the language's philosophy.

**Comment by stugol** [comment]
@asterite Um....how is this "not a bug"? Documenting a problem doesn't make it go away. Of course it's a bug. A bug you're probably not going to fix, but a bug nonetheless.

```alias_method``` has its uses - for example, to rename a method without breaking existing code; or to change a particularly stupid or hard to remember method name in third party code. But the way it's implemented at the moment, I agree, it's pretty much useless.

**Comment by kirbyfan64** [comment]
But all the uses that you mentioned are easily solvable by just defining the method explicitly.

**Comment by strcmp** [comment]
"to rename a method without breaking existing code" is not a use case alias_method supports anyway as far as I'm aware. in Ruby alias_method makes a copy at the time it is called, but not so in Crystal (it delegates to the original method name), so even if this worked it probably doesn't do what expect here (the same as Ruby).

**Comment by stugol** [comment]
@kirbyfan64 While true, that's not a good argument. By your reasoning, we don't need macros at all. Or functions. Or classes. Or blocks. All the uses of the above are easily solvable by defining the code we want, explicitly, line by line. In other words, assembly language.

**Comment by asterite** [comment]
@stugol Honest question here: why are you using Crystal then if Ruby already has all of what you need?

**Comment by kirbyfan64** [comment]
But you're missing the point. Someone (I can't recall who, though) said one of the hardest things about language design is deciding what features to NOT have.

Python's motto is "explicit is better than implicit", but it's not quite assembly language.

**Comment by stugol** [comment]
@asterite Don't get me wrong, I like Crystal. I think you've done an awesome job here. It doesn't crash all over the place (well, rarely anyway) and the compilation errors are mostly helpful. It could really use a debugger of some sort, though. A way of stepping through the code. I tried putting ```debugger``` on a line (I saw on some post or other that this was possible) but all it did was crash the compiler...

As to why I use it....Ruby's too slow for intensive computation, basically. Oh, and you can't compile it into an exe. C++ is an arse, and Lisp is a bigger arse, and Go is limited, and PyPy/Cython are broken, and Rust is useless...

These are presumably - correct me if I'm wrong - the entire reason you developed Crystal in the first place, surely?

Incidentally, do you know how hard it is to google for Crystal issues or code? I keep getting damn Crystal Reports stuff and people selling magical healing crystals.

**Comment by asterite** [comment]
@stugol Thanks for your reply.

With my question I was hoping you'd reply to me with "Ruby is slow", and this is basically why we created Crystal (another reason is static type checks). Now, in the beginning we tried really hard to make a "compiled Ruby" but realized that it's impossible without having to do some changes to Ruby, or adding some restrictions. One obvious restriction is disallowing "send" and "eval". But there are other limitations.

While designing and evolving Crystal we always try to make things efficient. Sure, we could add runtime reflection or dynamic method invocation, or many interesting ways to deal with splats, but that would make things much slower (either at runtime or compile time). So, we don't introduce new features unless we find an efficient way to implement them. Other things aren't in the language yet because we didn't have time, or a pressuring need, to implement them. Many of your questions like "Why can't I do this in Crystal if I can do it in Ruby?" will have this answer: because we didn't find a way to implement it without making the generated programs slow (or making the compiler slow).

I think `alias_method` and `delegate` are a mistake and we should remove them, at least until we find a good way to implement them. Or we can make them be a special construct in the language, that could also work.

As a conclusion: we won't have all the magic that Ruby has, but we (hopefully) won't have you writing assembly code either. We'll try to make something that gives a good balance between programmer efficiency and program efficiency, but 100% Ruby happiness is not guaranteed.

**Comment by asterite** [comment]
@stugol Oh, I forgot, if you use `debugger` you must compile the program with `-d`. Maybe this is also something that we need to improve. After that you can use `lldb` (and I think maybe `gdb`), but you won't be able to do much there, we need to implement variable inspection, etc.

**Comment by stugol** [comment]
@asterite Of course, there will be limits to what a compiled language can support.

I think step-by-step debugging and variable inspection is kinda an important feature. Also, why not allow ```send```? Doesn't the compiled code use dynamic dispatch like Smalltalk - sending messages instead of calling functions directly?

**Comment by strcmp** [comment]
God, searching for a solution to a programming problem and finding magic crystals instead sounds like an okay deal to me.
