### ISSUE TITLE
Monkeypatching doesn't shadow?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1170]
When I monkey-patch a class or module to add a new method, existing methods with the same name are overloaded, rather than shadowed. Is this intentional?

I'm fairly sure Ruby clobbers the original. It's very irritating ;)

Just as well Crystal doesn't shadow though....previous_def doesn't work unless the method signature is identical, it seems. Very odd.

**Comment by bjmllr** [comment]
Yes, this is intentional. Crystal has method overloading, so if the number or types of the parameters of two methods differ, then they are different methods, even if they have the same name.

http://crystal-lang.org/docs/syntax_and_semantics/overloading.html

This is a difference from Ruby, so perhaps it should be added to https://github.com/manastech/crystal/wiki/Crystal-for-Rubyists ?

**Comment by asterite** [comment]
@stugol Well, it's really hard to know what's your problem without you showing some code. This works:

http://play.crystal-lang.org/#/r/b6n

But yes, as @bjmllr says, we have method overloading so we have these differences from Ruby: you can have many definitions of a single methods to redefinition becomes a bit blurry, but it generally means you need to specify the same number of arguments and types for that to work.

I'll close this because it works as expected, but feel free to enhance the wiki with this.
