### ISSUE TITLE
Eager evaluation to char type

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1206]
The code at http://play.crystal-lang.org/#/r/boc shows unbound types B and E being evaluated as Chars (or possibly Strings) simply because I'm calling ```to_s```.

**Comment by bjmllr** [comment]
Don't you need to give a full type on line 1? e.g., `{} of Range(Int32, Int32) => Range(Int32, Int32)`

**Comment by stugol** [comment]
Apparently it will compile fine even if you don't. Except for thinking it's a Range of Char for some damnfool reason.

**Comment by waj** [comment]
When you refer to a generic type without the type arguments, it means it can be any instantiation of the generic class. The Range class is used in the standard library for integers and chars, so both exists at compile time.

Your `mappings` variable can contain elements of any of these Range clases, including Range(Char, Char). That's why you get the error.

If you replace the first line by:
```
mappings = {} of Range(Int32, Int32) => Range(Int32, Int32)
```
it will compile just fine.

**Comment by stugol** [comment]
Ah. So by leaving the types unspecified, we mean "a range of any types that have been used in ranges"?
That doesn't explain why removing the exception line removes the error, though:
```
mappings = {} of Range => Range

struct Range(B,E)
  def fn(range : Range)
#    raise ArgumentError.new("%s%s" % [self.to_s, range.to_s]) if false
    range.includes?(self.begin)
  end
end

(0...100).fn(mappings.values.first) if mappings.length > 0    # compiles fine
```

**Comment by asterite** [comment]
I think using non-instantiated generic types as generic type arguments should always be an error.

**Comment by stugol** [comment]
This could cause a few problems though.
