### ISSUE TITLE
Time.epoch not using UTC time in 0.7.6

### ISSUE THREAD

**Issue by dbackeus** [manastech/crystal#1210]
I'm in Stockholm (UTC +1 hour usually but currently +2 for summer time) and get unexpected output using Time.epoch:

```crystal
puts Time.epoch(0) # 1970-01-01 00:00:00
puts Time.epoch(0).to_utc # 1969-12-31 23:00:00 UTC
```

When using `Time.at(0).to_utc` in crystal 0.7.5 I got the expected `1970-01-01 00:00:00 UTC`

As a side note I miss the `Time.at` API. It's both shorter and makes it more obvious that the method would return a Time object itself. Seeing `Time.epoch` makes me wonder if it converts something (perhaps a Time object) to a number representing epoch seconds, rather than the other way around.

`Time.from_epoch` or `Time.at_epoch` would make it clearer but even more annoying to type...

**Comment by strcmp** [comment]
:+1: for from_epoch/at_epoch/at, as said in another comment Time.epoch reads more like a getter than something that takes an argument and returns a Time.

**Comment by asterite** [comment]
@dbackeus Oops, this was a mistake.

I don't know why many thing `Time.at` is more obvious. At... what? "We'll have dinner at 10 pm". I can't imagine why "at" would mean "number of seconds after the unix epoch". At least "epoch" has a word that's in the previous phrase :-)

I agree it's not the shortest of the words. There's also the thing that we also want "number of milliseconds after the unix epoch", and that we want to get the number of seconds/milliseconds from a time instance. If we use `to_i`, say it means seconds, what should we call the milliseconds variant?

This is all the discussion we had with @waj before we decided to go with the `epoch` name. Probably seconds is the most common case, so then we have `epoch_ms` for milliseconds, etc.

We could also make `Time.epoch` be argless (or default seconds to zero) so it returns the time at the unix epoch, and so it'll look like a getter :-)

**Comment by ysbaddaden** [comment]
The problem is dealing with both seconds and milliseconds as integers.

Ruby made a choice: integers are seconds, and floats are milliseconds.

JavaScript made the other choice: timestamps are milliseconds, which has repercussions on some formats —like BSON if I follow correctly — and thus would require conversion, of course.

Since a timestamp is the number of seconds elapsed since epoch, having #to_i return seconds is logical, and #to_f return milliseconds sounds smart (it's a fraction of 

BTW: Time.at(int) Time.at(float) and Time.at("10 pm") can be dealt in different overloads, and would be awesome.

**Comment by dbackeus** [comment]
Agree that `Time.at` isn't obvious but neither is `Time.epoch` (since it reads like an epoch seconds reader). After having looked at the documentation and learnt it I would be happier using Time.at since it describes what I get back, not what I send in, which seems less surprising.

@ysbaddaden nice point about allowing a range of overloads for `Time.at`. Sounds like developer happiness to me :)
