### ISSUE TITLE
Sharing variables between macros

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#1213]
I have a case where i want to share some variables between macros.

You can check the example case below. I wanna share variables between actions, before_action and register_before_actions.

https://github.com/Codcore/amethyst/blob/master/src/amethyst/base/controller.cr#L54-L80

How can i achieve this?

**Comment by asterite** [comment]
There is a way, using a constant:

```crystal
SHARED = [] of Int32

macro add(x)
  {% SHARED << x %}
end

macro process
  {% for value in SHARED %}
    puts {{value}}
  {% end %}
end

add 1
add :foo
add 'a'
process
```

Note that I had to put the `Int32` there for it to compile, but we are modifying the array literal at compile time, putting any kind of nodes inside it. The result is that this is generated:

```crystal
SHARED = [1, :foo, 'a'] of Int32
```

which would give an error if you explicitly use SHARED, but because it's only used at compile-time it's valid.

I consider this more of a hack and a side-effect of how things work, but for now we'll leave this door open: maybe we can find good patterns for enhancing metaprogramming.

**Comment by jhass** [comment]
@sdogruyol does that solve your usecase? Can we close this for now?

**Comment by sdogruyol** [comment]
Yeah you can close this issue. Thanks
