### ISSUE TITLE
Cannot compile Crystal in MacOS 10.10.4 (Yosemite)

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1218]
```
> brew install libevent
> brew install libyaml
> brew install bdw-gc
> brew install libpcl 
> brew install gmp
> brew install libxml2
> brew install llvm
> brew link llvm --force
> git clone https://github.com/manastech/crystal.git
> cd crystal
> make
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr
Error in ./src/compiler/crystal.cr:3: instantiating 'Crystal::Command:Class#run()'

Crystal::Command.run
                 ^~~

instantiating 'run(Array(String))'

in ./src/compiler/crystal/command.cr:36: instantiating 'run_command(Array(String))'

        run_command options
        ^~~~~~~~~~~

in ./src/compiler/crystal/command.cr:142: instantiating 'Crystal::Command::CompilerConfig#compile()'

      config.compile
             ^~~~~~~

instantiating 'compile(String)'

in ./src/compiler/crystal/command.cr:246: instantiating 'Crystal::Compiler#compile(Array(Crystal::Compiler::Source), String)'

      compiler.compile sources, output_filename
               ^~~~~~~

in ./src/compiler/crystal/compiler.cr:68: instantiating 'infer_type(Crystal::Program, Crystal::Expressions)'

      node = infer_type program, node
             ^~~~~~~~~~

in ./src/compiler/crystal/compiler.cr:117: instantiating 'timing(String)'

      timing("Type inference") do
      ^~~~~~

in ./src/compiler/crystal/compiler.cr:117: instantiating 'timing(String)'

      timing("Type inference") do
      ^~~~~~

in ./src/compiler/crystal/compiler.cr:118: instantiating 'Crystal::Program#infer_type(Crystal::Expressions)'

        program.infer_type node
                ^~~~~~~~~~

in ./src/compiler/crystal/semantic/type_inference.cr:9: instantiating 'infer_type_intermediate(Crystal::Expressions)'

      result = infer_type_intermediate(node)
               ^~~~~~~~~~~~~~~~~~~~~~~

in ./src/compiler/crystal/semantic/type_inference.cr:15: instantiating 'Crystal::TypeVisitor:Class#new(Crystal::Program)'

      node.accept TypeVisitor.new(self)
                              ^~~

instantiating 'new(Crystal::Program, SimpleHash(String, Crystal::MetaVar), Nil, Nil)'

in ./src/compiler/crystal/semantic/type_lookup.cr:113: instantiating 'Crystal::ASTNode+#accept(Crystal::TypeVisitor)'

      node.expressions.each &.accept visitor
                              ^~~~~~

in ./src/compiler/crystal/syntax/visitor.cr:23: instantiating 'Crystal::TypeVisitor#visit(Crystal::ASTNode+)'

        if visitor.visit self
                   ^~~~~

in ./src/compiler/crystal/semantic/type_inference.cr:1346: instantiating 'Crystal::Path#accept(Crystal::TypeVisitor)'

      node.name.accept self
                ^~~~~~

in ./src/compiler/crystal/syntax/visitor.cr:23: instantiating 'Crystal::TypeVisitor#visit(Crystal::Path)'

        if visitor.visit self
                   ^~~~~

in ./src/compiler/crystal/semantic/type_inference.cr:2139: instantiating 'Crystal::Const#visitor=(Crystal::TypeVisitor)'

          type.visitor = self
               ^~~~~~~

in ./src/compiler/crystal/semantic/ast.cr:380: instantiating 'Crystal::TypeVisitor#interpret_enum_value(Crystal::ASTNode+, Crystal::IntegerType)'

                numeric_value = visitor.interpret_enum_value(value, node_type.program.int32)
                                        ^~~~~~~~~~~~~~~~~~~~

in ./src/compiler/crystal/semantic/type_inference.cr:2089: instantiating '(Int8 | Int32 | Int16 | Int64 | UInt8 | UInt32 | UInt16 | UInt64)#<<((Int8 | Int32 | Int16 | Int64 | UInt8 | UInt32 | UInt16 | UInt64))'

      when "<<" then left << right
                          ^~

in ./src/int.cr:131: instantiating 'Int8#>>((Int8 | Int32 | Int16 | Int64 | UInt8 | UInt32 | UInt16 | UInt64))'

      self >> count.abs
           ^~

in ./src/int.cr:112: undefined method 'unsafe_shr' for Int8

      self.unsafe_shr(count)
           ^~~~~~~~~~


make: *** [.build/crystal] Error 1
```
Sigh.

**Comment by stugol** [comment]
You also can't compile Crystal in Debian once you replace the repo version of Crystal with a freshly-compiled version.

**Comment by jhass** [comment]
That looks like you're trying to compile HEAD with <= 0.7.5, it requires 0.7.6.

**Comment by stugol** [comment]
What?

**Comment by bcardiff** [comment]
building crystal from the source requires usually an up to date compiler. Right now it 0.7.6. When you installed crystal the first time probably it was 0.7.4. That compiler was fine to build crystal latest change until 0.7.5 was released. Why? Because now that crystal 0.7.5 exist there are new features that can be used in the compiler itself. Sometimes the changes are only in the standard library so you can have some out of date things without problem, but when new release make subtle, but changes in operators, syntax, core features, well.. things will blow probably in a cryptic way. 

Is either that way or you should avoid using crystal source. Hence, using only the released versions.

**Comment by stugol** [comment]
So....what? I need to somehow download the previous source, build that, then download the new source and build *that*? I don't know how to download a previous version.

You know, this could all be solved if executable versions were built whenever a commit was made.

**Comment by jhass** [comment]
You just need to make sure to install the prebuilt binaries for last release (0.7.6) to build HEAD.

**Comment by kirbyfan64** [comment]
@stugol Just calm down a moment and breathe *in*...and *out*. :)

Basically, to compile the sources, you always need the latest binaries available. Simple.

**Comment by stugol** [comment]
I'm just hitting wall after wall. I tried to install the latest binaries on my Mac (http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html):
```
brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:226:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:125:in `<main>'
```

**Comment by kirbyfan64** [comment]
@stugol Try running `brew update` again. [It usually works the second time.](https://github.com/Homebrew/homebrew/issues/42553#issuecomment-128412507)

**Comment by stugol** [comment]
Alright, I got it compiled. Hooray!

Of course, there's still the slight issue that you can't compile the source with an executable you already compiled from the source... which is weird...

**Comment by jhass** [comment]
You can, you just can't move it. If you don't move it running `make` again after the source changed will work, but you need to run it through the `bin/crystal` script in the repo to set the right paths.

**Comment by stugol** [comment]
Yeah, but what use is that? The whole point of compiling the damn thing is so when I type ```crystal``` at the prompt (or in a shebang line), it runs the new one. So I need to replace the symlink in /usr/bin or wherever to point to the new executable. Whereupon any subsequent ```make```s will fail. It's a catch-22.

**Comment by jhass** [comment]
I keep an alias to it around since I want to use the release usually and only occasionally check something with HEAD. `alias dcrystal=$HOME/crystal/bin/crystal"`

**Comment by asterite** [comment]
@stugol That's because we only advance one version at a time, and if you do `make clean crystal spec` it will test the new compiler, and if that works, we are good. And if you do want to use the latest version you can use an alias, as @jhass pointed. Or you can be patient and wait for the next version to come out.

If you want to compile a compiler with a new compiler you can still do it like this:

```crystal
bin/crystal build src/compiler/crystal.cr -o crystal-1
mkdir .build
cp crystal-1 .build/crystal
bin/crystal build src/compiler/crystal.cr -o crystal-2
# now crystal-2 was compiled with crystal-1
```

Could I ask you to change your tone? There's no need to say "damn" and other curse words. There's also no need to say "how on earth am I supposed to do X without Y", because I'm sure you realize not all languages have all features and yet people make very good tools with all of them. We all here try to be polite, positive and helpful. Please try to respect that, and please read our [code of conduct](https://github.com/manastech/crystal/blob/master/CODE_OF_CONDUCT.md). If you don't, nothing bad will happen, but I (and maybe others) will probably lose interest in giving you helpful answers.

**Comment by stugol** [comment]
@asterite I'm sorry, I didn't mean anything by it. I was just getting a little frustrated, that's all.

**Comment by kirbyfan64** [comment]
@stugol No worries. It happens to all of us. (Well, I don't know about everyone else, but I almost *always* have weird errors when I build projects; in fact, [the undefined reference errors that I helped you with](https://github.com/manastech/crystal/issues/1202#issuecomment-132009427) happened to me too, which is why I knew how to fix them. :).

**Comment by stugol** [comment]
@asterite I can't seem to build it from your instructions:
```
> git clone https://github.com/manastech/crystal.git
> cd crystal
> /opt/crystal_0.7.6_1e23667/bin/crystal build src/compiler/crystal.cr -o crystal-2
```
where ```/opt/crystal_0.7.6_1e23667``` is the location of the version of Crystal I built last time, and symlinked into my path.

**Comment by kirbyfan64** [comment]
@stugol Read my comment I referenced, which says how to fix those linker issues (like I said, I got the *exact* same ones).

**Comment by stugol** [comment]
The comment where you say I need to download build and install a bunch of other stuff that I *don't* need if I compile Crystal using a version of Crystal I haven't already compiled?

Let me say it again: If I install the repo version of Crystal, I can build Crystal - or at least the almost current version of it. And with that, I can build the latest version. But if I *then* try to use *that* to build *another* version of Crystal, IT FAILS.

Something is broken here. And it ain't gonna be fixed by downloading, building and installing a bunch of random stuff that I've never even heard of. Especially as this happens on MacOS *and* Debian.

**Comment by stugol** [comment]
Right. If I type the following command, it works:
```
> cd crystal
> PATH=/opt/crystal/bin/:$PATH; make
```
where '/opt/crystal/bin' is the location of your original version of Crystal, that you kept, because if you don't *you can't build the next version!*

Shouldn't this be fixed at some point?

**Comment by asterite** [comment]
I don't understand. I already showed a way to build a compiler, and using that compiler to create another compiler.

When we release we just [compile the compiler using a previous version](https://github.com/manastech/omnibus-crystal/blob/master/config/software/crystal.rb#L33). We never need to compile a second version because `make clean crystal spec` already takes care to verify that the new compiler can compile itself.

Then, maybe 99% of users will be using crystal as tool. 1% will also be using crystal to send pull requests to the standard library, and for that they'll use the `bin/crystal`, they don't need to compile a compiler. And just a small percent of that group will need to compile a compiler to make changes to the compiler. And in no case they will need to create a second compiler.

And yes, that small group needs to have some libraries installed in their system, it isn't really hard and it's listed in the wiki.

So I really don't understand your complaint.

**Comment by stugol** [comment]
My problem is that when I tried to follow your instructions, it didn't work.
