### ISSUE TITLE
Single-line if behavior changed in 0.7.6

### ISSUE THREAD

**Issue by pointybird** [manastech/crystal#1228]
In previous versions, single-line if statements such as

```Crystal
if 3 < 4 puts "smaller" end
```

worked but now fail to compile in 0.7.6. It still works with a semicolon added but is a bit awkward looking.

```Crystal
if 3 < 4; puts "smaller" end
```

**Comment by waterlink** [comment]
I think `0.7.6` behavior is correct. This semicolon is required to disambiguate where condition ends and where body starts.

**Comment by stugol** [comment]
Why not use idiomatic single-line if-statements?
```
puts "smaller" if 3 < 4
```

**Comment by pointybird** [comment]
The above is a simplified statement showing the change, and in that case I probably would just use the trailing if form. I don't think that helps if there is an else clause, though, as in
```Crystal
if 3 < 4; puts "smaller" else puts "larger" end
```
I do agree that the new behavior is probably the correct one, and Ruby also requires a semicolon or ```then``` for such constructions. I was merely noting the issue as an undocumented (as far as I can tell) change that can break code that compiled and ran without error in previous versions.

**Comment by jhass** [comment]
If there's an else case I tend to use ternary (since usually you're not doing that in a single line for side effects)
```cr
puts 3 < 4 ? "smaller" : "larger"
```

**Comment by waterlink** [comment]
You are correct this sounds like an undocumented breaking change for a
moment. To me it sounds like a bugfix though, because previous behavior was
incorrect.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-19 10:56 GMT+03:00 Jonne Haß <notifications@github.com>:

**Comment by asterite** [comment]
Before this fix this worked fine: http://play.crystal-lang.org/#/r/bzq

The fix was about fixing that case, and as a side effect the program:

```ruby
if 3 < 4 puts "smaller" end
```

stopped compiling. But in Ruby the above doesn't compile either. It's a syntax error.

So yes, it's a bug fix. And I don't consider it a breaking change because code that relied on this was broken (maybe it's a "fixing change"? :-)).

**Comment by alexeypetrushin** [comment]
Currently one-line if not working with `then` this compiles in ruby but not in crystal `v = if 1 > 2 then 1 else 2 end` crystal complains about `then`, this works in crystal `v = if 1 > 2 1 else 2 end` wonder if that's intentional, the version with `then` looks clearer.

**Comment by jhass** [comment]
Not supporting `then` (anywhere really) was intentional as far as I remember. The less keywords to learn the better. The less variants to do something the less fighting about styles.

**Comment by alexeypetrushin** [comment]
Hmm, I'm personally like `then` and that the code reads closer tho english. Another benefit is that there would be less confusion for people moving from ruby.

**Comment by z64** [comment]
> Not supporting `then` (anywhere really)

Crystal does support `then` for `case` statements:
```cr
num = rand(2)
case num
when 0 then puts("zero")
when 1 then puts("one")
end
```

**Comment by j8r** [comment]
Is there any case justifying adding `then` that can't be solved with ternary or single line if statement?

**Comment by asterite** [comment]
The reason is that `when ... then` is very common in Ruby, but `if ... then` is not. 

For Crystal we mainly followed [this Ruby style-guide](https://github.com/rubocop-hq/ruby-style-guide). In there, note that `if ... then` is not recommended and the ternary operator is recommended instead. But `when ... then` is perfectly fine.

So we don't want to add syntax that's not recommended by the most popular Ruby guide.

I understand some want to write `if ... then` but it's not going to happen, there's no value in doing that other than Ruby compatibility for a minority (because most don't write code like that), so you can continue discussing things here but it's not going to happen.

**Comment by straight-shoota** [comment]
To clarify: We already have `then` as a keyword in combination with `when`, so it would just be adding another usage of it.

What I find confusing:
```cr
if true 1 else 2 end      # => 1
if true then 1 else 2 end # unexpected token: then
```
The second expression is much better readable.

I'm not even sure why we support the first syntax. It's hard to understand, even with simple literal values. Shouldn't an expression separator (i.e. line break or semi colon - or perhaps `then`) be required between condition and body?

**Comment by asterite** [comment]
That the first syntax is supported is a bug. A newline or a semicolon should follow.
