### ISSUE TITLE
Why Range(B,E)?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1232]
Can someone explain to me the rationale for giving Range two type parameters? It makes it very difficult to, for example, subtract ranges. Besides, to my mind, a range from Int32 to Char makes no sense whatsoever. When would anyone need a range with two types?

**Comment by asterite** [comment]
For example: http://play.crystal-lang.org/#/r/c0s

**Comment by stugol** [comment]
I'm sorry, but a range of floats makes no sense at all. I think the code you gave should require a cast to int.

**Comment by asterite** [comment]
At one point we changed `Range(B, E)` to be `Range(T)` and it was very annoying, exactly because the code started to require casts or transformations everywhere. This becomes more annoying if you mix different integer types.

A range of floats makes no sense, but a range of integers whose end is a float is perfectly fine, and in fact the code I shown works OK in Ruby.

**Comment by stugol** [comment]
Ah, fair enough then. It makes some code really difficult though. Possibly the type system itself needs a little improvement. See my other post about unioning.

**Comment by jhass** [comment]
Looks like the question is resolved.
