### ISSUE TITLE
wrong computation with --release

### ISSUE THREAD

**Issue by will** [manastech/crystal#1274]
```
/tmp ➤ crystal build timebm.cr
/tmp ➤ ./timebm
2015-05-01 20:10:01 UTC
2015-05-01 20:10:01 UTC
2015-05-01 20:10:01 UTC
/tmp ➤ crystal build timebm.cr --release
/tmp ➤ ./timebm
2015-05-01 20:10:01 UTC
2000-01-01 00:00:00 UTC
2000-01-01 00:00:00 UTC
/tmp ➤
```
Code is here: https://gist.github.com/will/1b0ee6865472b8b30b46

I figure the byte swapping stuff is being mangled with --release but not sure why

**Comment by asterite** [comment]
I started looking at this but then noticed that you do:

```
def ...
  n = ...
  pointerof(n)
end
```

You are returning a pointer to a local variable, and once LLVM optimizes that out I don't know what happens with that pointer (it's basically undefined behaviour and the same thing that happens if you return a pointer to a local variable in C). Maybe the compiler could detect this, but it won't detect the general case.

Changing it to this it work: https://gist.github.com/asterite/8a7ac3f9e43075aee54f

**Comment by will** [comment]
Ah, yeah that makes sense thanks.

Also ![](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/27879/toot-1365641558.gif) pre-calculating the ticks is 3x faster than doing it each time, and overall 10x faster than the text result format.

https://gist.github.com/will/1b0ee6865472b8b30b46
