### ISSUE TITLE
Race condition in testsuite on 32bit

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1311]
I'm sure you noticed the stalled builds in the new 32bit builds on Travis. Since I can reproduce them in a local 32bit chroot, I figured I'll try a run in verbose mode to spot where it gets stuck, in about 2 of 3 builds it looks like this:

```
...
BufferedChannel(T)
  pings
  blocks when full
  doesn't block when not full
  gets ready with data
  works with select
  can send an receive nil
  can be closed
  can be closed after sending
  can be closed from different fiber <--- never turns green
```

at that point it goes into consuming 100% CPU and I have to kill it. I'll poke a bit more to see if it's related to #1275

**Comment by jhass** [comment]
Okay, it doesn't appear to be linked to #1275, I see no failed allocations :/

**Comment by asterite** [comment]
> 22:29 <waj> jhass: I'm debugging #1311 and I found that it get stuck inside the `caller` loop 
> 22:30 <waj> more precisely, `Unwind.step` seems to always return a positive number in that case 
> 22:30 <waj> I wonder if it's just some bad definition of the lib

**Comment by waj** [comment]
I'm now pretty sure this is related with this bug in glibc: https://sourceware.org/bugzilla/show_bug.cgi?id=18635, and it was fixed very recently: https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=bbab82c25da9b504c0804119840de7aeab0eeeba

Basically it fails when an exception is raised (and caught) inside a fiber. Instead of using libunwind low level functions, I changed the `caller` implementation to use `_Unwind_Backtrace` and I was able to make it crash every time instead of randomly.

I'm still looking for a workaround. I wouldn't merge #1316 because I don't want to simply ignore the issue.
