### ISSUE TITLE
'%' sign erroneously evaluated inside string literals in macros

### ISSUE THREAD

**Issue by trapped** [manastech/crystal#1336]
It seems that the `%` sign (for prepending macro local variables afaik) is evaluated even when inside a string literal:

```crystal
macro info(message)
  puts "#{TimeFormat.new("%d/%b/%Y:%H:%M:%S %z").format Time.now} - INFO - #{{{message}}}"
end

info "something"
#output: __temp_98/__temp_99/__temp_100:__temp_101:__temp_102:__temp_103 __temp_104 - INFO - something
```

Escaping them using `\` has no effect whatsoever, but the issue can be (temporarily) circumvented by using a constant:

```crystal
LOG_TIME_FORMAT = "%d/%b/%Y:%H:%M:%S %z"
macro info(message)
  puts "#{TimeFormat.new(LOG_TIME_FORMAT).format Time.now} - INFO - #{{{message}}}"
end

info "something"
#output: 31/Aug/2015:16:19:44 +0200 - INFO - something
```

**Comment by asterite** [comment]
The problem is that you want macro variables (`%var`) inside strings, when inside string interpolations. But currently the compiler doesn't track if it's inside an interpolation and I think it's pretty hard to it (because macros aren't parsed like normal language expressions). As an alternative, we can add the `\%` escape. In any case this escape will be useful, so I'll add it.

**Comment by asterite** [comment]
Maybe later (much later) I'll try to tackle the "detect if we are inside an interpolation", but with this new escape you should be able to do what you want (which previously wasn't possible without using a separate constant).
