### ISSUE TITLE
can't generate docs on master

### ISSUE THREAD

**Issue by jwaldrip** [manastech/crystal#1368]
I get the following error when trying to generate docs locally:

```
$ .build/crystal docs
ld: library not found for -lgc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o /Users/jwaldrip/dev/src/github.com/manastech/crystal/.crystal/crystal-run-macro-run-_Users_jwaldrip_dev_src_github.com_manastech_crystal_src_ecr_process.cr.tmp "/Users/jwaldrip/dev/src/github.com/manastech/crystal/.crystal/Users/jwaldrip/dev/src/github.com/manastech/crystal/src/ecr/process.cr/main.o"   -levent -lpcl -lpcre -lgc -lpthread`
```

Something different happens on 0.7.6 stable:

```
$ crystal docs
Error in ./src/char.cr:49: already initialized constant Char::ZERO

  ZERO = '\0'
  ^~~~
```

**Comment by jhass** [comment]
Please `brew install bdw-gc` and possibly more from https://github.com/manastech/crystal/wiki/All-required-libraries#mac-osx-with-homebrew

**Comment by jhass** [comment]
No further feedback for more than a month, closing.

**Comment by ozra** [comment]
I got both above errors just the other day when trying to compile docs in my local repo.
Here's intell based on catching up to latest of upstream repo 20151128:

If I use `bin/crystal docs`, I get:
```
error: undefined reference to 'GC_get_push_other_roots'
./.crystal/home/oscar/3-project-support/crystal/crystal-dev-fork/src/ecr/process.cr/_main.o:main_module:function __crystal_main: error: undefined reference to 'GC_set_push_other_roots'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/oscar/3-project-support/crystal/crystal-dev-fork/.crystal/crystal-run-macro-run-_home_oscar__-project-support_crystal_crystal-dev-fork_src_ecr_process.cr.tmp" "${@}"  -rdynamic  -levent -lrt -lpcl -lpcre -lgc -lpthread -ldl`
```

I get linking errors when compiling too. Before, in some versions (?) I could get away with something along the lines of `CRYSTAL_PATH=./src .build/crystal build --link-flags=-L/opt/crystal/embedded/lib/ src/compiler/crystal.cr`

When using the "global" crystal binary (just removing `bin/` or `.build/` from above example) it works (for compilation, not docs), as long as I still supply the `--link-flags` or it will fail linking.

There seems to be some trouble with the lib-paths lookup. And, when explicitly stating libs path, I guess perhaps it's not passed along to all instances of Compiler, for macro work etc?

For the 'already initialized' (which happens for `docs`) I just have no clue why it comes up. Perhaps paths here too? If it somehow loads stdlib from repo _and_ embedded? (causing duplication of all stdlib files, but since methods are OK to monkey patch, but not constants [why? other question.], it fails on that). Just a shot-in-the-dark theory made up while writing this...

I'm on Ubuntu 15.10, 64 bit.

**Comment by gerrywastaken** [comment]
@jhass It's too bad he didn't get back to you, because I'm running into the same issue on the latest Crystal master:

```shell
~/source/crystal(master ✗) brew install \
>   bdw-gc \
>   gmp \
>   libevent \
>   libpcl \
>   libxml2 \
>   libyaml \
>   llvm

Warning: bdw-gc-7.4.2 already installed
Warning: gmp-6.1.0 already installed
Warning: libevent-2.0.22 already installed
Warning: libpcl-1.12 already installed
Warning: libxml2-2.9.3 already installed
Warning: libyaml-0.1.6_1 already installed
Warning: llvm-3.6.2 already installed

~/source/crystal(master ✗) crystal doc
Error in ./src/char.cr:53: already initialized constant Char::ZERO

  ZERO = '\0'
  ^~~~
```

**Comment by asterite** [comment]
@gerrywastaken try `make doc`

**Comment by gerrywastaken** [comment]
@asterite Yup I did that. I was just figuring that `crystal docs` failing on the crystal code base was unintended, so I did a search for it and ended up here.
