### ISSUE TITLE
Should print flush?

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1436]
A common idiom is

```cr
print "Enter your name: "
name = gets
puts "Hello #{name}"
```

But since `STDOUT` is a `BufferedIO` it only flushes on newlines and you have to do it manually currently:

```cr
print "Enter your name: "
STDOUT.flush
name = gets
puts "Hello #{name}"
```

Should we have `print` flush? Or introduce something like `prompt` which does flush (and probably add a trailing space)?

**Comment by technorama** [comment]
Or let interactive programs turn off output buffering.

**Comment by jhass** [comment]
@technorama suggested on IRC to `STDOUT.sync = true if STDOUT.tty?`, I think that could give a good compromise.

**Comment by ysbaddaden** [comment]
I have this buffering problem with Logger, and resolved to pass a sync IO to Logger.new, otherwise I always end up with truncated log files (program exit doesnt seem to flush buffered IOs) for example.

**Comment by asterite** [comment]
STDOUT and STDERR should probably be sync'ed. We didn't want to do this because in [some benchmarks](https://github.com/nsf/pnoise) having sync by default makes the program run a bit slower (from 0.086s to 0.115s). But in these benchmarks we can always do `STDOUT.sync = false` if we want to get that performance back. We should favor correct behaviour.

As a side note, I never really understood why it's called `sync`, could we maybe rename it to `buffer` or `buffered`? (but that's something to discuss in another issue)

**Comment by will** [comment]
Alternately, maybe `gets` could flush before doing anything else?

**Comment by technorama** [comment]
+1 property `write_buffered`.  `sync`, `buffered` don't indicate that only writes are affected.  Reads still use buffering depending on the method called.

**Comment by jhass** [comment]
How about `direct_write` for something easier to type and keeping the same `true`/`false` values of `sync`?

**Comment by technorama** [comment]
Buffer/buffering/buffered is mentioned everywhere else in the IO code and is well understood.  It also keep the door open for consistency with write_buffer_size or other write_buffer_x variables.

**Comment by technorama** [comment]
@ysbaddaden see #1442 to fix logging.  There is no telling what type of IO object the logger may send to.  It could `Compressed(File)`, Scribe, or other service.
