### ISSUE TITLE
Implement send(:method) in standart lib

### ISSUE THREAD

**Issue by classyPimp** [manastech/crystal#1467]
As previously it was discussed back in 2013 (https://github.com/manastech/crystal/issues/49), send method can't be implemented.
But now with all that macros and eval capabilities is it possible to implement?
Maybe send method shall be included in stdlib?

**Comment by jhass** [comment]
The main issue I still see is that send would return a union of all return types of the methods the class has and inherits (so all of Object for example too). Huge unions are slow and a pain to work with, would you really want that?

It can make an interesting third party library, more as an experiment than a recommended technique. But we absolutely shouldn't recommend that programming style with stdlib. If you need dynamic dispatch you should build a macro that does it among the possible candidates only.

**Comment by jwaldrip** [comment]
I am not too sure about send. First of IF it gets implemented, I feel as though it should follow the same rules as regular methods. This means that calling send to a private method should never work outside the method itself. The same rules should apply to protected.

**Comment by waj** [comment]
I don't see how can we implement this, with macros or anything (there is no eval in crystal). Using macros, the method to be called still need to be specified as a literal and constant value. So how is this different than invoking the method directly?

Using macros we were able to redefine metaprogramming scenarios where other languages just relies on reflection, generating much more performant code (i.e.: JSON mappings).

However I'm sure other cases could not just be solved by macros and we should design patterns of language use to cover those scenarios if `send` is not available. If someone can describe one or more of these cases it might be helpful for the language design, instead of just trying to copy features from Ruby.

**Comment by technorama** [comment]
This is a real ruby example (from memory) where send could be useful.
 
```
SMTP::Server.io_loop
  cmd, arg = line.split(' ', 2)
  begin
    send("cmd_#{cmd.downcase}", args)
  rescue MethodMissing
    reply "502 command not recognized"
  end
end

# Partial SMTP server class.  Define commands by defining methods named cmd_#{name}.
class MySMTPServer < SMTP::Server
  def cmd_helo arg
    @hostname = arg
    reply ...
  end

  def cmd_ehlo arg
    @hostname = arg
    reply ...
  end

  def cmd_noop arg
    reply ....
  end
end
```

**Comment by waj** [comment]
But you can rewrite that using a case statement and at the same time you avoid that awful use of exceptions :-)

**Comment by technorama** [comment]
Can't rewrite it using a case statement.  Exception are only raised for unknown commands which shouldn't happen often.  Alternatively you can use method_missing.

# Each module includes 1 or more methods.
# The event loop is in SMTP::Server, not a subclass.
```
class MySMTP < SMTP::Server
  include SMTP::Modules::Ehlo
  include SMTP::Modules::EtrnDeny
  include SMTP::Modules::StartTlsOptional
end

class MySubmitSMTP < SMTP::Server
  include SMTP::Modules::Ehlo
  include SMTP::Modules::StartTlsMandatory
  include SMTP::Modules::AuthRequired  
```

**Comment by jhass** [comment]
Yes you can, [this](https://github.com/trapped/maild/blob/master/src/maild/handler.cr) is pretty much your example having done so.

**Comment by ysbaddaden** [comment]
A big case does solve the problem, if generated in a def macro that will generate a method on each child class:

```crystal
class SMTP::Server
  macro def io_loop : Nil
    cmd, arg = line.split(' ', 2)

    case cmd
    {% for method of @type.methods %}
      {% if m = method.name.match(/^cmd_(.+)/) %}
        when {{ m[1] }} then {{ m[0].id }}(line)
      {% end %}
    {% end %}
    else
      reply "502 command not recognized"
    end

    nil
  end
end
```

See https://github.com/ysbaddaden/minitest.cr/blob/master/src/minitest/test.cr#L28 for a real example.

**Comment by technorama** [comment]
If a case statement for all methods is possible in 10 lines of macro then supporting send may not be necessary.  Or send should be implemented using a macro.

**Comment by waj** [comment]
> Can't rewrite it using a case statement

Well.. yes you can. Specially if we keep considering the original example. The second example is interesting anyway, because it make us think how to solve it without using `send`. Without any metaprogramming (which I would consider in the first place) you can still have a dispatch method on each class. Otherwise, if having to maintain such dispatch methods REALLY hurts, then I'd consider the macros that generate the case statements for us.

Regarding using exceptions and note aside, I think it's bad not only because it's slower but also because in Ruby it would hide any missing method error inside the `cmd_*` calls.

**Comment by asterite** [comment]
I'll close this. We have no plans of implementing `send` or providing a macro in the standard library for this.
