### ISSUE TITLE
is_a? failure (always false) in macros

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1471]
The first 2 lines should say `foo Int32`
```
bar Int32
bar Int32
bar Int64
bar Int64
```

```
class C(T)
	def foo bar
		{% if T.is_a?(Int32) %}
			puts "foo #{T}"
		{% else %}
			puts "bar #{T}"
		{% end %}
	end
end

f = C(Int32).new
f.foo "a"
f.foo 1

f = C(Int64).new
f.foo "a"
f.foo 1
```

http://carc.in/#/r/f9b

**Comment by jhass** [comment]
No, Int32 is not an instance of Int32: http://carc.in/#/r/fa3

**Comment by asterite** [comment]
Also note that in macros, `is_a?` determines if a node is of a given type: http://crystal-lang.org/api/Macros/ASTNode.html#is_a%3F%28name%29%3ABoolLiteral-instance-method

We might want to test real types and this will need to change, or we just need to define `is_a?` in macros in a different way for TypeNode.

**Comment by jhass** [comment]
`object.is_a? Type` should mean "is an instance of Type or one of its subclasses or including types in case of a module", defining `TypeNode#is_a?` to "is equal to Type or a subclass of Typ or a including type of Type in case of a module` is just plain inconsistent and confusing. Let's find a different name instead, or even requiring  `klass.ancestors.includes? Type` would be okay with me.

**Comment by asterite** [comment]
Oh, definitely, I see what you mean.

**Comment by waterlink** [comment]
If you want to provide `is_a?` that will introspect on underlying type of
an ASTNode, then it would be good to provide alternative method as a
replacement for current behavior, since it is useful sometimes to switch on
ASTNode type.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 16:36 GMT+02:00 Ary Borenszweig <notifications@github.com>:
