### ISSUE TITLE
macro methods don't support polymorphism

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1590]
``` crystal
require "json"

module DDP
  abstract class Message
    def initialize(@type)
    end

    macro def self.parse(json) : Message
      hash = JSON.parse(json)
      raise "malformed json: #{json}" unless hash.is_a?(Hash)
      type = hash["msg"]?
      raise "malformed message: #{json}" unless type
      case(type)
      {% for subclass in @type.subclasses %}
      when {{subclass.name.split("::").last.underscore}}
        {{subclass}}.from_json(json)
      {% end %}
      else raise "unknown message type: #{type}"
      end
    end

    def on_response
    end
  end

  class Connect < Message
    json_mapping({
      type: { key: "msg", type: String },
    }, true)
  end
end
```

raises `Error in ./src/ddp/message.cr:8: expected 'parse' to return DDP::Message, not DDP::Connect`

**Comment by bcardiff** [comment]
As a big picture feedback it will be good to achieve integration with the pull parser and not from a whole string. Among that way reading from the pull parser until a type key is found would prevent for parsing almost twice the json, specially if the type key is at the beginning. But, if the order is not required a way to rollback/replay the underlaying io will be needed. This was probably mention IRL so I just wanted to noted here since it's a good example where it is need.
