### ISSUE TITLE
Improved spec library

### ISSUE THREAD

**Issue by booch** [manastech/crystal#167]
Our `Spec` class could use some improvements, to bring its feature set closer to something like RSpec:

* Something similar to RSpec's `let` and `let!`
* Something similar to RSpec's `before` blocks to help with setup
* Something like RSpec's `subject`
* Make it easier to define custom expectations (matchers)
* Isolate expectation methods (`eq`, `be_true`, etc.) so they don't pollute global method namespace
* Something similar to RSpec's newer `expect` syntax, or Hamcrest matchers' `assertThat` syntax, so we don't have to pollute `Object`'s namespace

These will likely require a major overhaul to the `Spec` class. It might make sense to replace the class instead.

**Comment by PragTob** [comment]
Hi @booch could you maybe make the list into a check list (e.g. `- [ ]` and `- [x]`) so it is easier to track what has already been done? E.g. I see there's already `before_each`.

Thanks!
Tobi

**Comment by waterlink** [comment]
@PragTob `before_each` implementation is global currently.

That is because currently there is no scoping of `describe` and `context`, and examples are executed as soon as encountered. Effectively, `describe` and `context` just modify example description prefix and execute their block, and `it` appends last description to example and executes its block. All of them just normal global methods.

Because of that `before`, `after`, `let`, `let!` are not achievable. At least not to the functionality similar to `RSpec`.

To achieve that (+ additionally random order example execution), we will need to define examples inside of context without actually executing them, and we need to remember all calls to `before`, `after`, `let`, `let!` and determine which example group they are in. After that we actually run all examples with all `before`, `after`, `let`, `let!` and `subject` applied to their respective example groups.

This can be achieved easily in the same way `RSpec` does it - class inheritance. I tried doing so and compilation of compiler and stdlib takes ridiculously long time, as well as test suite run. RAM consumption is much higher too. This is actually expected, since it generates tons of classes inheriting from each other.

Other way, will be not that simple, but still not very complex: `describe` and `context` create some sort of `Context` object and set it to currently active globally (or thread-local?) while running provided block. `it`, `let`, `before` and friends register their respective blocks to the current context. Then `Runner` jumps in, it will take care about execution order of these blocks. This will definitely allow to make `before` and `after` possible and scoped to proper example group, but what about `let` and `subject`? - since we are not in derived class here, we can't just define method with that name - we need some smarter way of making these names available to example, and even making them lazy..

**Comment by ysbaddaden** [comment]
Just for reference: the describe/before/after/let macros to generate test classes/methods with inheritance are implemented in my [minitest](https://github.com/ysbaddaden/minitest.cr) port. I didn't bench compile time and memory usage thought, but the more classes there are, the slower crystal compilation gets, so I'd expect it to get slower over time with many nested describes and let overrides.

**Comment by asterite** [comment]
I'll close this. `spec` works fine. If you want a `before` hook, define a private method and invoke it. That way specs are also easier to understand and there's no magic. And `expect(...).to ...` is a bit more verbose than should and I kind of dislike it (had to use this for some time in a Rails 4 project and it's so tedious).

Alternatively, use [minitest.cr](https://github.com/ysbaddaden/minitest.cr) if you need other funcionality, `crystal spec` works fine with that too.

**Comment by PragTob** [comment]
@asterite one of my main gripes with spec is also that all of the methods are implemented on a global level afaik. Are you open for improvements in that regard?

**Comment by asterite** [comment]
@PragTob Did you find any conflicts so far?

**Comment by PragTob** [comment]
@asterite no, I just believe that no library should define methods on the main scope. I never know what a library will be used for, and maybe some application wants to define methods like `eq` and `be_true` and it wants to use `spec` for tests. Or.. afaik `describe` and `it` . Polluting name spaces like that is not good imo.

**Comment by asterite** [comment]
@PragTob You mean something like [this](http://play.crystal-lang.org/#/r/hlt)?

The "problematic" methods are `should` and `should_not`. But if you write specs (and you probably do) you won't use those names in your objects. Same as you wouldn't use `object_id` for your objects, or define a `same?` method, or a `hash` method that doesn't return a hash code, etc.

I believe (and you said "I just believe") this is more of a philosophical issue rather than a concrete one. For the time RSpec had them as globals, nobody complained and it worked fine. Then they had issues with BasicObject and blank slates and many things that just don't exist in Crystal, so they changed it.

We also define `to_json` for all objects, but nobody seems to complain about that.

**Comment by PragTob** [comment]
@asterite no I'm not talking about should/should_not - not a big fan of those but I agree that it is nicer to type than the `expect` way. Also, with crystal featuring method overloading we could type them appropriately and as long as no one would define a `should` method that takes an Expectation as well, then we're all ok and this actually works.

I'm talking about all the matchers (`eq`, `be_true`) being defined on the main object/default scope (as well as describe, it and so on). So for instance `be_true` and `eq`. I.e. more like [this](http://play.crystal-lang.org/#/r/hma) - which causes a compiler error due to the conflict.

Alltogether that are ~20 methods defined on the main object/global scope that no one using `spec` can define, without potentially messing with spec (granted that through method overloading, this will work a lot of times as opposed to ruby).

**Comment by schmurfy** [comment]
On ruby I am still running with bacon both for personnal and work projects and I mostly ignored the trend about rspec (which for me provides a lot of useless features for my needs), bacon let me write this:
```ruby
should 'add numbers' do
  add(1, 4).should == 5
end
```

compared to what crystal currently has:
```ruby
should 'add numbers' do
  add(1,4).should eq(5)
end
```

Only a `should` method is defined on Object which never conflicted with anything I used until now (roughly 7 years) and allows using existing methods, in addition I find the first to be more readable than the later but it might just be me.

**Comment by georgeu2000** [comment]
I too was looking for `let` syntax...

**Comment by RX14** [comment]
The best way to do things you'd do with `let` and `before`/`after` is to either use helper methods to abstract creating objects, or use a helper method with `yield` to surround your spec code with code which is before and after. Here's a good example of helper methods and their usage: [1](https://github.com/RX14/pomfire/blob/cb574f422b086a7f640665c408eb0b9ca22daab5/spec/spec_helper.cr#L21) [2](https://github.com/RX14/pomfire/blob/cb574f422b086a7f640665c408eb0b9ca22daab5/spec/pomfire/file_cache_spec.cr)

**Comment by alexanderadam** [comment]
@georgeu2000 well, @waterlink got you covered with [spec2.cr](https://github.com/waterlink/spec2.cr#let).
