### ISSUE TITLE
Scheduler.yield does not yield to other Fiber

### ISSUE THREAD

**Issue by ddfreyne** [manastech/crystal#1683]
In the following example, I run an HTTP server in its own fiber, while the main fiber has a loop that does nothing:

```crystal
require "http/server"

spawn do
  server = HTTP::Server.new(8090) do |request|
    puts "Got a request! #{request}"
    HTTP::Response.ok "text/plain", "Hello world!"
  end

  puts "Listening on http://0.0.0.0:8090"
  server.listen
end

puts "Waiting…"
loop do
  Scheduler.yield
end
```

Fetching `http://0.0.0.0:8090` times out.

Adding a `#puts` in the loo in the main thread makes the issue disappear.

**Comment by ddfreyne** [comment]
Replacing the `Scheduler.yield` with a `sleep(0)` also makes the issue disappear.

**Comment by ysbaddaden** [comment]
Scheduler is an internal detail, and it's not supposed to be used directly.

We're missing convenience methods to prevent the program from exiting (maybe supervisors would help), and I'm not exactly sure what to use for now, except for `loop { sleep 1 }`.

**Comment by asterite** [comment]
@ddfreyne Could you detail your use case or what you are trying to achieve? My guess is, because `spawn` isn't documented and `Scheduler.yield` isn't public API, that you are somehow misusing them. In any case @waj thinks this should work somehow... but I think channels should be used here. What do you need to do in the main fiber besides looping endlessly?

**Comment by ddfreyne** [comment]
This is part of a game, and so the main fiber loops endlessly, as fast as possible, to render/update game state.

**Comment by waj** [comment]
I probably didn't write `Scheduler.yield` with this in mind. Currently what it does is put the current fiber at the end of the runnable queue and resume the next available fiber. Because there is no other fiber ready to be run, it returns to the same fiber without giving the network poller the chance to catch up with incoming connections.

One possible solution would be putting the current fiber on a separate queue (yielded fibers) and if there is no other fiber in the runnable queue, pass all the yielded fibers to the runnable queue and give the network poller the chance to run but without blocking, and only after that continue running with the next runnable fiber.

This actually happens to be semantically equivalent to do `sleep(0)`, which doesn't put the fiber in the runnable queue but sets a callback in the event loop to resume the execution of the fiber. Because the timeout is set to 0, the event loop doesn't block and the fiber is resumed immediately if there was no other pending events. So this should work as a good workaround for you in the meantime.

I actually wonder if we shouldn't just make `Scheduler.yield` do a `sleep(0)` instead of the more complex logic described before. Well... actually the advantage would be making less context switches when there are no pending IO events to process because the call to the poller could be done in the same fiber yielding the execution.

**Comment by kostya** [comment]
why not just `sleep` which is sleep infinitely?

**Comment by waj** [comment]
why would you want a fiber that sleeps forever?
