### ISSUE TITLE
Equality comparison between Char and single character String give unexptected result

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1730]
I don't know the expected behavior but my intuitive expectation was that the tests below would give  results opposite of that which is shown.

```
puts '.' == "." # false
puts "." == '.' # false

puts '.' != "." # true
puts "." != '.' # true
```
*EDIT: To clarify, the expected result was given that the comparison between different types is allowed. I assumed this was true for a reason.*

**Comment by kostya** [comment]
i think its ok, crystal is not php.

**Comment by Perelandric** [comment]
@kostya But then why does the type system allow the comparison if the result will always be `false`?

**Comment by ozra** [comment]
Well if you have some object with a value field that can be either String, Symbol, etc. etc., then when in a `case` statement you want the comparison to check type and value to get a correct match - not coercion that would cause confusing errors.
For coercion it'd be better with another comparison operator, say `~=` or something.
(Javascript has `==` coercing and `===` comparing type and value)

**Comment by kirbyfan64** [comment]
IMO, this should be an error. It costs 3 more characters to put `[0]` to get the first character of a string literal.

@ozra `~=` is too similar to `=~`: http://play.crystal-lang.org/#/r/ira.

**Comment by Perelandric** [comment]
@ozra It isn't that I want coercion. It's that the comparison is allowed but gives a confusing result. Why allow those two types to compare if there's no possibility of a `true` result? If they are intended to be comparable, then fine, but IMO the result should be more sensible.

@kirbyfan64 If you mean the `'.' == "."` should be an error, I agree. That it wasn't an error was confusing until I realized I had `(Char | String)` instead of `String`.

**Comment by ozra** [comment]
@Perelandric I don't think I made myself clear. The current behaviour is the expected behaviour. A lot of my code depend on equality being value+type == value+type. If it would throw an error comparing two values of different types there's no point having sum types (unions) at all - how would you conditionally branch without a shitload of type-checking crust for every test?
I simply works as it should afaic.

Also, if the variables has specific (non union), but differing types, it may be so in _one_ instantiation of a method, but not in another - so the test is still valid.

**Comment by kirbyfan64** [comment]
Well, maybe `==` should return `false` for different types, regardless...

**Comment by Perelandric** [comment]
@ozra That's foreign to me. I'm not saying I'm right but I can't fathom not wanting to know why something failed.

My (albeit limited) experience with sum types has been to receive one of many types but then explicitly separate them by type and work with them as such unless there's some useful behaviors that would obviate the need. So I think *"there's no point having sum types (unions) at all"* is overstated.

For example, I can see `String + (Char | String)` being allowed because there's a useful result either way. But with equality, if such a comparison will always fail, then I don't see the use in it. I don't know if it was the wrong type or the wrong value or both.

If the type system forced me to acknowledge it, then at compile time I know that I need to take some action instead of wondering why it failed at runtime only to find that I typed `'.'` instead of `"."` somewhere.

**Comment by waj** [comment]
@Perelandric not always the compiler can save you from coding errors, and in this case we prioritise convenience. Otherwise, as @ozra explained, you'll have to always first check the type of the value before comparing with another value.

For example, let say `foo` is a variable of type `String | Nil` (a nilable string). If you want to check if the variable has the value "bar", instead of just writing:
```crystal
foo == "bar"
```
you'll have to write something like:
```crystal
foo.is_a?(String) && foo == "bar"
```

Not to mention that I have no idea how we could posible write a `Hash` class that allows keys of union types. It's very important in this case that the objects can be compared between them regardless of their types.

One last comment that doesn't try to prove anything, but have served as inspiration, in Java and C# for example, the Object class has an "equals" method that allows comparison of objects of any type.

**Comment by Perelandric** [comment]
@waj And that's fine. I sure won't fight it.  However,  just as `nil` not equaling any `String` makes sense, IMO a single character `String` being potentially equal to a `Char` would seem to make sense.

If it isn't meant to be, no problem. I just don't see a downside, given that the types need to be comparable anyway. Is there ever a case where you'd *not* want `'.' == "."` to be `true`?

**Comment by ozra** [comment]
@Perelandric - sorry, was a bit dramatic in my statements. I still think this could be a good comparison to be _possible_ to make (and well, I call it coercing comparison). Still, I think it should use special comparator since it's not precise predictable behaviour. Another suggestion, after @kirbyfan64 pointed out confusing similarity: `puts "Yeay!" if some_str ~~ some_char`

**Comment by jhass** [comment]
We already have a "less strict `==`" that's used for example in `case when` statements: `===`

**Comment by Perelandric** [comment]
I don't think we need another operator. If it won't allow any positive result, then I'll just remember to do `(String | Char).to_s == String`. *(I can't use `[0]` without first testing `s_or_c.is_a?(String) && s_or_c.size == 0`)*

My only question at this point is why not allow a positive result in what would seem to be sensible cases? Is there some drawback?

I won't press this any further. Feel free to close if it just won't happen.

**Comment by asterite** [comment]
@Perelandric Following the same logic, is there a reason why `"123" == 123` shouldn't be true? In what case you want that to be false?

**Comment by kirbyfan64** [comment]
@asterite IMO, it should return false. Returning true is deadly JavaScript territory.

**Comment by Perelandric** [comment]
@kirbyfan64 JavaScript certainly takes it too far, or at least too far for a language like Crystal IMO. I wouldn't think it would need to be all or nothing.

@asterite Yes, because a string and a number have a much greater difference than a string and a character. I'd want it to be false in all cases.

Like I said, if possible I'd prefer that the compiler not allow Char/String comparison, but I understand it's needed. Given that, a String and a Char are potentially holding the same binary data, just in slightly different form. `"123" == 123` requires parsing.

But again, these are just my opinions. I'm not going to push for it. I just think it's unfortunate that if they're going to be comparable, there can be no meaningful comparison in those narrow cases where it would be intuitive without ECMA-esque confusion.

**Comment by ozra** [comment]
@jhass - oh, reverse JS-notation :) Have to check that one out.

**Comment by asterite** [comment]
> "123" == 123 requires parsing

Well, to compare `"あ" == 'あ'` you can't do a memcmp, because the char's data is not in memory as an UTF-8 encoded byte array. For that, you first need to check that the string's size is 1, which involves decoding the string to find out its size (it's cached afterwards, but still...), and just then to compare the char.

So it's far from a trivial comparison, and it can slow down things.

**Comment by Perelandric** [comment]
@asterite I see. Since it seems clear that this is not in the cards, I'll go ahead and close it. I like Crystal quite a lot so far; I think I just need to get used to its type system.
