### ISSUE TITLE
Formatter: right side comments inside comment's code blocks are incorrectly aligned

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1756]
I know, very mouthful, but bear with me while I try to describe the issue :smile: 

Inline comments placed on the right side of the code are properly aligned when the code is formatted.

Example diff:

```diff
   class MultiRouter < Beryl::Router
     routing do
-      get    "/products",     DummyAction # [0]
-      post   "/products",     DummyAction # [1]
-      get    "/products/:id", DummyAction # [2]
+      get "/products", DummyAction        # [0]
+      post "/products", DummyAction       # [1]
+      get "/products/:id", DummyAction    # [2]
       delete "/products/:id", DummyAction # [3]
     end
   end
```

However, when the comments are inline inside code blocks, those are re-aligned closest to the code or completely stripped of all spaces, like the following example:

```diff

       # ```
       # tree = Tree.new
-      # tree.add "/", :root           # /         (:root)
-      #
-      # tree.add "/abc", :abc         # /         (:root)
-      #                               # \-abc     (:abc)
-      #
-      # tree.add "/abcxyz", :xyz      # /         (:root)
-      #                               # \-abc     (:abc)
-      #                               #     \-xyz (:xyz)
+      # tree.add "/", :root # /         (:root)
+      #
+      # tree.add "/abc", :abc # /         (:root)
+      # # \-abc     (:abc)
+      #
+      # tree.add "/abcxyz", :xyz # /         (:root)
+      # # \-abc     (:abc)
+      # #     \-xyz (:xyz)
       # ```
```

Perhaps this is expected for those lines without code, but not sure if the re-align of the comment for the ones with code is correct.

Thank you. :heart: :heart: :heart:

**Comment by asterite** [comment]
The problem is how to recognize this:

```crystal
a = 1 # this comment
      # continues
b = 2
```

from this:

```crystal
a = 1 # this is one comment
# this is for the one below
b = 2
```

The formatter doesn't take existing indentation into account, so it can't distinguish between the two cases.  However, maybe we can decide that two comments are still considered "consecutive" if there's no newline between them. The second code would be incorrectly aligned, but to fix it you'd leave a newline before `b = 2`. I think it'll also be more visually understandable.

What do you think?

**Comment by asterite** [comment]
As a side note, this happens in regular code, not only in comments inside comments. Comments inside comments are formatted just like regular code (recursively, try it! :-))

**Comment by luislavena** [comment]
> The second code would be incorrectly aligned, but to fix it you'd leave a newline before b = 2. I think it'll also be more visually understandable.

I think that compromise is OK, besides for readability you will split your code blocks :smile: 

> As a side note, this happens in regular code, not only in comments inside comments

Weird, see my first case, the comments on the right side are still aligned, only the ones in new lines are messed up (as you described).

See this:

```crystal
# ```
# tree = Tree.new
# tree.add "/", :root # /         (:root)
#
# tree.add "/abc", :abc # /         (:root)
#
# tree.add "/abcxyz", :xyz # /         (:root)
# ```
```

The problem seems to be the new lines between the lines of code, if there is no new line, all comments remain aligned :thumbsup:

**Comment by ozra** [comment]
When I have comments _before_ a line, I always prefix it with a newline for clarity. So I definitely vote for 'empty line' as separator of natural groupings.

**Comment by asterite** [comment]
After some though, I'm not so sure about this.

The formatter fixes spaces and indentation problems, and re-aligns comments, but it never takes the existing code's space/indentation into account (because that info might be wrong). So, let's say we have:

```crystal
a = 1 # this comment
      # belongs to a
```

Seems natural to align it all together. Next we have:

```crystal
if some_condition # this condition is triggered
                  # in some particular cases
  a = 1
end
```

Again, seems natural to align the comments. But then:

```crystal
if some_condition # if X
  # assign to a
  a = 1
  # assign to b
  b = 2
end
```

Now it doesn't seem good to align the first two comments, but this is exactly the case above: there's no way that the formatter can distinguish both unless it takes the current space info into account (which it won't).

Or:

```crystal
if some_condition
  # here comes the hard part
  a = foo # first assign to a
  b = 3   # then b
end
```

You wouldn't want to align the first comment with the others, but they all come in consecutive lines.

In short, the formatter will align successive comments on the right-hand side of a line if they all have an expression on the left. That's the only rule.

So, I'd suggest that if you have existing code like this:

```crystal
tree = Tree.new

tree.add "/", :root           # /         (:root)

tree.add "/abc", :abc         # /         (:root)
                              # \-abc     (:abc)

tree.add "/abcxyz", :xyz      # /         (:root)
                              # \-abc     (:abc)
                              #     \-xyz (:xyz)

tree.add "/", :root           # /         (:root)

tree.add "/abc", :abc         # /         (:root)
                              # \-abc     (:abc)

tree.add "/abcxyz", :xyz      # /         (:root)
                              # \-abc     (:abc)
                              #     \-xyz (:xyz)
```

(and note that in the above case if we align successive comments they will still not be aligned different comment sections, because the expression lengths are different)

You change it to this:

```crystal
tree = Tree.new

# /         (:root)
tree.add "/", :root           

# /         (:root)
# \-abc     (:abc)
tree.add "/abc", :abc         

# /         (:root)
# \-abc     (:abc)
#     \-xyz (:xyz)
tree.add "/abcxyz", :xyz      

# /         (:root)
tree.add "/", :root           

# /         (:root)
# \-abc     (:abc)
tree.add "/abc", :abc         

# /         (:root)
# \-abc     (:abc)
#     \-xyz (:xyz)
tree.add "/abcxyz", :xyz      
```

Finally, not that it matters much, but gofmt also applies the same rule I described above.

**Comment by luislavena** [comment]
@asterite thank you for taking the time to respond and provide the reasoning behind the decision.

Cheers.

**Comment by straight-shoota** [comment]
I noticed the style that an end-line comment is continued in the next line (without there being an expression in the next line) is used a lot in [crystal-book examples](https://github.com/crystal-lang/crystal-book). When passing that through the formatter, it breaks the intended format.
It's probably possible to change most of these case, for example refactoring to full-line comments.

But I would actually suggest reconsidering the formatter behaviour. IMO it would make sense to use this rule: End-line comments in consecutive lines are aligned at the same column. Full-line comments following a line with end-line comment are aligned with the end-line comment. In order to break the alignment, you need to put in an empty line (or more general, a line without a comment).

I agree with https://github.com/crystal-lang/crystal/issues/1756#issuecomment-148938893 that a full-line comment should usually be prefixed by an empty line. That's especially when directly following an end-line comment. 
When @asterite's examples from https://github.com/crystal-lang/crystal/issues/1756#issuecomment-148876817 and https://github.com/crystal-lang/crystal/issues/1756#issuecomment-150920444 follow that rule, there'd be no ambiguity about comment alignment.
```cr
a = 1 # this is one comment

# this is for the one below
b = 2
```
```cr
if some_condition # if X

  # assign to a
  a = 1
  # assign to b
  b = 2
end
```

**Comment by straight-shoota** [comment]
A little bit odd is the formatter behaviour with `end`:
```cr
foo do
  foobar # comment
end # other comment
```
formatted:
```cr
foo do
  foobar # comment
end      # other comment
```
