### ISSUE TITLE
Formatter: Final trailing comma in ArrayLiteral

### ISSUE THREAD

**Issue by jessedoyle** [manastech/crystal#1780]
Awesome work on the formatter!

Currently the formatter will format the following code:
```crystal
arr = [
  :one,
  :two,
  :three
]
```
as such:
```crystal
arr = [
        :one,
        :two,
        :three,
      ]
```

Notice the final comma after `:three` in the formatted code. I'm fairly certain this trailing comma should be omitted from the formatted code as it is entirely redundant.

**Comment by waterlink** [comment]
To my opinion this is a good thing. This makes easier to append to array
and especially re-order items in array without going into typing mode (you
don't have to insert and remove coma anymore). And this is de-facto
standard coding style in ruby communities (as far as I know) - I think it
is good to follow.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-10-19 7:52 GMT+02:00 Jesse Doyle <notifications@github.com>:

**Comment by veelenga** [comment]
According to a [community-driven Ruby coding style guide](https://github.com/bbatsov/ruby-style-guide#collections) this is not a desired style:

>  Avoid comma after the last item of an Array or Hash literal, especially when the items are not on separate lines.

> ```ruby
# bad - easier to move/add/remove items, but still not preferred
VALUES = [
  1001,
  2020,
  3333,
]
# bad
VALUES = [1001, 2020, 3333, ]
# good
VALUES = [1001, 2020, 3333]
```

But when items are on separate lines (as it is in Crystal) I agree with @waterlink, it's better to have a comma at the end, because it is easier to append and reorder.

**Comment by asterite** [comment]
In this case I decided not to go with the Ruby style guide. The reasons are all what @waterlink said. Much easier to refactor and modify code that way.

Also note that Go forces you to write a comma in that place too, so we aren't the only ones who think that.

**Comment by jessedoyle** [comment]
Okay, I wasn't sure if it was intentional or not. Thanks for the info!

**Comment by waterlink** [comment]
Fun fact: go forces it only because go tokenizer is not capable to deliver
parse-able token stream if you omit coma on multiline literals. This
happens because tokenizer inserts auto-semicolons at the end of each line
that abides to 2 very simple rules. So if you are not putting coma there,
go tokenizer will put semicolon there, which will not result in valid go
code :)

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-10-19 16:30 GMT+02:00 Jesse Doyle <notifications@github.com>:

**Comment by kirbyfan64** [comment]
All to say...

Go is weird. :)
