### ISSUE TITLE
forward_missing_to causes segment fault when target does not exist

### ISSUE THREAD

**Issue by Ragmaanir** [manastech/crystal#1826]
```crystal
class X
  forward_missing_to x
end

X.new.test # Program exited because of a segmentation fault (11)
```

**Comment by asterite** [comment]
This is not a bug, you get a stack overflow at runtime. Basically `forward_missing_to` just declares `method_missing` that forwards the call. So your code becomes:

```crystal
class X
  macro method_missing(name, args, block)
    x.\{{name.id}}(\{{*args}}) \{{block}}
  end
end
```

When you invoke `X.new.test`, that generates:

```crystal
class X
  def test
    x.test
  end
end
```

In that method `x` is a call, and we hit method_missing again, thus generating:

```crystal
class X
  def x
    x.x
  end
end
```

and there's the stack overflow.

I guess this will be more evident once we can say "Segmentation fault" and show some of the stack trace instead of a mere segfault. I'll relate https://github.com/manastech/crystal/issues/271 to this.
