### ISSUE TITLE
Can there be (or is there) a "clean" command for Crystal projects?

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1853]
After stumbling on a couple compiler bugs and implementing workarounds, I suddenly started getting this:

>ld: mach-o string pool extends beyond end of file file './.crystal/path/to/File.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/path/to/project/.crystal/crystal-run-example.tmp" "${@}"  -rdynamic  -levent -lpcl -lpcre -lgc -lpthread -ldl`

So I thought perhaps the hidden `.crystal` directory simply needed to be deleted. First I looked for a `crystal clean` to clean the build files but didn't see one, so I did a `rm -r .crystal` but not without some trepidation.

Everything worked out but I think it would be nice if there was a `crystal clean` in order to safely clean up build files.

Is this a possibility or am I missing something that exists?

**Comment by asterite** [comment]
Ideally the compiler should work even if there's something broken in the cache. I'm not sure we want to expose a way to clean up the cache, it's a compiler detail.

**Comment by Perelandric** [comment]
@asterite Yeah its the kind of thing that should rarely be needed. If the compiler could catch stuff like this, it would certainly be better.

**Comment by asterite** [comment]
For now `rm -rf .crystal` is fine and should never be a problem, it's only cache :-)

**Comment by Perelandric** [comment]
Alrighty, I'll be good with that.

**Comment by veelenga** [comment]
You can automate a `.crystal` directory removal with a makefile also. [Here](https://github.com/porras/crul/blob/master/Makefile) might be a good example.

**Comment by Perelandric** [comment]
Thanks for the info @veelenga.

**Comment by jeromegn** [comment]
I just stumbled on this after probably hundreds of runs (compiles) of my crystal program:

Something like: (I have lost the exact original message due to scrollback buffer in my terminal)

```
mach-o symbol table extends beyond end of file file
```

My cache was huge (`~/.cache/crystal`), I cleared it after reading this post: https://lists.apple.com/archives/xcode-users/2012/Mar/msg00501.html which seems to mention incremental builds being the issue.

Works fine after purging the cache. Could we find a way to automate this maybe? When this occurs, it's pretty cryptic, there's no obvious way to fix it. It may deter people from using Crystal if you can only run a program xxx times before we're unable to compile it.
