### ISSUE TITLE
Can't mutate a struct in an Array.

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1862]
The code below creates an array of structs and then attempts to modify the second member of the array. The mutation does not hold. Seems like a copy is made even though it isn't assigned to a variable.

http://play.crystal-lang.org/#/r/lsb

```
struct Test
  property b
  def initialize(@b)
  end
end

t = [
  Test.new(false),
  Test.new(false),
  Test.new(false),
  ]

t[1].b = true # Set the second to `true`

puts t # All still false
```

Using a `class` instead of a `struct` works of course.

Is this the intended behavior?

**Comment by kostya** [comment]
struct is value, class is reference, so you should t[1] = Test.new(true)

**Comment by Perelandric** [comment]
@kostya I guess that's the question. Since I'm mutating an Array member, I would expect that exact memory location to be updated, just like if I was mutating a variable. 

If I assigned it to a variable first, that would be different. I wouldn't expect the Array to be modified in that case.

**Comment by kirbyfan64** [comment]
I would say this should preferably work (it works in C), at minimum give an error. I'm guessing it's that the compiler basically does this:

```crystal
tmp = t[1]
tmp.b = true
```

**Comment by Perelandric** [comment]
@kirbyfan64  Yeah, that's what I'm guessing too. Either here or in the `[]=` method since there seems to be an underlying buffer.

Works in Go: http://play.golang.org/p/_2qYw5b3Vw
and in Ruby: https://repl.it/BWQt *(I'm not a Ruby dev, so I'm guessing this is correct)*

So I think it's probably a bug. It would seem odd if we couldn't mutate Array memory directly.

**Comment by asterite** [comment]
Since `Array#[]` is a method and it returns a struct, the struct is returned by value, just like any other method that returns a value. So this is not a bug.

In Go it works because Go has very few primitive types and can do such analysis, but Array is not a built-in in Crystal (it's implemented in Crystal just like if it were any other user type). In Ruby it works because Ruby doesn't have real structs.

In C# they do give you an error:

```csharp
using System;
using System.Collections.Generic;

public struct Point {
  public int X {
    get;
    set;
  }
}

public class Foo {
  public static void Main(string[] args) {
    List<Point> points = new List<Point>();
    points.Add(new Point());
    points[0].X = 10; // Cannot modify a value type return value of `System.Collections.Generic.List<Point>.this[int]'. Consider storing the value in a temporary variable
    Console.WriteLine(points[0].X);
  }
}
``` 

But that's because I use a property. If I use a regular method that mutates self:

```csharp
using System;
using System.Collections.Generic;

public struct Point {
  public int X {
    get;
    set;
  }

  public void SetX() {
    this.X = 10;
  }
}

public class Foo {
  public static void Main(string[] args) {
    List<Point> points = new List<Point>();
    points.Add(new Point());
    points[0].SetX();
    Console.WriteLine(points[0].X);
  }
}
```

Then it compiles just fine.

The main issue in Crystal is that the case you mention is just method calls, there isn't much else in Crystal. We can fix this in several ways:

1. We remove structs from the language: if everything is a class then the problem disappears
2. We disallow mutating structs. The problem disappears, but you can't express some things in a very efficient way.
3. We keep the current way, and you have to be careful about mutating structs.

The current way is 3. And in my experience you immediately can tell that something is wrong if you try to mutate a temporary struct value, so in my opinion it's not a big problem. Crystal is mostly a high-level language with some low-level stuff to allow implementing some things in a fast way in the language itself, but this comes with a small price (some unsafety, or some unexpected behaviour when using structs).

**Comment by Perelandric** [comment]
@asterite 

Thanks for the info. I can make a local copy and mutate then copy back into the Array.

Just curious, is there no way to take a pointer to the address of an Array member in Crystal? Could a method to return a pointer to a member be added?

In the case of an Array of structs, I assume an Array is structured as a contiguous block of memory that is `sizeof(MyStruct) * my_array.size`. Is that right?

**Comment by omninonsense** [comment]
@Perelandric That seems kinda inefficient (copy, edit, copy back), especially if the struct is large. You could get the pointer to the struct, and then modify it (http://carc.in/#/r/lsy **NOTE**: there *might* be a better/smarter/safer way than this).

@asterite I am a fan of option 1 ("remove structs from the language"), if someone needs a copy of the value, they can always explicitly copy it, right?

**Comment by Perelandric** [comment]
@omninonsense 

These structs aren't too large and the writes happen seldom compared to the reads. 

Accessing heap memory has its own inefficiencies. I'm pretty sure that's why Crystal has structs in the first place, for performance reasons. I hope they won't be removed.

Thanks for the code on the pointer. That's helpful.

**Comment by ozra** [comment]
I totally would expect to be able to mutate it too - only seeing the allocation method being different (saving an indirection and shitloads of small GC allocations). 
I fully get the explanation for why it's not (supposed to be) working. But it feels like something that has to be "fixed" imo.

But I would prefer being able to declare a instance variable or an array as `the_var : byval SomeType` (whichever syntax for that...) rather than saying the type itself is by-val or by-ref (well having a default is good..). So changing the allocation scheme, and the semantic fact that it is a copy, at use-site. And yeah, still being able to be evil and mutate of course B-) So, if it is "by value" as a member in an object, accessing it would mean accessing a reference through a method (that returns a reference to the value stored inline with its container). This would be an 'insider-pointer', but current GC can handle that so, *shrugs*.

So, no "structs", just "types", and allocation-scheme specified for use-scenarios. But the 'struct-mode' could be turned into a "default to by-val when not specified". So essentially it's still there, but not a thing that must be inherited, as now.

This sort of tinkering is of course needed for performance coding reasons only.

I know I've ranted about this like three times before, but...
