### ISSUE TITLE
HTTP::Server.listen_fork 

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#1931]
I want to use `listen_fork` but can't understand why `gets` is here https://github.com/manastech/crystal/blob/master/src/http/server/server.cr#L126

**Comment by ilatif** [comment]
I think `gets` is there because as new processes are forked, listening of incoming requests are delegated to them and unlike `listen` method there is no `server.accept` which can keep listening to new sockets in current process. So `gets` is being used as a way to give illusion that like `listen`, `listen_fork` has retained control after forking new processes.

**Comment by ilatif** [comment]
I mean in `listen`, the current process itself is listening for new sockets which makes us feel that server has gained control and itself processing our requests. But in `listen_fork`, handling incoming requests and returning responses to them is handled by newly forked process and if `gets` is not there, there will be no `listen` like control retaining thing in terminal and the logs will be printed in terminal without taking into consideration it's current state.

**Comment by ilatif** [comment]
I however feel that `gets` is not an ideal thing for this but sometimes during `development` one presses `Enter` key to feed some empty lines so that logs of new requests can be seen clearly. In `listen_fork` if you press enter, the control retaining is gone and you will end-up seeing logs in terminal. I think the better would be to use something like:

```ruby
  until @wants_close
    gets
  end
```

In this way, no matter how many `Enter` keys you pressed, you will still in control retaining thing in `listen_fork`.

Thoughts?

**Comment by ilatif** [comment]
I just confirmed that the code snippet in above comment works perfectly fine. Now matter how many `Enter` keys you pressed, control retaining remain intact. And upon doing `Ctrl + C` all forked process terminated gracefully. Going to submit a Pull Request for this soon.

**Comment by asterite** [comment]
I think `gets` is there because we didn't have argless `sleep` back then.

In any case, `listen_fork` will be removed.

**Comment by sdogruyol** [comment]
Closing since `listen_fork` is removed on https://github.com/manastech/crystal/commit/c527c2f6e241e4463c8700a6cd062ad11f55b769 :+1:
