### ISSUE TITLE
Macro operation order

### ISSUE THREAD

**Issue by dragostis** [manastech/crystal#1959]
The order of operations when using them does not appear to be right:
```crystal
macro pr(ex)
  {{ ex }}
end

puts 1 & 2 & (3 | 4) == pr 1 & 2 & (3 | 4)
```

This prints `false`.

**Comment by asterite** [comment]
Good catch! It's easier to see it this way:

```crystal
macro pr(ex)
  {{ puts ex }}
end

pr 1 & 2 & (3 | 4)
```

**Comment by dragostis** [comment]
Sure. I'll try to take a look into it. Any tips where to start?

**Comment by asterite** [comment]
@dragostis If you want to tackle this, the issue is how an AST node is converted back to a String. The code is [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/to_s.cr) and there are some specs [here](https://github.com/manastech/crystal/blob/master/spec/compiler/parser/to_s_spec.cr). Remember that `&` and `|` are just `Call` nodes.

**Comment by dragostis** [comment]
@asterite I'm currently having some issues with my build (LLVM 3.7 doesn't work; not easy to install 3.5 on Arch).

I took a look at the issue and it appears to stem from [`call_args_need_parens = false`](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/to_s.cr#L266). This should be `true` in case of infix operations that have precedence.

The left paren should then be added [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/to_s.cr#L302).
