### ISSUE TITLE
How to add a hook to inherited classes

### ISSUE THREAD

**Issue by veelenga** [manastech/crystal#1984]
I want to add a `method_added` hook to all subclasses. My try:

```crystal
class A
  macro inherited
    macro method_added(m)
      # ...
    end
  end
end

class B < A
  def foo; end
end
```
And it works, but  I am not able to expand `m` with `{{m}}` because it is not a variable of the outer macro.

Please advise a right way to implement that.

**Comment by asterite** [comment]
You need to escape the inner macro's `{{` and `{%`. For example:

```
class A
  macro inherited
    macro method_added(m)
      \{{ puts m }}
    end
  end
end

class B < A
  def foo; end
end
```

Otherwise, if you do `{{ puts m }}`, the macro will try to expand it as soon as possible. With the `\{{`, the first macro will ignore it but generate `{{ puts m }}` as its output, and then the second macro will expand it.

Kind of confusing, but that's how to deal with nested macros :-)

**Comment by veelenga** [comment]
It works. Thank you :+1:
