### ISSUE TITLE
Unitialized String causes Segmentation Fault

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#2019]
```crystal
class Foo
  getter x, y
  def initialize
    @x = uninitialized Int32
    @y = uninitialized String
  end
end

puts Foo.new.x
puts Foo.new.y
```
When trying to call `Foo.new.y`

```
Using compiled compiler at .build/crystal
0
Program exited because of a segmentation fault (11)
```

**Comment by jhass** [comment]
I don't know what else you expect.

**Comment by asterite** [comment]
@sdogruyol Right now the equivalent is [this](http://crystal-lang.org/docs/syntax_and_semantics/declare_var.html). As it's said there, using this is unsafe.

The 0 is because right now when you do `Foo.new` the compiler will allocate memory for Foo and initialize it to zero, but this might change in the future (we do this because `Nil` always has a type id of zero, so nilable instance variables always get the right type with this trick).

**Comment by sdogruyol** [comment]
Okay, now i get this. 

But shouldn't this be a compile time error when trying to call something uninitialized like `Foo.new.y`?

**Comment by asterite** [comment]
@sdogruyol No, the idea of an uninitialized variable is "Compiler, don't bother me if I don't properly initialize this variable, just consider it initialized". Later, if you don't initialize it, it's your fault, and bad things can happen (including segfaults).

**Comment by sdogruyol** [comment]
This feels really unsafe to me.

Seems like i got used to safety of Rust thinking that this should be a compiler error or at least warning. 

FYI you can close this issue at will.

**Comment by jhass** [comment]
This is really unsafe. This is intentionally really unsafe, it's the reason d'être for this feature. Don't use it until you absolutely need it.

**Comment by asterite** [comment]
Yes, it's unsafe on purpose. In rust you have `unsafe { ... }` which basically is "Compiler, don't check the type safety of this, I know what I'm doing, because I need to do some things here in a way that, by your rules, would be slow". In Crystal we don't have `unsafe { ... }`, but there are just [4 unsafe things](http://crystal-lang.org/docs/syntax_and_semantics/unsafe.html), so it's basically the same.

Oh, I just searched how to do the same thing in Rust, and what a coincidence!

https://doc.rust-lang.org/std/mem/fn.uninitialized.html

It's even named "uninitialized"! I swear we didn't know that before choosing that name. And there's even a big paragraph with the title "Undefined behaviour", and it says in bold "This is incredibly dangerous, and should not be done lightly. Deeply consider initializing your memory with a default value instead." :-)

**Comment by sdogruyol** [comment]
@asterite i didn't know about that. Thanks a lot :smiley:
