### ISSUE TITLE
Compiler in standard library

### ISSUE THREAD

**Issue by greyblake** [manastech/crystal#2070]
Hi!
It would be nice to access some compiler internals programmatically. E.g. for [ICR](https://github.com/greyblake/crystal-icr) I'd like to use `Compiler::Parse.parse` in order to detect syntax errors, before executing the code.

Would you think?
Thanks.

**Comment by asterite** [comment]
The compiler isn't in the [API](http://crystal-lang.org/api/) because it lacks docs and `:nodoc:` to hide non-interesting parts, but it's definitely in the standard library. For example [this](https://play.crystal-lang.org/#/r/qjx).

```crystal
require "compiler/crystal/**"

node = Crystal::Parser.parse("foo.bar")
p node.class
puts "~~~"
puts node
puts "~~~"
puts (node as Crystal::Call).obj
```

In fact, the original `icr` that we had and eventually removed was done using it: https://github.com/manastech/crystal/blob/224a080e1147ecc4adfdc9a80391bed4a9b8233c/src/compiler/icr.cr

**Comment by sdogruyol** [comment]
Wow this is really interesting :+1:

**Comment by greyblake** [comment]
@asterite Super! Thanks!

I've tried similar example yesterday, but looks like I was requiring wrong file name. Your example works perfectly!
