### ISSUE TITLE
Unsupported type for debugging

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2116]
```
$ crystal build linux-setup.cr -o linux-setup-static-32 --link-flags="-static" -d
Unsupported type for debugging: Nil (Crystal::NilType)
Unsupported type for debugging: Nil (Crystal::NilType)
Unsupported type for debugging: String? (Crystal::NilableType)
Unsupported type for debugging: String? (Crystal::NilableType)
Unsupported type for debugging: (Nil | Int32) (Crystal::MixedUnionType)
Unsupported type for debugging: String? (Crystal::NilableType)
Unsupported type for debugging: String? (Crystal::NilableType)
Unsupported type for debugging: String? (Crystal::NilableType)
Unsupported type for debugging: String? (Crystal::NilableType)
...hundreds of lines elided...
```
Huh?

**Comment by waj** [comment]
It's not a bug. The debugging support is far from complete.

**Comment by stugol** [comment]
But I'm not getting a stack trace on an exception either!
```
Nil assertion failed (Exception)
[134620905] ???
[134620772] ???
[134620709] ???
[134630552] ???
[134630475] ???
[134570530] ???
[134722112] ???
[134785335] ???
[134785096] ???
[134568920] ???
[134579405] ???
[136050470] ???
[134518651] ???
```
Shouldn't the `-d` flag make this work?

**Comment by kirbyfan64** [comment]
Honestly, it's a miracle you even got this far with debugging info... See #1321.

**Comment by stugol** [comment]
I only just turned it on, in the hope it would fix my stack traces.

I get exception stack traces when running a Crystal script via the `crystal` command; but not when statically linking it and running the resultant exe on another machine. Why is this? And what can be done about it?

NB: If the `-d` switch is so badly broken, you should remove it. A broken option is _worse_ than useless.

**Comment by waj** [comment]
In Linux, the linker will not export the symbols unless linking with `-rdynamic`, option that you might be overriding while compiling statically. That's why you don't see the symbol names in the backtrace. There are other options to get the symbol names from debug info but it's not implemented yet, so in the meantime I'm afraid you must decide between static linking or better backtraces.

I we removed any incomplete feature we would never move forward. We need all these "incomplete" features so we can test them while we make progress towards 1.0.
