### ISSUE TITLE
URI.escape unhelpful

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2118]
```
require "http/client"
puts URI.escape "http://google.com"
```
Output: `http%3A%2F%2Fgoogle.com`

Is this intended behaviour? Because it really isn't helpful. Now I'll have to split my url into two parts before escaping it.

**Comment by waj** [comment]
That's totally the intended behaviour because it's used to escape URI parts before joining parts, and not after. If you have a uri string it should be already escaped otherwise it's impossible to parse correctly.

An example. Let's say this is your URI before passing to URI.escape: `http://my.host/?q=foo&bar=baz`. You might assume that the escape shouldn't make any change at all, but what if the `q` argument has to be `foo&bar=baz` instead? There are some ambiguity here. That's why URI.escape must be used on each fragment before joining:

```crystal
uri = "http://my.host/?q=#{URI.escape(...)}&bar=#{URI.escape(...)}"
```
