### ISSUE TITLE
there is no previous definition of 'file?'

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2135]
This works:
```
File.file? "/"
```
But [this](https://play.crystal-lang.org/#/r/rye) does not:
```
class File
	def self.file?(filename : String | Int)
		previous_def filename.to_s
	end
	def self.exist?(filename : String | Int)
		previous_def filename.to_s
	end
end
File.file? "/"
```
I'm not actually trying to make these functions accept an `Int` - I've substituted `Int` for the actual class I'm using because it doesn't exist here.

Why does the compiler complain that `there is no previous definition of 'file?'`? Is `previous_def` not the correct tool to use here? In which case, what should I be using instead?

**Comment by asterite** [comment]
With `self.file?(filename : String | Int)` you are defining a new overload, not redefining the previous method, because the previous one just has String as a restriction.

So in your case you have to redefine it for String, use previous_def, and also define a new overload for Int and call whatever you need.

Not sure changing those methods is a good idea, though.

**Comment by stugol** [comment]
Oh, I see. So...I guess the simplest way is just to write a new function taking `Int` (not actually int, obviously), and call the base function from there?

Ruby doesn't overload by parameter type, and I keep thinking in Ruby terms ;)

**Comment by jhass** [comment]
Yes, just define another overload.
