### ISSUE TITLE
HTTP::Params with binary data bug

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#2161]
https://play.crystal-lang.org/#/r/sf9

**Comment by kostya** [comment]
in ruby
```ruby
{"key" => "\xFF\xE6\xEE\xEF\xE0"}.to_query
=> "key=%FF%E6%EE%EF%E0"
```

**Comment by jhass** [comment]
I think you should decode into a slice, not a string and we should let APIs like this accept slices.

**Comment by asterite** [comment]
I agree with @jhass here, and it's the same issue we need to solve in other places: String vs. Slice(UInt8).

In any case, I changed URI.escape to iterate bytes, which has the same effect (specs pass), doesn't crash on invalid chars, and as a bonus it's a bit faster, since chars don't need to be decoded :-)
