### ISSUE TITLE
Case restrictions

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2188]
I don't know if this has been mentioned before, but I really don't like the fact that constants have to start with a capital letter, and non-constants cannot. Is this strictly necessary?

**Comment by kirbyfan64** [comment]
I think it's necessary to dis-ambiguate the parser, so that.

**Comment by stugol** [comment]
?

**Comment by bcardiff** [comment]
* It makes harder to highlight some parts of the code in a semantic way without those conventions.
* It also complicates the compiler since an identifier `foo` won't be clear whether should bind the meaning. It can be done, as methods vs local variables. But it will slow the compiler putting everything in the same bag.
* If constants would be able to share the names of variables, then we would need another way to declare them.
* And regarding errors messages, upon an fresh identifier compiler won't know if it's meant to refer variable, method or constant. So the errors will be more generic, hence ugly.

Non of these are stoppers. Most languages have some conventions.
I don't see a real benefit of changing this. Is like trying to remove `@` from instance variables and using a variable resolution like C++, it can be done, but at least I like the current status.
 

I haven't try it but, did you check https://github.com/ozra/onyx-lang maybe you will find it more appealing, but is not intended to push you out, I am just sharing other work that is going around you might like.

**Comment by stugol** [comment]
Yes, I posted on that project some days ago asking if the project was dead. As no answer has been forthcoming, I conclude that it probably is.

**Comment by kirbyfan64** [comment]
@ozra might just have been busy or something...

**Comment by ozra** [comment]
@kirbyfan64 - you're right ;-) I've worked on it then and when meanwhile, I finally pushed an update today. Fairly usable now.

@stugol - Just saw your post now in onyx; answered there. You might get disappointed: the first-char-case-sensitivity is one of few things that _are_ common with Crystal syntax. You will like the call syntax for functors and lambdas (procs) though :). But post on the RFC's I'll be posting tomorrow to chime in on why etc. It might change.

**Comment by asterite** [comment]
I'm closing this. There isn't much to discuss here, because if you say "I don't like it" I can say "I like it" and then we'll be blocked. Propose an alternative syntax or semantic.

I personally think it's a nice convention. Otherwise you need something like `const var = 1`, but the good thing is that if you read `Voo` you know it's a constant (or a type, which is a constant) too.

**Comment by ozra** [comment]
On a sidenote @stugol: if you want a certain constant to be lowercase, you could always wrap it in a function. In release mode this is optimized to the constant it self (I've benchmarked it), so just as fast.
Onyx example (for comparison) would be:
```
CRUDE_PI = 3.14
crude-pi() -> CRUDE_PI

say "My lowercase 'constant': {crude-pi}"
```

**Comment by stugol** [comment]
It's not about wanting a "certain" constant to be lowercase; it's about wanting to use Title Case for function names. I detest camelCase with a passion; and my only other option is to intersperse_the_function_name_with_underscores. Even dashes would be an improvement, but that would of course necessitate moving to Onyx.

**Comment by ozra** [comment]
Ah, I see.

**Comment by DeltaRazero** [comment]
I hate to beat a dead horse, but I'd like to share my view on case restrictions, specifically regarding functions/methods.

I think that the case restriction for functions/methods is a bit of a troublesome area, at least for me and a great deal of people around me. While SCREAMING_SNAKE_CASE as naming convention for constants is pretty much a de facto standard (and thus starting with a capital letter), function/method naming conventions seem to vary not only per language, but also per developer.

I, myself, belong to the 'camp' of using PascalCase due to finding it much easier to distinguish methods and fields/properties/attributes (camelCase) than to solely rely on clever naming. But again, since this differs per person, I think it's hard to get establish a de facto standard.

Of course, this is easily a topic to ping-pong opinions, as asterite has already posted:
>There isn't much to discuss here, because if you say "I don't like it" I can say "I like it" and then we'll be blocked. Propose an alternative syntax or semantic.

So I'd like to propose an alternative semantic. I haven't delved too deep in Crystal yet, so if I make any wrong assumptions here, I'd like to apologize for that in advance. For now I'm trying to come up with alternatives given what I know about Crystal so far.

In contrast to constants, functions/methods (exclusively?) use the `def` keyword to define them. Then I suspect that's how the compiler makes distinction between attributes and methods? If this is a given, is the case restriction still necessary? If not, then I would think this could lead to removing the case restriction.
I could extend the above to classes (as they need the `class` keyword), but seeing how most people these days use PascalCase anyways, I think the urgency of that is almost _much_ smaller.

I'd like to hear what the opinions are on this.

**Comment by asterite** [comment]
Did you consider how to distinguish calling a method or using a type or a constant, in contrast to just defining them? I think you overlooked that.

**Comment by DeltaRazero** [comment]
Valid point. I had assumed the compiler could contextually determine symbol type with a shared symbol table during syntax and/or semantic analysis, which is clearly not the case then. That indeed complicates things to the point where such change isn't feasible.
