### ISSUE TITLE
Request: Add roadmap/milestones

### ISSUE THREAD

**Issue by marceloboeira** [manastech/crystal#2189]
I think it could be interesting in order to understand what are the short-term goals between crystal-lang releases, as also it would help people to focus their efforts on the highlighted goals.

What do you guys think?

**Comment by marceloboeira** [comment]
Found here: https://github.com/manastech/crystal/wiki/Roadmap

**Comment by asterite** [comment]
We do have a [Roadmap](https://github.com/manastech/crystal/wiki/Roadmap) (beat me to it!). However, knowing when and what we'll release in the next version is a lot more tricky.

Since this is mostly a spare-time project, we tend to do what we enjoy, although of course we deal with boring stuff from time to time, like dealing with nasty bugs or thinking how to handle stack overflows.

Right now what we have in our mind is:
* Make concurrency multithreaded (@waj is working on this, but it's super hard)
* Improve C bindings. We'd like more stuff to be autogenerated, and maybe an easy way to link C files into the project. Although our motto is "we don't want to write C code to make it faster", we do **need** C code to make it more portable (for example sigfault_handler is a mess of C macros).
* A [DB interface](https://github.com/manastech/crystal/pull/2182) so projects don't need to write adapters for each database.
* Fix [long-standing compiler bugs](https://github.com/manastech/crystal/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3Acompiler) (54 at the moment). I personally don't like bugs and want them to fix as soon as possible, but the old ones need a small redesign of the compiler's type system. I try to tackle these from time to time when I get some inspiration, but now I feel I have to sit down with @waj and think of a good design (generics are not well designed right now and so they have many bugs).
* Fix incoming bugs and review/accept incoming pull requests. These lately make the bulk of new features in a release.

**Comment by marceloboeira** [comment]
@asterite thanks for the enlightenments!

**Comment by ysbaddaden** [comment]
I wish I had more knowledge of low level stuff to add ARM and *BSD targets to the roadmap. I'd love to see Crystal running on more platforms!

**Comment by marceloboeira** [comment]
@ysbaddaden that would be really awesome.
