### ISSUE TITLE
Package / gem system?

### ISSUE THREAD

**Issue by farleyknight** [manastech/crystal#220]
Haven't worked on anything crystal in a while! Just wondering if you guys have any plans on doing a crystal package / gem system any time soon?

**Comment by weskinner** [comment]
+1 for the name "geode"

**Comment by r20** [comment]
Why "geode" ? I don't get it.

**Comment by weskinner** [comment]
Because they package a bunch of crystals together.

**Comment by bcardiff** [comment]
I thought it was because they have crystals inside :-). I like it.

There is also something called nodules that are geodes without the hollow cavity. 
And nodules and modules are ridiculous similar. Sadly as a medical term it is not so nice. But could work also.

**Comment by asterite** [comment]
@zamith suggested the name "shard", and he even built a [website](https://crystalshards.herokuapp.com/) ([in Crystal!!](https://github.com/zamith/crystalshards)) that lists GitHub projects that use Crystal.

I think I like it :smile: 

In this case shard would mean "a piece or fragment of a crystal", so the definition fits nicely with "a piece of functionality in crystal". It's also just one syllable, so it's faster to pronounce ("gem" has also one syllable).

Maybe "geode" would be something like rvm or rbenv, if a geode packages a bunch of crystals together (let's hope we never need a tool like that :wink:)

**Comment by kostya** [comment]
what about gem -> crem

**Comment by ysbaddaden** [comment]
I like `shard` too!

**Comment by jhass** [comment]
+1 to shard

**Comment by naps62** [comment]
@Exilor oh damn :( so close

**Comment by sardaukar** [comment]
+1 to shard

**Comment by Inkybro** [comment]
Hey, guys. Been a while since I piped up here.

So, I still love the idea of a decentralized approach for dependency management. But I have what I *think* may be a good idea, and eagerly await to hear what any one else thinks of them.

I was thinking it'd be very cool if we settled on some decentralized backend (e.g. GitHub). Users who want to distribute a "Crystal shard" (or whatever they will be called) can use some included binary, perhaps `shard push` or some command, to "push" their shard up. In reality, this binary and its associated commands would simply wrap git/git-core.

Alternatively, when a user wants to install a library, he or she could use something like `shard pull [git-address]`. Eventually, we could extend this to have some Shardfile syntax and what-have-you, and an entire package management system can be built around this architecture, which remains decentralized, yet still offers all the really important *functionality*.

So,

A. Is this a good idea?
B. Is this idea even really *new*, so to speak? In other words, is what I mentioned basically the *eventual* plan?
C. Surely this isn't so hard. I heard talk about some piece of current, internal code that handles some very basic dep management. Is this handled there? Where is that code, so I can check it out?

Those are my thoughts and questions as of today. Crystal seems to get cooler as each day passes. I really look forward to what it will have to offer.

**Comment by fdr** [comment]
Having worked on and seen the guts of some of the centralized dependency management systems (e.g. Ruby's): they're almost always a mess, no matter the size of the programming community, and never attract enough investment of effort to be good.  All of them wind up albatrosses.

Modulo lack of version pinning, "go" has the right idea here.  Even with some clear defects, the price is right.

**Comment by trans** [comment]
Just use git tags for releases. It's easy enough to write a tool that can pull down these tags. (I think I have part of one lying around my computer written in Ruby actually.) Since Crystal is compiled we really only need a tool to vendor the dependencies. I don't think there is a reason to "install" them in a central location (though that would be an easy enough option to add too if need be). For binaries, i.e. end user applications use distro package managers (e.g. .deb) as God intended.

**Comment by boghison** [comment]
I think that Crystal could use the exact same approach as Rust's manager: cargo. I've played with Rust and can honestly say Cargo is like a miracle. That means Crystal's dependency manager can have both centralized and decentralized dependencies. That means efficient version matching (a key point for new languages). That also means Toml, which was specifically created for this type of thing and, of course, a ton of additional features like build scripts for C/C++ dependencies etc.

**Comment by trans** [comment]
Please no Toml. It was not "created for this type of thing". It is actually pretty lame for this type of thing. It's just another superset of INI. I'd much rather see someone take the time to create a "RubyML". 

As for everything else about Cargo, I haven't used it, but it sounds good.

**Comment by boghison** [comment]
@trans Trust me, it's just perfect and it's very simple, so writing a parser won't be hard. It's also very easy to read :)

**Comment by kirbyfan64** [comment]
IMO, one of the best package managers I've seen is [Nimble](https://github.com/nim-lang/nimble) (I also like Felix's Scoop, which has a very similar model, but that one is unmaintained). Basically, it uses Git (and Mercurial) to manage versions with a big JSON file. To add a package, it's simply added to the JSON file. To update the local package list, the Git repo containing the JSON file is updated. Packages all have a Git/Mercurial URL. To get a specific version of a package, Nimble just checks out the tag corresponding to the version (e.g. it'd get the tag `v0.3` for version 0.3). The package list is on GitHub. Developers to hand-edit the JSON file and send a PR to the package repository.  This basically means that you get the benefits of centralized and distributed hosting.

A twist would be that the package list is not a file at all! Instead, the package repo has a directory named "packages". When someone submits a new package via the PR, they create a file in the "packages" folder, "<package name>.<some extension>". That way, instead of parsing a huge JSON file, the package manager would just use the directory structure!

To me, this is sufficiently simple for developers (just submit a PR to add your package and create tags for the versions) while still being simple for the maintainers (you basically just merge PRs!).

**Comment by jhass** [comment]
One long-term issue with that approach is the blockchain issue: It'll grow indefinitely and there's no (sane) way to reduce the size of it ever again. And I can only get the whole copy of the index.

**Comment by kirbyfan64** [comment]
@jhass What do you mean?

**Comment by jhass** [comment]
Git doesn't support partial checkouts and shallow clones are only useful since 1.9.

**Comment by kirbyfan64** [comment]
@jhass Don't lots of other package systems make you download the whole package list every time, too? Take Haskell's Cabal.

**Comment by kirbyfan64** [comment]
@jhass Actually, not every time. Just whenever you run `cabal update`.

**Comment by jhass** [comment]
Yes, though that doesn't mean it's a good thing, in fact it's what made for example Bundler so unbearably slow that they added a custom API to rubygems.org for it. And that was using a gzipped YAML representation of the index, not a whole git repository.

**Comment by kirbyfan64** [comment]
@jhass Oh.

Well, the rest of the idea would still work...

**Comment by asterite** [comment]
Nimble or Cargo could work fine, I think. We just didn't have time to implement this yet...

One thing I'd really like to have is recursive dependencies and dependencies checks, like bundler. Do Cargo or Nimble do this?

By the way, I think the current Projectfile, although nice, is not very handy for this type of things because it's a Crystal file so it has to be compiled. Imagine doing that for every dependency (well, shouldn't be that slow, but parsing JSON or TOML should be faster). And also, we already have a [TOML parser](https://github.com/manastech/crystal-toml), but I'm not sure I'd use it. I'd prefer JSON (even it's a bit more verbose). I don't think TOML can be mapped as easily to a data structure as JSON (i.e, like `json_mapping`).

**Comment by kirbyfan64** [comment]
@asterite What do you mean by dependency checks? I know Nimble downloads any needed dependencies.

**Comment by kirbyfan64** [comment]
Also, I can toy with writing a package manager over the week, but I'm not giving any guarantees...

**Comment by asterite** [comment]
@kirbyfan64 I mean [something like this](http://patshaughnessy.net/2011/9/24/how-does-bundler-bundle)

Of course, if anyone wants to slowly write a package manager we can later integrate it in the compiler if it's good enough. And right now almost anything is better than the current `crystal deps` :-)

One thing we do like is to have a project's dependencies in that project's directory, without a global directory where all dependencies go. That makes it easy to remove a project's dependencies when you delete a project (just delete the project's dir) and also to browse a project's dependencies source code (it's right in that directory).

**Comment by trans** [comment]
Why do I need to trust you? I know all about Toml. It's not at all perfect.
*Hipster* is what it is -- all the new kids are doing it. Blah. It's junk.

**Comment by bararchy** [comment]
I also do like TOML, its easy, its readable, and its hashes :)

Tough, I really don't care which parser ends up managing the packages TBH

**Comment by trans** [comment]
Ryan + Ary gave me an idea. What if a crystal project had a directory
in it, call it `dep` or `deps` (or whatever), and in this directory
you added a file for each dependency. e.g.

    dep/
        json.dep
        clik.dep

Then each file contains a single line with a git repo reference and a
tag or branch ref constraint. A command line tool can look at these
files and check each out right into the `dep` directory. It then
recursively checks the `dep` directory of each of those and does the
same.

There are two ways that recursive behavior can go down, and it depends
on what Crystal is capable of handling (or made to handle).

In the first case, if Crystal can only handle one version of a given
package, no exceptions, the tool has to look for version conflicts. It
might be able to do this by always checking out the repos to the top
level `dep` directory and checking out the most recent compatible
version (MRCV). If there is no possible MRCV, then of course a version
conflict error arises.

In the other case, perhaps Crystal can handle multiple versions of the
same package? If my package uses version 4 of some library, but
another dependency of mine use the same package but version 3, is
there any reason that they can't just use their own respective
versions and compile without conflict? (Of course it's a good idea for
the tool to tell me about the version difference, at least.)

One other thing this setup would allow: build and test dependencies,
or any other group for that matter could be in a subdirectory. e.g.

    dep/
      json.dep
      test/
        cryunit.dep

**Comment by ysbaddaden** [comment]
I started designing something this morning. Let's see where it goes.

- I chose YAML because JSON is too noisy and TOML's spec is unstable (sic). I apologise for trolling ;-)

- I'll clone bare repositories into `.shards` and install dependencies into the `libs` folder (ie. just like `crystal deps`), because we don't need a global packages folder and I never know where Bower, NPM and alikes put their global caches, and I hate that.

- I'm starting decentralised but with the long term goal of having metadata registries (name -> URL + versions + dependencies) to speed things up (no need to clone everything upfront), and simplify usage (I prefer to remember a package name, not a repository URL) and have a searchable list of packages.

**Comment by bararchy** [comment]
I would really like if the dir will be an external dir, like in gem, where for each "require" crystal can link the needed deps from the global directory, this way I dont need download all the deps each time for each project, and It's easier to keep all the deps up to date.

**Comment by trans** [comment]
On Wed, May 20, 2015 at 7:50 AM, Trans <transfire@gmail.com> wrote:
> Why do I need to trust you? I know all about Toml. It's not at all perfect.
> *Hipster* is what it is -- all the new kids are doing it. Blah. It's junk.
>

Okay. That's a bit harsh. Toml is *okay*. I just think it is
overrated, and espoused for the wrong reasons, i.e. new and simple
--- new and simple does not necessarily equate to better.

**Comment by trans** [comment]
If I were able to get this to compile to Crystal would it be helpful to you?

  https://github.com/rubyworks/versus

Note it has a version resolver.

**Comment by boghison** [comment]
@asterite Do you mean like if package a depends on b, and b on a, then throw an error? Yes, Cargo does that. Also, [here](https://github.com/servo/servo/blob/master/components/script/Cargo.toml)'s an example of Servo's (in case you didn't know, Servo is like Gecko written in Rust) Cargo.toml. It's very readable by humans. One thing I wouldn't like is Github being compulsory, because there's Bitbucket, GitLab etc.

**Comment by trans** [comment]
On Wed, May 20, 2015 at 8:24 AM, Trans <transfire@gmail.com> wrote:

> In the other case, perhaps Crystal can handle multiple versions of the
> same package? If my package uses version 4 of some library, but
> another dependency of mine use the same package but version 3, is
> there any reason that they can't just use their own respective
> versions and compile without conflict? (Of course it's a good idea for
> the tool to tell me about the version difference, at least.)

So can anyone tell me if this is possible (or can be made possible) or not?

**Comment by asterite** [comment]
@trans Dependencies aren't compiled to separate binaries that are later linked. When you compile your program, all of the dependencies are load up and from them and the main program an executable is created. If version 3 defines a method `foo` that returns 1 and version 4 defined a method `foo` that returns 2, one of them will win: they can't coexist.

**Comment by trans** [comment]
@asterite That's helpful. Thanks.

Theoretically, couldn't the two versions be "namespaced" so as not to be confused? So code using version 4 would call `v4::foo` and code using version 3 would call `v3::foo`.  I once developed such a system for Ruby. With the exception of global variables and core extensions it worked. In short, instead of `require 'foo'`, one used a more javascript styled `foo = require('foo', '>4')`, so a namespace automatically wrapped the library, which was then reachable via `foo` variable.

**Comment by bcardiff** [comment]
@trans In theory for a simple code it can be done, but as @asterite said, right now the compiler loads all the required sources and compiles it as a single unit. Class/method lookups are run over the whole code. 

If the lookups are changed in order to use some sort of scoped lookup based on project dependencies each shard would be able to use just the code it's advertised depends on. But then we need to see how to deal with blocks calls, inversion of control, delegation. Monkey patch will be left out (despite not being the something to encourage). Top level funs will definitely clash. I'm not sure if for something more than simple code that will end up working.

I don't see something like that coming. Yet, it seems an interesting problem.

**Comment by clord** [comment]
I know most languages have their own package management solution and so the temptation is there to invent yet another one from whole cloth, but I'd like to propose adopting a slightly modified version of [nix](https://nixos.org/nix/) as a way to distribute code and dependencies. And if not that, at least base a new crystal-specific manager on it.

Why?

Most language package managers end up needing other things too. I'm thinking of having a local imagemagick install, or libxml, etc. and everyone always ends up rolling their own solutions to having these installed, usually half-assed and buggy for a decade or more.

Using a real package manager as the foundation means you can easily port these sorts of dependencies without having to reinvent the wheel. 

The reason I suggest nix specifically is that it is really well thought out, and solves a lot of problems that a source-code package manager will also have to solve. Aforementioned binary dependencies is one. Also, it's really good at versioning. One project might depend on v3.1 of some library, whereas one of it's dependencies might depend on 2.0. Now the ideal way to deal with this is to allow both to have their own dependent versions used, without conflict. Nix makes that sort of stuff trivial. 

Because of the way nix works, it becomes really easy to 'switch' projects. With ruby, RVM and other tools try to solve this problem (badly, imo). nix inspired tooling would allow the whole stack to be specified declaratively at the project level. 

Also, because of the way nix lays out packages, it makes it really easy to build stuff. It puts literally everything into one tree (kind of like a mini chroot) and then builds it. So one need only set the appropriate `LOAD_PATH` environment variable and run the normal compiler without much cooperation from the package manager (the compiler could also be a dependency of the project btw) 

So my proposal then is to:

1. Either fork be inspired by nix (at the very least the idea of immutable self-contained packages)
2. Create a crystal-specific front-end to the nix store
3. use the resulting tool to manage source of dependencies
4. use it to publish end-user binaries and compiled libraries as well, ideally with an easy way to port from elsewhere.

This is really a big opportunity to leap-frog gems and RVM. At least *studying* the design of nix will certainly produce a much stronger package manager that will solve some of the worst problems with the other systems out there, and save some work in the process.

**Comment by rishavs** [comment]
coming from node and python, i personally prefer a centralized approach. I personally believe that npm was among the most important factors in node getting so big.

Also, if crystal does implements a package manager, i'd really want it to be part of crystal itself, rather than a separate project/product.

I'd love to use commands like `crystal install fast-json@1.2'

**Comment by vyp** [comment]
@rishavs You may be interested in https://github.com/manastech/crystal/wiki/Roadmap#package-manager if you haven't already seen it.

@clord I agree, but I don't see the reason for using a fork of nix, why not just nix itself? And besides, unless I'm misunderstanding something, `crystall install` is not supposed to *be a package manager*, but just more like a build helper, ala rust's `cargo install` command, so really you should be able to use whatever you want.

**Comment by clord** [comment]
@vyp the problems a 'build helper' solves and those that a 'package manager' solve overlap significantly, especially if crystal wants to have something resembling ruby gems.

**Comment by jhass** [comment]
Shall we close this in favour of #1357?

**Comment by asterite** [comment]
@jhass Good idea!
