### ISSUE TITLE
EOFError on MemoryIO with encoding

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#2205]
https://play.crystal-lang.org/#/r/sv4
It works if I don't set the encoding: https://play.crystal-lang.org/#/r/sv5

**Comment by asterite** [comment]
Mixing binary and text reads will cause that for the moment. It's said in the docs

**Comment by asterite** [comment]
@Exilor I'll expand a bit more about this.

Right now we are using [iconv](http://man7.org/linux/man-pages/man3/iconv.3.html) for encoding/decoding. The interface to it is:

```c
size_t iconv(iconv_t cd,
                    char **inbuf, size_t *inbytesleft,
                    char **outbuf, size_t *outbytesleft);
```

You give it input and output buffers, and it will read from the input as much as `inbytesleft` bytes and write to the output buffer.

The problem is, there is no way to tell it "decode a single char". If we wanted to do that, we'd have to invoke it multiple times, first with 1 in `inbytesleft`, then with 2, etc. Super slow. So for now we have an intermediate buffer of about 4K, read raw bytes from the IO and then decode them all with iconv, hoping that the user won't mix binary and text. If the user does, then the requested bytes might come after the already decoded ones (the intermediate buffer is only used when reading text if there's an encoding).

Another library we considered is [icu4c](http://icu-project.org/apiref/icu4c/), but it has its own complications too. `iconv` was the simplest to implement right now.

We thought a lot about what to do, and in what cases you'd want to mix binary and text. If there's a protocol, it usually says how many bytes come next if there's a string, so you always use binary (and if you need to decode you can read the bytes and then decode them). There's also the case of Java (and I believe in C# it's similar), where you wrap an InputStream with an [InputStreamReader](https://docs.oracle.com/javase/7/docs/api/java/io/InputStreamReader.html) to read text, but they recommend you to use a BufferedInputStream, but then it will read more then the request text (because it buffers), so then if you read from the underlying input stream you will face a similar issue than in Crystal.

The good news is that this can, and probably will, be improved in the future, if we implement the encoding/decoding ourselves. It's just that it would take too much time for us right now. Ruby does let you mix bytes and text and it works just fine.

**Comment by Exilor** [comment]
Thank you for the explanation. I'm porting Ruby code that I more or less ported from Java and the protocol is that the string is terminated with [0, 0]. The original code moves the bytes to another object before reading a string from it, so I suppose they faced a similar issue. I solved it the same way.

**Comment by ysbaddaden** [comment]
The PostgreSQL wire protocol behaves that way too: each frame has an overall payload length then strings are null byte terminated. For example the Startup Packet is `[Int32 len, Int32 protocol, String name, \0, String value, ... \0 ]`.

I'm not sure it will require any decoding, thought. Startup and ErrorResponse packets should only use ASCII chars, and Data Row Packets do specify a length for each value, so the current behavior shouldn't be a problem.

**Comment by Exilor** [comment]
@ysbaddaden In my case a packet containing 1234 (int16), "hello" and 1234567890 (int32) looks like this: ```[15, 0, 210, 4, 104, 101, 108, 108, 111, 0, 0, 210, 2, 150, 73]```. That's why I had to mix reading numbers and reading UTF-16LE strings.
