### ISSUE TITLE
:= inside if?

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#274]
Since in Crystal it's so common to assign to a variable inside an if to avoid the nil type, this idiom is common:

```crystal
if var = some_expression
  ...
end
```

For example:

```crystal
if value = hash["key"]?
end
```

When I read it I never mistake the `=` with an `==`, but maybe because I'm so used to writing that kind of code). For others that might not be the case ("did he mean `==` there?").

The alternatives are:

1. Allow using `:=` as an alternative to `=`, anywhere.
2. Allow using `:=` as an alternative to `=`, but only inside `if`, `unless`, `while` and `until` conditions.
3. Disallow `=` inside conditions and always require to write `:=` for assignment.
4. Leave things as they are now.

In all of these cases `:=` would just be the same as writing `=`. In **no case** it means "declare this variable and give a compile error if it's already declared".

I think I like number 3 the most.

What do others think about this?

**Comment by ozra** [comment]
I like the ideas brought up here, both by @asterite and also the widening of the issue by @ohjames.

The "assign in condition" pattern is common for me too, and I rarely make a mistake, however - it always takes an extra glance to verify - and especially in others code, before getting acquainted. So, I really do think, say `:=`, would be appropriate in that context.

But, then we come to the issue @ohjames brought up. It's not on the table for Crystal atm, but I do like the idea of being able to specifically declare variables, make them immutable, etc. Having another notation for updating/mutating a variable different from declare/initial assign would be a good middle ground, so it's worth considering before locking down symbol-combos for the parser.

In any event, I'd say both 2) and 3) are good with me.

**Comment by kostya** [comment]
why just not to check exist variable or not?
```ruby
a = 1
if a = 2 # compiler error
end
```

```ruby
if a = 1 # ok
end
```

**Comment by kirbyfan64** [comment]
@kostya I really like that idea...though it would need to be paired with good error messages for it to not be overly confusing for newcomers.

**Comment by kostya** [comment]
this can break some cases like:
```ruby
a = nil
while a = some_method
  ...
end
puts a
```

**Comment by technorama** [comment]
New language constructs such as `:=` should be used extremely sparingly.  They're hard for newcomers to understand especially when they have different meanings in other languages.

It also doesn't have much of a visual impact other than possibly being mistaken for `==` at a glance.

Requiring `()` around a conditional statement with assignment may not be a bad idea.  It provides quick visual recognition that something is different.

**Comment by ysbaddaden** [comment]
Adding a new operator for the sake of a visual difference sounds a little overkill.

The idiom is so common in Crystal code that I got used to it very quickly, and adapted it to my Ruby code, too.

**Comment by radarek** [comment]
@ysbaddaden 100% agree. Please, please, don't introduce another assignment operator, only to support this case.

My quick idea is this: if there is assignment in boolean expression then it has to be compared to something (with !=, == etc.) or method has to be called on it. Few examples:

```crystal
if x = get_foo # error, pure assignment
end

if (x = get_foo) != nil # ok
end

if (x = get_foo).nil? # ok, there is a method call
end

if foo && (x = get_foo) # error, pure assigment as a part of expression
end

if foo && (x = get_foo) == 1 # ok
end
```

**Comment by ysbaddaden** [comment]
Please, please don't introduce java-like syntax, thanks :smirk:

**Comment by ozra** [comment]
The "must add parentheses" doesn't help much imo, but @radarek 's idea is killer: Requiring explicit comparison/check.
- Makes it really obvious that an expression is an assignment
- Avoids another assignment op

However - what about issuing a _warning_ instead of _error_ unless the chosen "safety convention" is met? If someone reeeally don't wanna play with the "safety convention" a "ignore-this-and-that-warning"-pragma can be used in the source.

**Why do this - motivation**
For anyone saying "I never make a mistake about these, concerning '=' vs '=='" - fair enough - me neither, and I've been using that style for over 20 years. However - I also know that it requires constant extra reviews and double checks (albeit subconsciously), making your reasoning about code slower and more energy demanding. 
Remember: source code is write-once, read-many - so putting additional energy into the writing-part is a win.
_I'd like to see some visual safety in this - not because of frequency of mistakes, but the energy required to avoid them!_

**Comment by alanwillms** [comment]
If you don't like assignments in conditions, just assign before and don't use them. I don't see the point of all the work of creating a new assignment operator and confusing new users.

Oscar's warning idea is good. Some IDEs like Netbeans already do something similar, displaying a warning when you assign a variable in a condition.

**Comment by radarek** [comment]
After n-th compilation with warnings you will stop paying attention to it which is bad (there can be usefull warnings later). Warnings should be messages that tells you that something should be fixed (for example calling deprecated function). Using pragma/compiler option isn't good either. Remember that you will use code that is written by other programmers. Would you like to suppress warnings because someone wrote code and didn't pay attention to it?

**Comment by alanwillms** [comment]
You're right @radarek 
I'm not a core-developer anyway, but I vote for leaving things as they are.

**Comment by asterite** [comment]
I'll close this, it seems the current behaviour is good and it's even used now in Ruby by @ysbaddaden ! :-P (I admit I use it too to avoid double hash lookups, etc.)
