### ISSUE TITLE
Bug in right shift bitwise operator?

### ISSUE THREAD

**Issue by scidom** [manastech/crystal#305]
For ex, `100 >> 32` should return 0, but it returns 1.

**Comment by asterite** [comment]
We decided to solve it this way:

* We add `unsafe_shl` and `unsafe_shr` as Int methods that do what the current `>>` and `<<` do (thus the "unsafe" in their names.
* We add `>>` and `<<` with the rules seen in the commit above: use the opposite operation on negative numbers, return zero if shifting by an amount larger than the number of bits in the type, else invoke the unsafe variants.

The `>>` and `<<` methods are usually used with constants, and in those cases LLVM is pretty smart and will optimize that out. When the argument is not known at compile-time there's an 1.5x slowdown, but we prefer this slowdown to undefined behaviour.

Because primitives will be replaced with regular methods, it will take a couple of releases for this to be available.

**Comment by scidom** [comment]
Yes, this makes sense, it is better to avoid unsafe behaviour (if someone really wants to go for it, the unsafe version of the shift operators is provided anyhow according to the above).
