### ISSUE TITLE
!= bug

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#328]
```ruby
crystal eval 'p ((1 == 1) != (2 == 2))'
true

ruby -e 'p ((1 == 1) != (2 == 2))'
false
```

**Comment by asterite** [comment]
This one was a tricky one!

The bug had two causes:
1. The parser didn't return parenthezised expressions when there was only one expressions inside a parenthesis (so `(1)` is the same as `1`).
2. The chained comparison rule: if you have `1 == a == 2`, or a mix of comparison operators, it is later transformed to `(1 == (temp = a)) && (temp == 2)`. This is useful to do `1 <= a <= 10`.

Combining these, this:

```crystal
(1 == 1) != (2 == 2)
```

was seen by crystal as this:

```crystal
1 == 1 != 2 == 2
```

which is later transformed to this:

```crystal
1 == (temp = 1) && (temp != (temp2 = 2)) && (temp2 == 2)
```

Then we have:

```crystal
1 == (temp = 1) #=> true
temp != (temp2 = 2) #=> true (1 != 2)
temp2 == 2 #=> true
```

The `&&` of all of the above is true.

I fixed this by not discarding parenthesized expressions with a single ast node, so then chained comparison rule can't be applied. It works and all specs pass, but maybe later we'll have to think of a different solution.

(I wanted to explain all of this because it was really misterious!)
