### ISSUE TITLE
Regex literal with just a space does not parse

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#337]
```
Syntax error in /home/jhass/tmp.cr:5: unterminated call

"foo bar".split(/ /)
```

**Comment by zamith** [comment]
From what I could understand the bug is due to [this line](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/lexer.cr#L238).

Basically the lexer thinks a `/` followed by a whitespace is a `:/` token and does not create a regex delimiter.

I don't really know how to fix it though. The lexer and parser are two beasts I'm yet to tame, but I thought this could be of some help to someone trying to fix this bug.

**Comment by jhass** [comment]
It's a hard bug, I know. Sorry:

```ruby
begin
  / /
end
````

**Comment by asterite** [comment]
@jhass Keep them coming :-) I guess we'll find more along the way, but at one point we'll solve them all. I even had a test for "begin; / /; end" but forgot to test it with newlines as well.
