### ISSUE TITLE
Crystal always produces ELF 64-bit object files

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#349]
So I went on a quest to cross-compile Crystal for one of my 32 bit VMs.

After trying a ton of variations of passing `--cross-compile`, `--target`, `--mcpu` and in my desperation even `--link-flags -m32` to `crystal build`, I still ended up with
```
$ file crystal32.o
crystal32.o: ELF 64-bit LSB relocatable, x86-64, version 1 (GNU/Linux), not stripped
```

Which obviously fails to link with the 32bit variants of the needed libraries, which in fact a 32bit ld no even recognizes.

I tried digging a bit into the the compiler, but the target triple seems correctly passed, the 32bit data format seems used, everything looks okay there. Eventually I added support for combining `--ll` and `--cross-compile`:
```diff
diff --git a/src/compiler/crystal/compiler.cr b/src/compiler/crystal/compiler.cr
index 3c526ef..a36616d 100644
--- a/src/compiler/crystal/compiler.cr
+++ b/src/compiler/crystal/compiler.cr
@@ -149,6 +149,11 @@ module Crystal
         llvm_mod.data_layout = DataLayout32
       end
 
+
+      if dump_ll?
+        llvm_mod.print_to_file o_name.gsub(/\.o/, ".ll")
+      end
+
       if @release
         optimize llvm_mod
       end
```

I got a 32bit chroot, installed llvm and the other dependencies, copied the generated `.ll` into it and fired up `llc -march=x86` and fed the result into `clang` with the linker flags needed. And that actually worked! I have a 32bit crystal binary now!

Okay, time to reiterate, let's push that binary to a VM actually running a 32bit kernel and use it to compile Crystal there, `git clone ...`, `cd crystal` and (includes some debug output I didn't include in the diff above):
```
$ CRYSTAL_PATH="src" ../crystal32-0.5.8_dev build -o .build/crystal src/compiler/crystal.cr
cross_compile_flags = nil
program.flags = Set{"linux", "i686", "release"}
.crystal//home/jhass/crystal/src/ecr/process.cr/main.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o /tmp/crystal-run.QcjZUr .crystal//home/jhass/crystal/src/ecr/process.cr/main.o   -lpcre -lgc -lpthread -lunwind`
$ file .crystal/home/jhass/crystal/src/ecr/process.cr/main.o
.crystal/home/jhass/crystal/src/ecr/process.cr/main.o: ELF 64-bit LSB relocatable, x86-64, version 1 (GNU/Linux), not stripped
$ uname -asm
Linux aeshna.de 3.14.29-1-lts #1 SMP Fri Jan 16 21:14:23 CET 2015 i686 GNU/Linux
```

![](http://i1.kym-cdn.com/photos/images/original/000/173/576/Wat8.jpg)

**Comment by asterite** [comment]
Nice detective work! Yes, that's a big "wat" on my side too. I was almost sure that Crystal produces 64 bit object files, but now I know it for sure. We used to have cross-compile use .ll files until we managed to produce .o files using LLVM's APIs (so we don't need their executables, like llc), and in that moment I did a small test and I couldn't cross compile to 32 bits anymore (we didn't support 32 bits anyway because of some other bugs).

But... I didn't know it also produced 64 bit object files in a 32 bits machine! That's... unexpected.

I'll check (during this week) where could that setting be in LLVM's API and report back. 32 bits support is very important. And Windows too, but that's a bit harder.
