### ISSUE TITLE
constant OpenSSL::BIO::CRYSTAL_BIO requires initialization of EventScheduler::INSTANCE, which is initialized later.

### ISSUE THREAD

**Issue by brasten** [manastech/crystal#377]
When I try to use HTTP::Client after having requiring "evented_io", I get this compile error.

```
Error in /<...>/crystal/src/openssl/bio.cr:17: instantiating 'TCPSocket#read(Slice(UInt8))'

      io.read(Slice.new(buffer, len)).to_i
         ^~~~

in /<...>/crystal/src/io.cr:58: instantiating 'read(Slice(UInt8), Int32)'

    read slice, slice.length
    ^~~~

in /<...>/crystal/src/openssl/bio.cr:5: constant OpenSSL::BIO::CRYSTAL_BIO requires initialization of EventScheduler::INSTANCE, which is initialized later. Initialize EventScheduler::INSTANCE before OpenSSL::BIO::CRYSTAL_BIO
```

Minimum code required to duplicate:

```ruby
require "evented_io"
require "http/client"

client = HTTP::Client.new("0.0.0.0", 9080)
client.get("/")
```

**Comment by asterite** [comment]
Hmm... it's been a while since we last used that.

To be honest, "evented_io" was just an experiment to see how we could implement it. But right now we are more inclined to use libuv rather than libevent. @waj is currently making the bindings and doing the necessary wrappers.

Then the idea would be that you would compile a program in evented mode (maybe a combination of a compile-time flag and `ifdef` will be enough) or non-evented mode. We will try to make the evented and non-evented APIs be compatible, so you could theoretically switch between the modes, but the real reason is that you can program as if you were doing things linearly, similar to Ruby's EventMachine, I guess Python's twisted or node.js. As @waj says, "if that concurrency model works for node.js, it could work for us". Of course, we might try different concurrency models in the future, but for a start this will be good enough.

So... I could fix the error related to "evented_io", but it will soon be gone for sure, so...

I will still debug that error, maybe there's something to improve there related to constants.

**Comment by brasten** [comment]
If it's going away then don't worry about it. I was just seeing if it worked. :-)

**Comment by asterite** [comment]
It's gone, so I'm closing this.
