### ISSUE TITLE
No 32-bit builds and unclear documentation of architecture or OS support complicates installation for new users

### ISSUE THREAD

**Issue by Marand-** [manastech/crystal#402]
A combination of limited documentation, no listing of platform support, and only providing amd64 builds makes getting and using Crystal a bit of a mess, especially if trying to use it on a 32bit system.  First, a list of the problems:

* The download link on http://crystal-lang.org is useless unless you already have Crystal installed.  For a new user, this is likely the first place someone will go to start using Crystal, and it is just a useless, wasted step, because the bin/crystal is a shell script that relies on .build/crystal (doesn't exist) or a system-wide crystal (also won't exist for a new user)
This link should either go to install&download instructions, or it should provide links to a working Crystal binary for at least one platform.  

* Next stop will be the Readme.md for the github repository, which has a link to http://crystal-lang.org/docs/installation/README.html .  This is a good start, but has its own problems:
  1. the Ubuntu/Debian repo only has an amd64 build, and that is not documented.
  1. The "from a tar.gz" page points you to the releases page, but again doesn't mention that only amd64 downloads are provided.
  1.  No list of required library dependencies anywhere.  Which means even after you get a working Crystal binary, you get to try running it and then figuring out which packages you're missing

If you're using OS X or a 64-bit Linux you're done at this point.

However, if (like me) you want a 32-bit build, there's almost no information on how to make it happen successfully.  I had to use a combination of the info from the "Cross-compilation" doc page and some chat logs that showed up in Google searches, and even then I still had to look in the Makefile to figure out the rest.  

If you don't want to provide builds for non-amd64 systems, that's fine, but architecture/OS support should be more clearly documented on the site and there should be a sub-page of the "Installation" page that documents how a new user can build a working 32-bit Crystal of their own.  

Ideally, the Makefile could contain a make target so you could just do something like "make crystal32" on an amd64 system to get started, but even just some basic documentation on how to bootstrap a 32bit build in its own page would help.

If I weren't ridiculously stubborn, I would have just given up and never given Crystal a chance, and it's likely others aren't going to be as determined to make it work.  That's a shame, because it's a nice bit of work and deserves widespread adoption. 

---

For reference, this is what I ended up having to do to get the 32bit build started:
1.  Install 64bit Crystal from the Debian repo on an amd64 system
2.  Clone the git repo and build a newer 64bit Crystal.  (The repo version at the time would only build 64bit versions)
3.  Build 32bit crystal.o with **env CRYSTAL_CONFIG_PATH=`pwd`/src crystal build --cross-compile "Linux i686" --mcpu i686 --target "i686-pc-linux-gnu" -o crystal src/compiler/crystal.cr**
4.  Move file to the x86 system and attempt to build with the command provided (Kudos for providing the build command for the target system, it was helpful)
5.  Install whatever missing dependency it errored on and then repeat step 4. 

Easy enough, once I figured out that I needed to do it and how to do it, but I wasted a lot of time on this.  I started with the Debian repo, which didn't work, and then I downloaded the .tar.gz off the main page, and it didn't even have a working binary, and then the releases page only had 64bit executables.  Then when I decided to bootstrap it from my laptop, I still had to figure out the library dependencies that weren't listed, and then to actually figure out how to build it I had to resort to searching chat logs found on Google to clarify parts of the cross-compile documentation page. 

---

Sorry for the length of this, and thanks for the work on an awesome language.

**Comment by waj** [comment]
You're absolutely right and I agree on each and every point. Thank you for taking your time describing the issues and how you managed to solve it. When the people likes a project is really common to receive positive feedback, but negative points are equally (or event more) useful and it remind us how much the work we are doing is being accepted. That's making us really proud lately :-)

As the language grows and the adoption is higher, it also become less obvious how to keep everything up to date. The time we have after working in other projects to pay bills and beers is limited. Fortunately  the project started to receive contributions and the help is trending up.

We used to have compiled binaries for Linux 32 bit. At some point the build was broken and we decided to temporarily give up with that effort. Please, if you had to make changes in the source code to make it work, send a pull request so we can include your effort into the project.

I'll keep this issue open until we fix all the points you describe, including the ones for the documentation and the website.

Thanks!

**Comment by Marand-** [comment]
It's also worth noting that the documentation you already have, while incomplete, was still very helpful, and I wouldn't have been able to get it compiled without it, so I appreciate the effort that's been put into it.  In a lot of ways, it's already more useful than Mirah's documentation, and I've seen languages older than either with much less useful information.  

The pieces are in place for it to be clear and useful, just needs some minor cleanup, and some sort of list of classes and their methods at the end similar to Ruby's pickaxe book or Java's API reference.  It's easy enough to figure it out by poking around in the source for now, though.  



---
No source changes were needed; once I figured out the cross-compile flags I needed,  all I had to do was "make -n crystal" to see what make was running and then repeat it with the extra flags on the end.  It compiled without issue on the amd64 machine, and the "cc crystal.o etc etc etc" line it gave also compiled fine on the x86 machine once I figured out which package I needed for the garbage collector lib.

There might be something subtly broken somewhere with the 32bit version, but so far it's been working fine and I've used the bootstrap binary to build new versions without trouble.

I don't know if it would be useful to anyone, since it may not be done in a preferred way, but I did modify the Makefile to allow cross-compiling by specifying arch=X, for example **make crystal arch=i686** adds the cross-compile flags I listed in the initial comment.  I'm a Makefile newbie so it's just an ifeq that sets some extra flags, but it works and extra conditions could be added for other architectures.  Preferably by someone that actually knows what arguments those platforms need for --target, --mcpu, and --cross-compile.

I don't know if that would be useful to anyone, but if you're interested in it, let me know and I'll try to figure out how to send a pull request; I'm clueless about it because I've only used github for bug reporting, and I usually only clone repos or manage local ones with git.

**Comment by jhass** [comment]
32bit is only working again since the last release, mainly because I wanted to run Crystal on a server I have, so asterite and I digged into it. That's why there are no official builds (yet). Nonetheless I patched up the Archlinux packages with 32bit support and in order to do that, until there are official packages, will provide 32bit binaries that are dynamically linked against an Archlinux environment at `http://cloud.aeshna.de/u/mrzyx/crystal32/crystal32-$version.tar.gz`.

You can find some preliminary API docs at http://crystal-lang.org/api/

I can also recommend you to drop into the IRC channel with your questions, even if you're not sure you've gone the complete way yet but are just stuck for a moment. This is true in general for young projects, if they have an IRC channel hang out there for a day or two, you have good chances to find somebody who's already a bit more experienced with the project and can answer you such question as "is there 32bit support?" ;)

**Comment by asterite** [comment]
I just removed the "download" icon and link from the [homepage](http://crystal-lang.org/).

I think the website should be redesigned to something similar to the [Rust homepage](http://www.rust-lang.org/). You have lots of useful links right there, a small code sample, a list of features, and a big "Install" button. The current website is nice and fancy but not that useful in that sense.

However, as @waj says, our spare time is limited and the pending task list is huge: there's the language itself, it's evolution and bug fixes; the standard library; the documentation of the standard library; the documentation of the language; the website design; the website blog; reviewing issues and pull requests; answering questions on irc; and also toying with the language whenever we have time, to make sure it pleases us and works well :-)

@Marand- As for the 32 bits thing, as @jhass said, we fixed 32 bits support very recently. However on my Ubuntu VM it wasn't working well. Mainly, `Dir.list` didn't work well (not even in Ubuntu 64 bits). It turned out we were using C's `dirent`'s `d_type` attribute, which is not portable and is not guaranteed to work. So I just [rewrote that](https://github.com/manastech/crystal/commit/f9c2149e068efb41825f12adf8274aca309bcb68) and now I have the specs passing, and I also compiled a compiler in that VM and with that compiler the specs also pass. So you can expect 32 bits releases for debian-like and centos-like linuxes too, starting from the next release, once we add that to our [build app](https://github.com/manastech/omnibus-crystal).

We know we lack lots of documentation. The website's source and its documentation is open source too, and it's on the [gh-pages branch](https://github.com/manastech/crystal/tree/gh-pages) of this repository. Any improvement, in the form of a pull request or just an issue saying "rewrite this paragraph to xxx" will be very accepted.

**Comment by asterite** [comment]
@Marand- There's version 0.6.0 now, but still now 32 bits releases. We will do that soon, but right now it was kind of hard to do because this particular release involved a two-step release because of core, breaking changes. Sorry!

**Comment by Marand-** [comment]
No need to apologise; I'm having no problems updating the repo and compiling it myself, so it doesn't bother me at all. :)  Interesting that 32bit support just recently improved enough to be usable, though.  I found Crystal at a good time, apparently.

I know I should make the switch to 64bit on this system, but I'm still using 32bit+PAE because this system doesn't have enough RAM to justify the effort.  Planning on switching over during a hardware upgrade.

Also, I didn't know you could do pull requests to get the documentation updated, that's cool.

**Comment by asterite** [comment]
Starting from 0.7.5 we now provide 32 bits releases, so I'll close this :-)
