### ISSUE TITLE
Crystal can't build master from d4e17eb or earlier, must checkout and build 4985484 first.

### ISSUE THREAD

**Issue by Marand-** [manastech/crystal#421]
The change in commit 4985484 created a choke-point of sorts when building from git.  An older version of Crystal has to `git checkout 4985484` and build that before attempting to build a newer version.  If you're using a build from commit d4e17eb or earlier, attempting to build a commit after 4985484 results in the following error:

```
> make crystal
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build   -o .build/crystal src/compiler/crystal.cr
Error while requiring "prelude"

in ./src/prelude.cr:27: while requiring "string"

require "string"
^

Syntax error in ./src/string.cr:545: unexpected token: =

    $~ = match
       ^

Makefile:27: recipe for target '.build/crystal' failed
make: *** [.build/crystal] Error 1
```

The fix, as alluded to above, is to `git checkout 4985484; make crystal` and then use that binary to build the newest with `git checkout master; make crystal`, or alternately to get a newer pre-compiled version from the release page and use it to build master.

This isn't likely to be something that needs to be fixed, since it's a very specific problem that should be self-correcting over time.  I'm just posting it to document the issue in case someone runs into the same problem and searches for it.

**Comment by jhass** [comment]
Isn't that what the whole point of 0.5.10 was? To build 0.6 you checkout 0.5.10, build it and then build 0.6 with the 0.5.10 compiler.

**Comment by Marand-** [comment]
Probably, but it was unexpected when it happened.  I went a few days between building new versions, did a pull, and suddenly the compiler's spewing errors trying to build.  

I don't think there's anything to fix here, but I did think it might be a good idea to report it in case anybody else hit the same thing and came looking for information.

**Comment by asterite** [comment]
@Marand- Indeed. Maybe the next time it happens we can use a better wording in the Changelog, including a link to a FAQ or something describing what to do in these cases?

But... we don't expect those choke-points to happen often. In fact, that's why the commit does a lot of things, dealing with magic variables, the struct/class distinction and Proc/Function rename. If they were single commits you'd have to create a separate version for each of these before compiling the next one.

In any case, we will soon add 32 bits binaries available for download so that you won't have to do that manually.

**Comment by asterite** [comment]
I'll close this, this is expected behaviour/workflow.
