### ISSUE TITLE
[RFC] Evented IO mode as the only mode

### ISSUE THREAD

**Issue by waj** [manastech/crystal#430]
We're working on an IO backend on top of the great libuv library (the one that powers nodejs). The current results are very promising and it's already possible to compile a HTTP server for example, capable of answering multiple calls at the same time.

The implementation makes heavy use of fibers to give control back and from the libuv event loop. New lightweight processes can be started with `spawn` and every time an async IO operation is started the fiber yields the control back to the loop. The event callbacks are set by the implementations so the feeling is very much like multithreaded programming.

In order to make use of this new implementation a flag "evented" must be passed to the compiler. The std classes are being populated with tons of "ifdef evented" to switch the implementation.

At the beginning we thought that maintaining both implementations could be worth to someone looking for a language that is able to make quick synchronous IO on a single thread/fiber, but so far I cannot think on any real use case of this, besides having awesome numbers on some benchmarks.

The startup overhead is really small (currently the main thread hast to be running inside a fiber, so at least one must be created and there is also the libuv initialization and loop running) and if no IO is performed by the application there shouldn't be major differences.

So, the question is... is it really worth the effort of maintaining both implementations, or should we focus on having a single one well tested and stable? Does someone see any scenario where synchronous IO makes a real difference in performance? And besides performance, is there any other reason to use sync IO?

**Comment by weskinner** [comment]
I believe switching to async only is a wise decision.  This would give rubyist a familiar language to migrate to with the promise of node like concurrency.  Which, if your willing to make the trade offs for the performance of crystal, would probably be a big selling point.  I can see that playing a major role in language adoption.

**Comment by ysbaddaden** [comment]
A fully concurrent language is the way to go. But an evented concurrency with libuv that must run on a single thread... is no fun at all.

If crystal multithreads fibers, then it would be incredible and, yes, please make -Devented the only concurrency.

I know libpcl supports multi threading, which is great, but apparently libuv isn't thread safe, and all uv functions must be called from one, unique, thread.

**Comment by akaufmann** [comment]
> ... should we focus on having a single one well tested and stable?

This is a big plus, especially if there is not enough resources to maintain different I/O models.
Because of the limited resources, good features (TLS, gzip compression, static file handling, ...) would be implemented faster as well.

Some libraries show that evented I/O works very well (Node.js, Ngnix, ...). You can handle virtually unlimited amount of I/O concurrency. Slow clients will not to be a problem, thereby eliminating the need for a buffering reverse proxy. Of course its a little bit harder to implement a good evented model compare to a blocking I/O model. 

I would say "yes" for evented I/O "only" mode. Maybe a sync version is provided as a library?!

**Comment by waj** [comment]
@weskinner That's the idea. Crystal is really fast already, but adding native support for concurrency would make it suitable to make scalable systems.

@ysbaddaden I thought we could start with a single thread and move later to a multi worker thread model. In Go the network poller loop is run on a single thread. I wonder how they manage to register new network file descriptors asynchronously into the loop.

Maybe we should reconsider if libuv is the best choice before moving any forward. Maybe libevent has a better design for multithread environments although I read some benchmarks in which libevent is much slower that libuv. Or... maybe forget about any framework and get our hands dirty with epoll/kqueue directly.

@akaufmann The idea is the apis remain synchronous. Even when the runtime would be making async calls and running evented IO underneath.

**Comment by akaufmann** [comment]
I see. But whats the point to use libuv async functions underneath if my fs operations are sync?
If I have `File.read` it will block (your event loop runs empty, because no other event was registered after the fs_read) until a result is returned. Is it my job to call `spawn` on sync functions to get an async behavior? 

Btw, I think Go used a lock to allows runtime poll updates to be called synchronously from the loop thread.

**Comment by waj** [comment]
Yes, you basically have to use `spawn` to get real concurrency. That's pretty much how Go works, using the `go` keyword to start new "goroutines". When the `File.read` blocks (the current fiber) the scheduler would give control to another job, or just wait for the result if there isn't anything else to do.

**Comment by brasten** [comment]
I generally support the idea of this being the primary or only mode going forward. I think if this concept gets implemented right, Crystal potentially wins the next decade. (no pressure, huh?)

A thought:

This is about 90% messaging and 10% technical, but we might want to consider overhauling the concept of a Fiber. As they exist in Ruby, they're essentially useless as a high-level concurrency construct. Instead, Fiber could move away from being a co-routine and move toward being a true light-weight thread like Erlang's "process" or (increasingly) Go's goroutine. Threads without the overhead of POSIX threads and schedule themselves around I/O and/or other events (channels? timeouts? course-grained pre-emption?)

Essentially that means dropping the `yield`, `resume` etc methods so that scheduling is handled entirely in the runtime.

**Comment by ysbaddaden** [comment]
The whole concurrency thing is so complicated. I long for Erlang-like processes (actors) too, and I would love that concurrency/parallelism would be just like that (or something along those lines):

```crystal
process = spawn do
  receive do |message, caller|
    puts message  # message
    caller.send "got it"
  end
end

process.send "message"

receive do |message|
  puts message # got it
end
```

That being said, about the current RFC, if making the evented IO (libuv) the only concurrency (for now) means that I can still do IO within different threads without segfaults [like this](https://github.com/ysbaddaden/prax.cr/blob/master/src/prax/server.cr#L35-L40), then I'm fine with it :+1:

**Comment by waj** [comment]
@brasten Many thanks for your words! Let's try to do our best.
Probably as the design evolves there's going to be a separate entity for coroutines, but I still think fibers could be useful in some cases.

@ysbaddaden We're thinking something more like Go channels instead of just a process inbox, but that's the idea. You can already try to use the HTTP server with libuv if you compile with `-D evented` flag. It's not multithreaded but it works pretty well so far.

**Comment by asterite** [comment]
If you get a segfault remember to wrap your main code in a `spawn`. This will be done automatically later, but for now you have to do it manually.

**Comment by asterite** [comment]
@ysbaddaden Why are you getting a segfault there? Isn't it because the "socket" variable is always the same so every thread you create will refer to that same variable?

**Comment by ysbaddaden** [comment]
@asterite I didn't meant that it segfaulted, but that I should still be able to do IO in many threads without libuv segfaulting on me —until Crystal goes for a great de-facto concurrency/parallelism scheme.

I just tried, but Prax won't compile with -Devented right now: `crystal/src/io.cr:82: undefined method 'fd' for TCPServer`.

**Comment by waj** [comment]
Some progress on this... I changed my mind and it doesn't use libuv anymore. Instead libevent2 is used that should have better support for threads in the future. The implementation it's less intrusive and easier to replace with something else (libev? direct calls to epoll/kevent/etc...)

I started a new branch (evented) where this is the default and only implementation of IO in Crystal. It works pretty well and all the specs are passing (there isn't many IO specs anyway but at least the compiler can still build itself).

I have a problem I couldn't figure out yet with the TCPServer. After some successfully attended requests, the "accept" fails and errno == EINVAL. Do someone have any idea of what's going on there?

**Comment by waj** [comment]
Ok... I figured out the problem. There was a bug with the fibers and GC.

**Comment by ysbaddaden** [comment]
That sounds very good! I read about the different solutions, and I think libevent or libev will require more work to integrate, but should prove far more flexible than libuv, which should fit better to Crystal (I hope).

I'll try to find some time to play with the branch and to discuss/propose enhancements :-)

About libevent/libev the former has some weird naming, but I don't know about libev and thread safety.

**Comment by asterite** [comment]
We will push this idea forward :-)
