### ISSUE TITLE
Function literal signature lost when passing around

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#447]
Okay the title is suboptimal, but meh.

Setup:

```ruby
lib LibFake
  alias Faker = Void* -> Void
  fun fake(faker : Faker)
end

module Fakes
  def self.main_fake data
  end
end

def fake faker
  LibFake.fake faker
end

def strict_fake faker : LibFake::Faker
  LibFake.fake faker
end
```

```ruby
fake ->Fakes.main_fake
```

gives 
```
Error in ./tmp.cr:20: wrong number of arguments for 'Fakes:Class#main_fake' (0 for 1)

fake ->Fakes.main_fake
     ^
```

```ruby
strict_fake ->Fakes.main_fake
```

still gives

```
Error in ./tmp.cr:20: wrong number of arguments for 'Fakes:Class#main_fake' (0 for 1)

strict_fake ->Fakes.main_fake
```

When the type is specified in the wrapper, it should also work when overloads for `Fakes.main_fake` exist.

**Comment by asterite** [comment]
Marked as enhancement, but this works "as expected". We find matching defs based on the type of the arguments, except when it's about C functions (because they can't be overloaded and you must specify their types, so we can infer argument types there).

I'll leave it open in case we do find a way to improve this.

**Comment by asterite** [comment]
I'll close. We find matching defs from the argument types, so there really isn't a way to do it the other way around.
