### ISSUE TITLE
Compiler confused about variable's scope inside macros

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#466]
From the compiler's message I can't tell if that variable *should* be available outside the macro or not. The message is wrong in either case though.
```ruby
macro for(*exp)
  {% exp_str = exp.stringify[1..-1] %}
  {% first_line = exp_str.lines[0] %}
  {% block_vars = first_line.split('(')[0] %}
  {% lines = exp_str.lines.select { |l| l != "end)]" && l != "end))]" }.length %}
  {% enumerable = first_line.split("in")[1].split(" do")[0] %}
  {% open_parens = enumerable.split("").select { |e| e == "(" }.length %}
  {% close_parens = enumerable.split("").select { |e| e == ")" }.length %}
  {% if open_parens != close_parens %}
    {% enumerable = enumerable[1 .. -1] %}
  {% end %}
  __enumerable_object = {{enumerable.id}}
  __enumerable_object.each do |{{block_vars.id}}|
  {% for line in 1 ... lines %}
    {{exp_str.lines[line].id}}
  {% end %}
  end
  __enumerable_object
end
```
```ruby
for x in Set {1, 2, 2, 3} do
  print x
end 

__enumerable_object # undefined local variable or method '__enumerable_object' (did you mean '__enumerable_object'?)
```
So this is either a scope issue or an error message issue.

**Comment by asterite** [comment]
Variables defined by a macro shouldn't be visible outside it. But yes, it's a bug because of the error message. I'll fix this.

By the way:
1. I wouldn't really add `for` to the language, but maybe it's a good exercise to try to do it :-)
2. Instead of manipulating strings I would manipulate the given AST.

Start with this:

```crystal
macro for(exp)
  {{ puts exp }}
end

for x in Set {1, 2, 2, 3} do
  puts x
end
```

This will print (at compile time):

```crystal
x(in(Set {1, 2, 2, 3}) do
  puts(x)
end)
```

I'm not sure why the `do` is attached to the `in` call, I would have thought it would attach to `for`. Maybe it's a bug?

In any case, here `exp` is a call, so you can ask, for example, for its name, arguments, block, etc., in the macro:

```crystal
macro for(exp)
  {{ puts exp }}
  {{ puts exp.name }}
  {{ puts exp.args }}
  {{ puts exp.args[0].block }}
  {{ puts exp.args[0].block.body }}
end

for x in Set {1, 2, 2, 3} do
  puts x
end
```

This will print:

```crystal
x(in(Set {1, 2, 2, 3}) do
  puts(x)
end)
x
[in(Set {1, 2, 2, 3}) do
  puts(x)
end]
do
  puts(x)
end
puts(x)
```

With this it should be much easier to implement what you want, without even needing a variable for the enumerable.

It's always much easier to manipulate an AST than to convert it to a string and manipulating strings :-)

**Comment by Exilor** [comment]
1. Don't worry, not everything I do will later pop up as a pull request! Like BigInt#bytes from my previous issue for example.
2. Cool! Although using ```exp.args``` doesn't work when the macro accepts a variable number of arguments:
```ruby
macro for(*exp)
  {{ puts exp.args }}
end

for k, v in ({name: "Jacob", age: 25, foo: :bar}) do
  p "#{k}: #{v}"
end
# undefined macro method ArrayLiteral#args
```
which my version does:
```ruby
for k, v in ({name: "Jacob", age: 25, foo: :bar}) do
  p "#{k}: #{v}"
end
# "name: Jacob"
# "age: 25"
# "foo: bar"
```
You might want to update the documentation about macro methods. Such a powerful feature deserves more love!

**Comment by asterite** [comment]
If you are using a splat, `exp` will be an ArrayLiteral containing all those nodes. This works:

```crystal
macro for(*exp)
  {{ puts exp[0] }}
  {{ puts exp[1] }}
end

for k, v in ({name: "Jacob", age: 25, foo: :bar}) do
  p "#{k}: #{v}"
end
```

So you could check the length of exp.

**Comment by asterite** [comment]
And yes, we need to document these things. But there's so much to do and it takes so much time...!

**Comment by jhass** [comment]
> And yes, we need to document these things. But there's so much to do and it takes so much time...!

Do the `CONTRIBUTING.md` and explain how to do doc patches ;)

**Comment by asterite** [comment]
@jhass I'll do it. In fact, I started many times but I can't do it because I'm not sure what's the scope of that file should be. Could you make a list of points that would go there? Like, should I explain what to use the issue tracker for? How to install the compiler and bootstrap it? How to document code? What's still missing in terms of functionality and documentation?

Because I don't know the scope, everytime I start writing it I feel like it's going to be huge and then give up and do other smaller tasks :-/

**Comment by jhass** [comment]
I usually look at other popular projects in these cases, but don't include too much and more importantly don't duplicate stuff that's already elsewhere, like install docs, just reference them. And maybe don't aim to make it perfect, we can always add missing bits later.

* [Rails](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)
* [Ruby](https://github.com/ruby/ruby/blob/trunk/CONTRIBUTING.md)
* [RSpec](https://github.com/rspec/rspec-core/blob/master/DEV-README.md) (sort of)
* [Travis CI](https://github.com/travis-ci/travis-core/blob/master/CONTRIBUTING.md)
* [Twitter gem](https://github.com/sferik/twitter/blob/master/CONTRIBUTING.md)
* [Piwik](https://github.com/piwik/piwik/blob/master/CONTRIBUTING.md)
* [cockpit](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md)
* [arangodb](https://github.com/arangodb/arangodb/blob/devel/CONTRIBUTING.md)

And so on, just look through your stars ;)

**Comment by Exilor** [comment]
This could be a related issue. In this case, the variable is visible *outside* the macro:
```ruby
macro for(*expressions, &block)
  {{expressions[0]}}
  while {{expressions[1]}}
    {{block.body}}
    {{expressions[2]}}
  end
end

for i = 0, i < 10, i += 2 do
  i
end

i #=> 10
```
I don't know if it's intended or not but just in case.

**Comment by ysbaddaden** [comment]
I noticed that macros don't create a new scope, but are injected as is into the current scope, hence the variable being available outside the macro. Actually, whatever variable you define inside the macro definition is "leaked".

I'm not sure how much of a bug this is, as long as macros are expected to be injected, and not be callable functions.

**Comment by Exilor** [comment]
@ysbaddaden 
```ruby
macro test(var, val)
  {{var}} = {{val}}
end

p test(x, 1) # => 1
x # undefined local variable or method 'x' (did you mean 'x'?)
```
It didn't leak in this case, although the message is wrong.

**Comment by asterite** [comment]
In the `test(var, val)` example, `x` shouldn't be visible afterwards.

However, this should work (and currently does):

```crystal
macro test(var, val)
  {{var}} = {{val}}
end

x = 10
test(x, 1)
p x #=> 1
```

That is, a macro is able to see change local variables, but not define them.

The `for` example is ok, `i` remains assigned and visible, because at the time of parsing `i` is assigned something, and so is considered a local variable, even if it finally doesn't get assigned something. It's just a syntactic rule.

However, it is still impossible to define a new unique variable inside a macro that won't conflict with existing variables. For example, consider [this macro](https://github.com/manastech/crystal/blob/evented/src/concurrent/concurrent.cr#L48). Here we used `__channel`, but that might conflict with an existing variable (unlikely, but can happen, specially if a previous invocation of the macro was used). For this we will make it possible to define unique variables like this:

```crystal
macro foo
  %var = 1
  %var
end
```

The `%var` syntax inside macros asks the macro to define a variable with a unique name.

**Comment by asterite** [comment]
Now it's fixed: variables declared inside a macro can't be seen outside.

I tried the `for` example (really nice, by the way), and now `i` isn't visible anymore outside it. What I said was wrong: even though `i` is a variable as seen by the parser, before the macro call it was never assigned a value, so after the macro it shouldn't have a value assigned.

**Comment by ysbaddaden** [comment]
Cool! That should help here: https://github.com/ysbaddaden/minitest.cr/blob/master/src/minitest/assertions.cr#L148 :-)

**Comment by Exilor** [comment]
If we're going to have "macro variables" it would be useful to make a "normal" variable defined inside a macro available outside of it.
Like:
```ruby
macro foo
  %var = 1
  var = %var
end
var  # => 1
```

**Comment by asterite** [comment]
Mmm... why do you need that?

**Comment by Exilor** [comment]
A crappy example: in Ruby, ```i``` in a ```for i in 0..5``` loop is available outside the loop (unlike variables in a block). If I want to emulate that behavior with a macro, I can't.

Also, constants behave that way:
```ruby
macro foo(name)
  {{name}} = 3
  Baz = 5
  class Asd; end
end

foo(Bar)

Bar # => 3
Baz # => 5
Asd.new # => #<Asd:0x248EFF0>
```
I'm just brainstorming here :) the choice is yours alone.

**Comment by asterite** [comment]
But in Ruby that's a built-in. In fact, there's no way in Ruby for a method to define local variables in the caller. That's because what `foo` means (a method call or a variable) is determined at parse time. And so it is in Crystal.
