### ISSUE TITLE
Inherited class inherits enum but can't access its values by name

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#476]
```ruby
class Foo
  enum Color
    Red
    Green
    Blue
  end
end

class Bar < Foo
end

Bar::Color::Red # => undefined constant Bar::Color::Red
Bar::Color # => Foo::Color
Bar::Color.values # => [Red, Green, Blue]
```

**Comment by jhass** [comment]
IMO the bug is that `Bar::Color` works at all.

**Comment by asterite** [comment]
Bug indeed.

In Ruby and in Crystal this works:

```ruby
class Foo
  class Sub
  end
end

class Bar < Foo
end

puts Bar::Sub #=> Foo::Sub
```

So I think accessing the enum via `Bar::Color` should work.

**Comment by jhass** [comment]
I guess it depends if we want to view structs, enums, classes, modules and so on as regular objects assigned to constants like it is in Ruby, or as their own thing, since the compiler treats those constants in a very special manner. If the former, `Bar::Color` should work, no question, however if the later, I'd very much say it's up for discussion.

**Comment by asterite** [comment]
But `alias` allows declaring recursive types. That is its main purpose, but you can also use it like doing `A = B` (except that in alias you can also use unions).

I think keeping it like it works now (like in Ruby) is ok.

**Comment by jhass** [comment]
Well, my point is that if we view classes, modules etc. as objects assigned to a constant, a union would need to be an object too and an alias would just be assigning that object to a constant. Creating a union would be calling the `|` method on a class, module or union object passing it another class, module or union as parameter. Note that I'm talking about the conceptual viewpoint here, not about how it's implemented.

**Comment by asterite** [comment]
Yes, a union will eventually be an object too, I guess. For example if you print this:

```crystal
puts Pointer(Int32 | Char).malloc(1)
```

Right now it crashes the compiler. That's because Pointer#to_s prints T, and T here is a union class (not just a union whose value will be known at runtime, but the class representing those possible values).

I guess a union will be something like `Union(T)` where T is a tuple of the possible types, but with a little twist. For example `Union(Int32, Char)` should be the same type as `Union(Char, Int32)`.

In any case, the above should eventually work, no matter how we implement it.

About `|` being a class method, it can be viewed like that if you want, except that it doesn't work with variables (`a = Int32; b = Char; c = a | b # error`).

But little by little we can try to make all those little details work... maybe, I don't like fiddling too much with types at runtime.
