### ISSUE TITLE
[RFC] Nicer Signal

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#483]
This is annoying:

```crystal
require "signal"

Signal.trap(Signal::INT) do
  # ...
end
```

Well, not very annoying but a bit redundant. In Ruby it's a bit cleaner:

```ruby
require "signal"

Signal.trap("INT") do
  # ...
end
```

The other day @waj came with the idea that we could transform Signal into an enum, and have `trap` be an instance method. That way you can do this:

```crystal
Signal::INT.trap do
  # ...
end
```

We can also add `ignore` and `default` methods (maybe with a bang to show they do something?), to ignore a signal or reset it to the default one:

```crystal
Signal::INT.ignore
Signal::INT.default
```

This will break some existing programs (looking at you, @jhass and @ysbaddaden), but that's the reason why we are still on 0.x, to remodel things as we discover new idioms and design patterns.

Another benefit is that you can list all signals because it will now be an enum.

What do you think?

(Right now this can't be implemented because of [this](private
private) and [this](https://github.com/manastech/crystal/commit/38bea9fc4850ca746d02c1451c8ca7f7242d1ebf), but once we are at 0.6.2 we could do it)

**Comment by jhass** [comment]
Would be nice with me +1

Don't randomly add bangs please, adopt a clear policy for them like Ruby core, that is if a bang variant exists a non-bang should exist. Technically `.not_nil!` would fail that, but we can add the `raise on nil` rule, we just should have a clear set of rules for adding a bang to a method, "signal they do something" is not a very good one.

**Comment by ysbaddaden** [comment]
I reopen Signal to avoid duplication, which forces me to use signals outside of any context (ie. I don't trap from an object instance).

```crystal
module Signal
  trap(INT) do
  end
end
```

This problem is more global, sockets and logger also "suffer" from this. This is why Ruby is allowing symbols/strings to fetch the constant at runtime.

Actually Logger in Crystal redefines the Logger::Severity enum values into Logger to reduce the problem.

**Comment by asterite** [comment]
@jhass You are right, we should have a convention for the bang. In Ruby core it's "mutates the array", don't know if there's anything else. In Crystal it's the same, except we also have `not_nil!`, as you say. We could change it to `not_nil` without problem, but the "!" there is so you know you are doing something "dangerous" (actually an incorrect assumption) that might fail. I don't know.

@ysbaddaden The problem with Ruby's symbols and strings is that if you have a typo you find out at runtime. You also have to do a switch based on the value to find out the desired behaviour. In Crystal an enum solves both problems: you get a compile-time error on typos, and the "switch" is already done by the user by selecting a value from the enum. I prefer this small readability penalty in favor of the other two benefits. But, if we can improve the readability, like in Signal's case, then I'm all for it.

**Comment by jhass** [comment]
Ruby core convention is as follows:

* If a method with a `!` exists, there exists one without.
* The variant without the `!` returns a modified copy, it's usually implemented as `obj = dup; obj.foo!; obj`.
* The variant with the `!` modifies the receiver. It returns the receiver if changes were made, otherwise `nil`.

Rails derivatives a bit, I think it doesn't follow the "return `nil`" rule and adds the following rule, at least for ActiveRecord:

* The version with the `!` raises an exception on errors, the version without `!` returns false instead.

As said, we don't have to follow these rules, we should just clearly define them. This is becoming increasingly offtopic though, maybe we should start a separate issue about this.

**Comment by ysbaddaden** [comment]
I do understand how better compile-time enums are vs runtime symbols, despite being more verbose. I just struggle to see the real need or benefit, to have a particular behaviour for signal enums vs others (sockets, logger, etc), so I'm challenging the idea in this RFC, to know whether this is great or not.

Having Signal be an enum would be better, for the aforementioned reasons. Yet I like the order of "signal trap x do y" which reads a bit better than "signal x trap do y". Maybe it's just habit.

**Comment by asterite** [comment]
This is already implemented :-)
