### ISSUE TITLE
samples/binary-trees.cr no longer compiles

### ISSUE THREAD

**Issue by kolyan1981by** [manastech/crystal#485]
```
Error in ./s1.cr:37: instantiating 'Int32#step(Int32, Int32)'

min_depth.step(max_depth + 1, 2) do |depth|
          ^~~~

in ./s1.cr:37: instantiating 'Int32#step(Int32, Int32)'

min_depth.step(max_depth + 1, 2) do |depth|
          ^~~~

in ./s1.cr:42: no overload matches 'Range(Float64)#initialize' with types Int32, Float64, Bool
Overloads are:
 - Range(Float64)#initialize(begin : Float64, end : Float64, exclusive : Bool)

  (1..iterations).each do |i|
   ^

```

**Comment by asterite** [comment]
Hmm... this broke because previously `Range` as `Range(B, E)`: the beginning and end could be of different types. Now it's `Range(T)` and they must be the same type. But I wonder if that was a wise change.

Maybe we should change it back to `Range(B, E)`? It's not that uncommon to want to have a range that begins in an int and "ends" in a float.

/cc @waj @jhass

**Comment by jhass** [comment]
You know me, I'm always in for more flexibility, I thought you had strong reason for that change :)

**Comment by asterite** [comment]
It was simplicity, but I didn't know you could have a range like `1 .. 2.5` in Ruby.

**Comment by jhass** [comment]
I think you can have a range of about anything in ruby, some methods will just run forever in some cases while others just use Range as a handy container for two values and peek at  `.begin` and `.end`.
