### ISSUE TITLE
Does not check for type returned by other function

### ISSUE THREAD

**Issue by KamilLelonek** [manastech/crystal#487]
def f(x: String)
      x
    end

    def g(y: Integer)
      puts y.class
      y
    end

    def h(a)
      g(f(a))
    end

    h("should throw an exception")

**Comment by asterite** [comment]
This actually works as expected, but it's bug-prone so I think it's time we fix this.

In your example, `Integer` doesn't exist. The name of the class you are looking for is `Int`. This gives the correct compile-time error:

```crystal
def f(x: String)
  x
end

def g(y: Int)
  puts y.class
  y
end

def h(a)
  g(f(a))
end

h("should not compile") # and does not
```

In fact, you don't need `f`, `g`, and `h` to trigger the "bug":

```crystal
def foo(x : SomeRandomWord)
end

foo "hello" # works
```

However...

```crystal
class SomeRandomWord
end

def foo(x : SomeRandomWord)
end

foo "hello" # error!
```

From this you can tell the compiler works like this: if it finds a type with the name on the type restriction, it checks if you pass the correct type. Otherwise, it lets the type pass, **and makes that name capture the given type**. That is, it acts as a free variable. For example:

```crystal
def foo(x : T)
  puts T
end

foo "hello" # prints String
foo 1 # prints Int32
```

Of course, if I go and define a type named "T", it stops working.

The above lets you do some nice things, like this:

```crystal
# Pass me two variables of the same type, I don't care which type
def foo(x : T, y : T)
end

# Pass me a type and an array of that type
def foo(x : T, a : Array(T))
end
```

But the rule "if the type is not defined then it's a free var" is very fragile and bug-prone. How can we improve this?

My ideas are:

1. Use a new symbol to denote free vars. For example `def foo(x : @T)` or `def foo(x : 'T)`.
2. Use the convention that in order to declare a free var it must be a single uppercase letter: `def foo(x : T)`. With this, the above example using `Integer` would have given an error.
3. Some other idea...?

I personally like number 2. Of course this won't work if someone defines a class named "T", but we can either disallow those names or just assume they won't be used for real programs (but it's nice to be able to use A, B and C in sample code). Another good thing about point 2 is that it's easy to implement and backwards compatible, and keeps noise at a minimum.

What do you think?

**Comment by KamilLelonek** [comment]
So I use Scala a lot and over there we have sth like that:

    def function[T](variable: T)
      puts variable
    end

I think that introducing generic types for methods or even classes would be an awesome idea. It may allow also use inheritance and Variance like:

    def function[-T](variable: T)
      puts variable
    end

or

    def function[+T](variable: T)
      puts variable
    end

![Alt text](https://monosnap.com/file/wKocMNrXI9k8sF424ySIvktl3vZq64.png)

Have a look: https://twitter.github.io/scala_school/type-basics.html

**Comment by ysbaddaden** [comment]
I'd go for number 2 with conventions:

- a generic is denoted as a capital letter (eg: `T`);
- convention says the first parameter should be `T`, and the return type should be `R`;
- convention says that single letter constants are allowed, but discouraged to avoid conflicting with generic types.

A quick grep into Crystal's source code, shows that these are used: `T` (first generic), `U` (second generic), `R` (return), `I` (iterator), `K`, `V` (key, value).
