### ISSUE TITLE
crystal init

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#505]
Lets continue conversation on this one https://github.com/generate-cr/library.template/issues/1 here, since it is a proper place to have it.

So, currently my `library.template` is able to generate such project structure:

```
$ tree example -a
example
├── .gitignore
├── libs
│   └── .keep
├── LICENSE      # Currently generates MIT
├── Projectfile
├── README.md
├── spec
│   ├── example
│   │   └── .keep
│   ├── example_spec.cr
│   └── spec_helper.cr
├── src
│   ├── example
│   │   └── version.cr
│   └── example.cr
└── .travis.yml
```

You can look, what exactly gets generated in these files here: https://github.com/generate-cr/library.template/tree/master/example

So the first question, do you have any suggestions on this structure, anything you would like to change ?

Current implementation uses `ecr` heavily and concept of `View` objects. It just iterates over the list of `View` objects and renders them. This means, that we have all the templates in the same structure here https://github.com/generate-cr/library.template/tree/master/template . And all the views here: https://github.com/generate-cr/library.template/tree/master/src/generate/library (all `*_view.cr`) files and a base class for them.

So the second question, do you like this kind of implementation? Is it good to have such a template (which basically mimics structure of the project)? Is it good to put such abstractions like `View` in compiler? Any other suggestions?

/cc @asterite

**Comment by asterite** [comment]
Hi! Sorry for the delay in replying.

The structure looks good. I'm not sure about why "libs" is necessary, it gets created by `crystal deps` but nothing from there is ever commited, so I'd skip that directory.

Then I think using `ecr` for that is OK. When I thought about it I was a bit worried that compiling the compiler will be slower because it will now use `ecr`, which invokes `run`, but then I remembered that for generating the docs we are using a similar technique :-) . Look at [this directory](https://github.com/manastech/crystal/tree/master/src/compiler/crystal/tools/doc), the [view files](https://github.com/manastech/crystal/tree/master/src/compiler/crystal/tools/doc/html) and the [view types](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/templates.cr). I chose to put all those small structs in a single file to avoid having many files in the filesystem... but it's ok to put them separately, like you did.

Then from [this line down](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/generator.cr#L50) you can see the code that renders those templates.

This way of implementing things is good because it's type-safe and fast, but it can be boring to write all that. Eventually we can have dumber templates with just string substitutions and maybe loops, and have those rendered dynamically, when rendering performance maybe doesn't matter that much (like in this case).
