### ISSUE TITLE
Is it compatible with ruby/gem code?

### ISSUE THREAD

**Issue by mrkaspa** [manastech/crystal#516]

**Comment by jhass** [comment]
No, Crystal has Ruby inspired syntax but is its own language.

**Comment by ysbaddaden** [comment]
Even thought it looks and feels a lot like Ruby to develop with Crystal, and that it used to be a Ruby implementation (of a subset) there now are a number of small and big differences between Ruby and Crystal and growing.

Tiny differences like single quotes denoting a single *char* like `'c'` versus double quotes denoting an unicode string like `"str"`; bigger differences like metaprogramming which mostly happens at compile time (using macros) to generate code, instead of at runtime like Ruby does.

So no, Crystal is not a Ruby implementation, but it looks a lot like it :smiley:

**Comment by waterlink** [comment]
@mrkaspa It is not compatible. Only very simple ruby code will be able to compile. Anything complex will probably fail by syntax. If it is lucky enough to have complying syntax (or you fixed all syntax errors), then you will probably get lots of type errors during compile time.

Any gem, that has even tiny bit of metaprogramming (defining anything at runtime) will not compile in crystal.

If you look at it as "Crystal = Compiled Ruby", you are wrong. Crystal just borrowed 90% of syntax from Ruby, and standard library looks somewhat similar.

**Comment by asterite** [comment]
Also, empty array literals require a type, so any gem with a `[]` out there won't compile.

**Comment by waterlink** [comment]
The same goes about hash empty literal: `{} of KeyType => ValueType`

**Comment by asterite** [comment]
I'll close this, no compatibility now or ever.
