### ISSUE TITLE
How much faster is Crystal compared to Ruby and JRuby in their lastest versions?

### ISSUE THREAD

**Issue by mrkaspa** [manastech/crystal#522]

**Comment by waterlink** [comment]
It is the same as asking, "How much faster is C++ compared to Ruby and JRuby in their latest versions?". Your question still sounds as if you think, that Crystal is yet another Ruby implementation. It is not. It is totally different language.

It is much-much faster. Since it is not a dynamic language. And it is not even a virtual machine language. You don't have any interpretation here. It just compiles down to native code, like C++, Rust, Go and other system languages.

**Comment by waterlink** [comment]
What would be interesting to measure, is how fast Crystal in comparison to C++/Rust/Go.

**Comment by asterite** [comment]
It all depends on the programs you are writing.

There are a couple of benchmarks [here](https://github.com/kostya/benchmarks) and [there](https://github.com/nsf/pnoise). There are also some in the samples directory, mostly written by @kostya, which show very good performance.

All of these benchmarks show that Crystal can get performance similar to C/C++/Rust by only programming in Crystal. And since you have access to raw pointers and memory (if you need to), you can optimize bottlenecks without ever leaving the language. I think this is the most important point. It's bad when you suddenly realize a language is not good enough for some task and you need to rewrite a portion of it in another language.

**Comment by mrkaspa** [comment]
Great! When will be available for production?

**Comment by waterlink** [comment]
Heh, a good question. With open source projects, I think they become production-ready, once somebody actually starts using it in production, discovers whole lot of bugs and problems, reports them (probably with pull request) and they got fixed, and then something may be considered production-ready.

So, if you like some project and want it to be production-ready, start using it now, report issues, contribute, make your friends do the same, ie: expand community. And eventually it becomes production-quality.

**Comment by waterlink** [comment]
And as far as I know, manastech company already uses it for something in production.. Am I right @asterite ?

**Comment by asterite** [comment]
@waterlink Well, we use it in an internal app. The app is a Slack bot that communicates with Google, Quickbooks and Brium, and uses Redis as a backend. So far it's working great :-)

There's also @jhass 's [DeBot](https://github.com/jhass/DeBot) which is used in our IRC channel and it's also working great. Or [this](https://github.com/jhass/github_desktop_notifications). And [this](https://github.com/porras/crul). And also [crystalshards](https://crystalshards.herokuapp.com/).

But I wouldn't consider these "production" as there's no client paying. The best thing to do, as @waterlink  says, is to learn and use the language and try to build things with it, reporting bugs and proposing changes/enhancements, to the point where you feel confident it's "production ready".

**Comment by ssvb** [comment]
The performance is very good, just the usage of the "--release" option (which enables optimizations) is a bit poorly documented, which is an obvious pitfall for newcomers.

**Comment by ssvb** [comment]
If we take the Ruby code from https://clifff.com/blog/2013/04/21/ruby-is-too-slow-for-programming-competitions/ and convert it to Crystal (also borrowing the palindrome test function from the Go implementation because reversing strings is too slow), then we get something like:

```
def int_palindrome?(num)
  n = num
  reverse = 0.to_i64
  while num > 0
    dig = num % 10
    reverse = reverse * 10 + dig
    num = num / 10
  end
  n == reverse
end

argf = File.open(ARGV[0]).read.split("\n")
argf.shift
count = 0
argf.each do |input|
  count += 1
  found = 0
  start, finish = input.split(" ").map {|a| a.to_i64 }
  sqrt_start = Math.sqrt(start).to_i64
  sqrt_finish = Math.sqrt(finish).to_i64
  (sqrt_start..sqrt_finish).each do |x|
    if int_palindrome?(x)
      square = x * x
      if int_palindrome?(square) && (start..finish).covers?(square)
        found += 1
      end
    end
  end
  puts "Case ##{count}: #{found}"
end
```

And then we can compare the performance of Crystal and Go (the Ruby benchmark is not included because it is way too slow):

```
wget https://gist.githubusercontent.com/clifff/5430194/raw/750151829069b4cc2ce93e52494c38e17745a30b/C-large-1.in

go build -o C-go C.go
crystal build --release -o C-crystal C.cr

time ./C-go < C-large-1.in > /dev/null

real	5m3.071s
user	5m2.789s
sys	0m0.160s

time ./C-crystal C-large-1.in > /dev/null

real	3m13.956s
user	3m13.715s
sys	0m0.025s
```

**Comment by asterite** [comment]
@ssvb very nice! I guess LLVM optimizes better than Go.

I think that program shows that it's good to have primitive integer values in the language, even though you have to be more careful sometimes (like, in your example you have to specify you want Int64). Fixnum to BigNum promotion is nice and convenient, but bans your language from many scenarios.

**Comment by ssvb** [comment]
@asterite Regarding the integer types size, it might be a good idea to ensure that the "to_i" method of String just throws an exception if the value does not fit, so that the absence of Fixnum to BigNum promotion is somewhat compensated. This would make porting code from Ruby safer.

https://code.google.com/codejam is ongoing, and the programming languages usage statistics is here: http://www.go-hero.net/jam/15/languages :-)

**Comment by asterite** [comment]
@ssvb Yes, it should raise. Right now we are using C's `atoi` but I also plan to implement custom parsing logic so we support underscores, like in Ruby. I just added [this issue](https://github.com/manastech/crystal/issues/547)

**Comment by asterite** [comment]
I'll close this, you have many answers here plus some benchmarks in the wild (or benchmarks you can do)
