### ISSUE TITLE
Conditional else keyword(s)

### ISSUE THREAD

**Issue by Ap0ph1s** [manastech/crystal#528]
Many popular mainstream languages use `else if`

I propose, to add to Crystal's incredible flexibility, to add an option so that you can use `else if`.

The reason it just to make Crystal even more flexible which is a very great trait to have, just a suggestion :P

**Comment by jhass** [comment]
-1 This adds unnecessary redundancy to the language.

**Comment by kirbyfan64** [comment]
Can't you just use `elsif`? It's 2 characters shorter.

**Comment by rhysd** [comment]
You can also use `case when ... end`.

```crystal
case
when true
  puts "foo"
when false
  puts "bar"
else
  puts "baz"
end
```

**Comment by asterite** [comment]
This adds more rules to the language for no real benefit. New rules must be explained and known, because someone might write things as `elsif` and someone else as `else if` so you must understand how they both work. Of course this is just a small thing to know/learn, but why add it if there's no *real* benefit to it? (that is, you won't get faster programs nor you will be able to make your code more readable, `elsif` is easy to learn, short to type, and if you know Ruby you already know it)

**Comment by ssvb** [comment]
-1 from me

The proposed "else if" construct is a little bit ambiguous (at least for a human) because you would always have to wonder whether it is in fact "elsif" or a nested "if" in the "else" branch. Consider the following example:
```ruby
if condition1
  puts "a"
else if condition2
       puts "b"
     else
       puts "c"
     end
     puts "d"
#end
```
The logic of the code would change, depending on whether the last "end" line is commented out or not.

I agree with @asterite, the ```elsif``` keyword is just better in every possible way. It is short to type and unambiguous.
