### ISSUE TITLE
optional end statements

### ISSUE THREAD

**Issue by Synatra** [manastech/crystal#533]
Instead of having to always use the `end` keyword with methods, classes, if statements and structs, we should have the option to use `}` or to use the paring braces `{}`

Any thoughts?

**Comment by jhass** [comment]
-1 This conflicts with block syntax.

```ruby
if numbers.any? {|n| (n*3).even? }
  puts "even number detected"
end
```

That may be unambiguous to the compiler, but it's confusing to the user and prone to user errors. Besides our syntax space is already quite packed, let's not give what we have left to something that just "solves" something that you would get used to anyway otherwise.

**Comment by Ap0ph1s** [comment]
@jhass Idk, it seems like since this is optional, the programmer would deliberately know which one to use, since its optional. I think many .would like this since they don't exactly like the end statements, I personally don't care for one, but I'm all for flexibility, +1 on my side, though doesn't seem like a need

**Comment by jhass** [comment]
Alright, larger example:

```ruby
class MyStuff {
  def foo {
    things = ["meep"]
    # Let's call any? without a block as an alias for !things.empty?, let's use braces for the if body
    if things.any? {
      puts "found something!"
    }
    
    # I like do end style though, for whatever reason
    10.times
      puts "meep"
    end
  }
}

MyStuff.new.foo
```

Assuming we patch `times` up to return an enumerator/iterator, the program will have no output, can you spot why?

**Comment by Ap0ph1s** [comment]
the times loop doesn't have a `do` ?

**Comment by jhass** [comment]
Yes, first point: we moved a compile time syntax error into a logical bug, second point, be honest with yourself, how long would you have needed to spot this without the comment, in a 500 lines file?

**Comment by Ap0ph1s** [comment]
Well the compiler would tell you, also, why would the programmer not include the `do` if we had the option vs not having it

**Comment by jhass** [comment]
We don't do that yet in Crystal, afaik, but in Ruby invoking `10.times` without a block is perfectly valid and returns an Enumerator. Forgetting the `do` is a common mistake, I still make it too from time to time after programming for years in Ruby.

**Comment by Ap0ph1s** [comment]
So you guys will soon be in favor for whitespace sensitivity and the `end` keyword for blocks ?

**Comment by jhass** [comment]
I don't see where you pull whitespace sensitivity from, let's not complicate this discussion with it. I also don't follow where you pull the "you guys" from, so far it's only me opposing this idea.

**Comment by Ap0ph1s** [comment]
Updated my comment, sorry for bad terminology and when I meant "you guys" I mean Crystal devs

**Comment by asterite** [comment]
Sorry, but no. This adds more rules to the language for no real benefit. See also my comments about adding `else if` [here](https://github.com/manastech/crystal/issues/528#issuecomment-92142604).

**Comment by Synatra** [comment]
Ok

**Comment by Synatra** [comment]
What about optional end statements but instead of using braces we could rely on indentation? thoughts @jhass ? @asterite ?

**Comment by jhass** [comment]
Crystal is inspired by Ruby, not Python ;)

And again, mixing such stuff is not improving user experience, it's making it worse IMO. The fundamental syntax of how code blocks are formed is nothing you just mix and mash together, it's a core decision of the language and here it has been made already.

**Comment by asterite** [comment]
@Synatra Take a look at [Nim](http://nim-lang.org/), for example, specifically the [Source Code Filters](http://nim-lang.org/filters.html) section. You will find it says:

> Because indentation-based parsing is not suited for a templating engine, control flow statements need end X delimiters.

So they use **end if**, **end for**, etc, in their templates, which means users must learn a new language. In Crystal an ECR file looks like this:

```crystal
<% [1, 2, 3].each do |i| %>
  Number: <%= i %>
<% end %>
```

It's the same language, no need to learn nothing new.

Indentation not only plays bad with templates, but also with macros. For example [this one](https://github.com/manastech/crystal/blob/master/src/json/mapping.cr). I would go crazy if I had to make the generated code respect indentation. Now I only need to worry about newlines and matching "end"s. Very simple.

And, personally, I find indentation-based code hard to read when the code is large, more than a screen. Sure, you will say "refactor your code into smaller functions", but try to do that in a hand-made parser :-) . I find I always have to go up with my eyes and see where a block ends... maybe you get used to that after a time, I don't know, but I prefer to reuse my existing eye/brain abilities to match things by visibility.

And, as @jhass says, something having more freedom is worse. The more you allow changing and customizing a language's syntax, the more it looses its identity and its idioms.

**Comment by Synatra** [comment]
Most users will not use templates/macros, and those who will probably do not care about it.

```
proc doA = echo "done a"
proc doB = echo "done b"

let 
  conditionA = true
  conditionB = false

if conditionA:
  if conditionB: doA()
  else: doB()
  
echo "done"
```

```
def doA
  puts "done a"
end

def doB
  puts "done b"
end

conditionA, conditionB = true, false

if conditionA
  if conditionB 
     doA
  end
  else 
     doB
end

puts "done"
```

See the benefits of Nim's indentation?

**Comment by kirbyfan64** [comment]
@Synatra The biggest program is that `end` statements and indentation do NOT go well together. For instance:

    class MyStuff
      def foo
        things = ["meep"]
        if things.any?
          puts "found something!"
        end
      end

Is this correct or not? Which `end` is associated with what? This would require virtually infinite parser lookahead.

Also, I agree with @jhass and @asterite in that adding more features isn't going to help. That's why nobody can read someone else's Perl code.

However, I disagree that indentation-based code is harder to read. You should indent it anyway... ;)

**Comment by dziulius** [comment]
I find indentation based languages (python, coffescript, you name it) pain in arse. It makes my brain swallow.

Also refactoring harder. Moving code around, namespacing classes, putting code block into if statement, etc requires manual reindentation. While in normal langues you can ask your editor to auto-format your code.

**Comment by mverzilli** [comment]
I guess it comes down to what @asterite says here: http://crystal-lang.org/2014/12/06/another-language.html

Indent vs. braces vs. _end_ is at the end of the day a matter of personal taste. 

Fact 1: The team behind Crystal picked _end_. There's no point in discussing that choice: since it's a matter of taste, there's no clear objective winner. Changing that choice would make Crystal... another language.

Fact 2: Supporting 2 of those options at the same time would not only make it a new language, but also would make the parser much much more complex and cumbersome to work with.

If you like indentation-based languages, there's Nim, if you like everything about Crystal except indentation, maybe you can learn to live with that little personal inconvenience and help the community make great design decisions from now on. 

That decision in particular was already made and the community won't derive considerable benefits from changing it (some people will be happy because they're into indentation-based syntax and others will be sad because they prefer _end_), in the end it's zero-sum game.
