### ISSUE TITLE
Variable overflow / dynamic type-checking issue

### ISSUE THREAD

**Issue by grzesiek** [manastech/crystal#550]
Hi all !

Suppose there is following pice of code:

```crystal
a = 1
(1..100).each do |i|
  a = a * i
end
puts a
```

This prints `0` and is kind of confusing. **In my opinion this should report some kind of RuntimeError when `a` is overflowed**. This also won't work when `a = 1_u64` etc. as unsigned int 64 is not enough for **100!**.

This leads to more general problem - handling BigNums. As for now I can't find solution for this.

Kinds regards,
 Grzegorz Bizon

**Comment by jhass** [comment]
Regarding your second question, stdlib ships a binding to gmp with the class BigInt: https://github.com/manastech/crystal/blob/master/spec/std/big_int_spec.cr

**Comment by grzesiek** [comment]
Ok, then using BigInt is solution for creating big numbers explicit way, but this piece of code above should work out-of-the-box without explicitly creating BigInt, shouldn't it ?

**Comment by jhass** [comment]
Related to #547

**Comment by asterite** [comment]
@grzesiek We don't know yet what to do in this case. As we want performance, and most compiled languages out there don't check overflows on every math operation because of that, we'll probably leave things like this.

I think that, when dealing with a given problem, you know if you are going to need BigInt or not. For example if it's project euler, a competition, etc., chances are that you'll need BigInt. But in real-life BigInt rarely appears. Unless, again, there's some part of your problem where you are almost sure you are going to need big numbers.

Anyway, that's just my opinion. In my years of programming I can't remember the last time I needed BigInt, or I was thankful that Ruby converted the numbers for me like that.

For your specific snippet, you can do this:

```crystal
require "big_int"

a = 1.to_big_i
(1..100).each do |i|
  a = a * i
end
puts a #=> 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000
```

**Comment by grzesiek** [comment]
@asterite Thanks for explanation, however in my opinion this shouldn't be left like this. This is confusing and may lead to serious language-wide implications.

I believe that this is more general problem. I agree that most  compiled languages don't check for variable overflows, however most of compiled languages are typed languages. Leaving this as is in crystal, where language is not strongly typed may have some extensive implications.

So, when you declare types of variables is statically typed language - you can agree on unchecked overflows (it is your your fault when something explodes) but in case like above - this is not true. in case of dynamic type-checking responsibility falls on language itself and it is languages job to notify user, at runtime, when something is wrong.

I think that this issue may reflect one of most serious flaws in crystals design. I strongly encourage further discussion.

Cheers,
 Grzegorz

**Comment by jhass** [comment]
> Leaving this as is in crystal, where language is not strongly typed may have some extensive implications.

How do you define strongly typed? Since for my definition Crystal is both, strongly and statically typed.

**Comment by grzesiek** [comment]
@jhass I mean strongly typed defined as in wikipedia -- 

> A strongly typed language is more likely to generate an error or refuse to compile if the argument passed to a function does not closely match the expected type

No I see that crystal is supposed to be strongly typed, but again, my example above violates that definition. So now this can be considered as bug instead of being a result of conflicting assumptions.

Yes, I agree that we are on some new, debatable territory, thus discussion is important. Maybe this short article may come in handy for someone - https://www.omniref.com/blog/blog/2014/11/17/matz-at-rubyconf-2014-will-ruby-3-dot-0-be-statically-typed/

**Comment by grzesiek** [comment]
#497

**Comment by ysbaddaden** [comment]
Just an example: I once had to deal with binary computations in Ruby, which involved using lots of modulos to "overflow" integers, which was the expected outcome (and is quite frequent in C based algorithms).

It means that ruby took care to not overflow, which requires a performance loss, which I eventually told to discard, when CH is another performance loss. I'm not saying this specific example should direct any decision here, but having the control over this behavior is great.

Since Crystal is far closer to C than Ruby is, and differentiates the different integer sizes, it feels natural (to me at least) that these integers will overflow.

This must be documented thought, and maybe part of a Crystal for Rubyists FAQ.

**Comment by jhass** [comment]
> my example above violates that definition

I might be missing something, but I don't see why that would violate it. It just overflows, it doesn't change its type, it doesn't treat a comparable value represented in another type as equal and it doesn't accept another type in place of the intended one. And I can't come up with anything in Crystal that would do so. If you type restrict a method to take an Int32, it takes a Int32 and nothing else.

**Comment by kirbyfan64** [comment]
99% of statically typed languages don't guard against overflow. It's expensive.

Of course, maybe overflow checks could be added in debug mode but not release mode. I think that's what Nim does.

**Comment by grzesiek** [comment]
Well, I am by no means an expert, I've just pragmatic point of view. For me this behaviour is confusing. Maybe because I'm using Ruby a lot. This also may lead to bugs that are very difficult to fix. 

However I got your point, so I'm closing this issue.

**Comment by ysbaddaden** [comment]
Check in debug but not in release? Sounds a bit dangerous, unless you mean that it fails with an exception in debug?

**Comment by kirbyfan64** [comment]
@ysbaddaden Yup.
