### ISSUE TITLE
request: lightweight block syntax

### ISSUE THREAD

**Issue by will** [manastech/crystal#561]
One of the things I miss most from smalltalk is the super lightweight, first-class block syntax `[code]`, which made it common to pass more than one block to a method. Since Ruby and so far what I've seen of Crystal makes a special case of passing a single block to a method, I've rarely done several blocks in Ruby. Especially combined with [keyword arguments](https://github.com/manastech/crystal/issues/560), you can have nice semantics like 

```
    aBoolean
	ifTrue: [someCode]
	ifFalse: [otherCode]
```

and 

```
    aValue switch
	case: [matchCode1] then: [actionCode1]
	case: [matchCode2] then: [actionCode2]
	...
	default: [otherCode].
```

**Comment by jhass** [comment]
If we do this I'd vote for extending the current block shortcut only, something like:
```ruby
validate &.airbags(has: 4), if: &.car?, unless: &.historic?
```

However I don't mind the current Proc syntax once it interferes its argument types:

```ruby
validate ->(vehicle) { vehicle.airbags(has: 4) }, if: ->(vehicle) { vehicle.car? }, unless: ->(vehicle) { vehicle.historic? }
```

**Comment by asterite** [comment]
The special block case is actually very special: you have next, break, return, and many things that actually make blocks very different than captured procs.

Having a method receive more than one proc is pretty rare, and in those cases it doesn't hurt to write the long version.

Also, there won't (probably) be a time when a proc infers its argument types, because the type inference works from method arguments to method instantiation. In this case we would need to infer the argument's type from the chosen method, but to choose the method (the overload) we must first type the arguments. Maybe we can make an exception: "if there's only one method with that name...", but I think that complicates the logic, and exceptions are not good.

**Comment by asterite** [comment]
@will Can I close this? I'd like to keep the language small, the case where you need more than one proc is pretty rare so probably doesn't deserve a whole new syntax.

**Comment by will** [comment]
Yeah sounds good.
