### ISSUE TITLE
false's falsyness unknown at compile time

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#566]
```crystal
(nil || "foo").reverse # => "oof"
(false || "foo").reverse # => undefined method 'reverse' for Bool
```
It's tricky because you can rely on nil being always falsy but a Bool could be either true or false. Thoughts?

**Comment by ssvb** [comment]
I guess, the Nil type is very nice because it can be used in a union with some other type, and then decoupled from it at runtime via simple branching in the code: https://github.com/manastech/crystal/issues/547#issuecomment-95041690

But your expressions don't seem to make much sense to me. The first one always reduces to "foo".reverse, so there is no point using the conditional expression here in the first place. For the second one, either we know the exact boolean value at compile time or we don't. If we do know the exact value, then it is either the same no-op as the first nil expression (redundant useless code) or it is a compilation problem because we are supposed to call the "reverse" method for this Bool variable. And if we don't know the exact value at compile time, then the code must be ready to handle the "true" value at runtime, so it needs the "reverse" method implementation for the Bool type. Can you try to provide a more practical example?

**Comment by Exilor** [comment]
@ssvb You're right. I should have thought this more thoroughly.
