### ISSUE TITLE
macro inherited inconsistencies

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#576]
I'm playing with the inherited macro again (to add specs to minitest), and stumbled upon an inconsistent contents for `[] of A.class`. Take the following code:

```crystal
class A
  @@children = [] of self.class

  def self.children
    @@children
  end

  macro inherited
    p A.children << self
  end
end
```

The following class definitions are correct:

```crystal
class B < A; end   # => [B]
class C < A; end   # => [B, C]
class D < C; end   # => [B, C, D]
```

Add this class, and... it's wrong (despite `self` being correct in the inherited macro):
```crystal
class E < D; end   # => [B, C, D, C]
```

Eventually add this one and... it's correct again:
```crystal
class F < B; end   # => [B, C, D, E, F]
```

**Comment by ysbaddaden** [comment]
The issue title may be wrong, since I think the array of classes is the faulty one.

**Comment by asterite** [comment]
It turns out it has nothing to do with inherited:

```crystal
class A
end

x = [] of A.class

class B < A; end

x << B
puts x   # => [B]

class C < B; end
x << C
puts x   # => [B, C]

class D < C; end
x << D
puts x   # => [B, C, B]
```

The problem seems to be that `puts(Array(A.class))` is being instantiated, but then A gets more members inherited so that method isn't getting recomputed (at compile-time). I'll try to fix it.

By the way, if you don't print it inside the inherited macro but outside it, at the end, it seems to work fine. So if you was using it for debugging maybe it's not that a big deal (still a bug).

I also found that if you use a method with a block inside inherited, it crashes the compiler.

**Comment by asterite** [comment]
The same also happens if you have `[] of A` and add B.new, then define C, then add C.new, etc. The "problem" is that Crystal doesn't handle well typing code and then modifying the class hierarchy or the methods. Crystal assumes you first define your hierarchy and methods, maybe monkey patch things, and then start the program (the main code). If you mix code with class/method modification you'll get these unexpected behaviours.

We obviously have to find a resolution to this, but I it's a hard problem.

**Comment by asterite** [comment]
Sorry for the dramatism :-P. When I started looking deeper into the problem it reminded me of #448 and I thought "Wait! I fixed this already! Déjà vu?"

Turns out we do the necessary recalculations when a subclass is added. Problem was, only the superclass was notified about having new subclasses, but that superclass' superclass wasn't being notified (was missing a recursive call). It's a long explanation, but basically the target of the call is `A.class`, and that's why when you did `class F < B`, that notified A of a new subclass and it started working again (but didn't work for `D < C`).

**Comment by strcmp** [comment]
@asterite dude, you rock! :100: I read this and thought, damn, it's a shame this will be a while to fix, and 30 minutes later you closed it. Great work :)

**Comment by ysbaddaden** [comment]
Thanks a lot for fixing it! I know meta programming and macros are very hard, and I'm pushing the limits a bit with the minitest port ;-)

**Comment by asterite** [comment]
@strcmp :blush:
