### ISSUE TITLE
Why do macros allow you to specify types without error just to ignore them?

### ISSUE THREAD

**Issue by yyyc514** [manastech/crystal#596]
```
macro x(y : String)
	puts "suzy"
end

x(1)

# => "suzy"
```

Expected: Error that no macro or method taking Int32 could be found, etc.

**Comment by asterite** [comment]
Because the language is incomplete and not every case has been considered.

Macros accept AST nodes, so a restriction like `String` doesn't make sense. In the future we might want to allow restricting a macro with node types, for example with `StringLiteral` or `NumberLiteral` or `Call`. Maybe for now we can disallow type restrictions in macros.

**Comment by yyyc514** [comment]
> Maybe for now we can disallow type restrictions in macros.

Yeah, if it wasn't going to work I would have expected a compiled error letting me know it wasn't allowed.

**Comment by yyyc514** [comment]
Thanks! :-)
