### ISSUE TITLE
Wierd benchmark results

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#656]
So, I wanted to see how Crystal handles some stuff differently from Ruby, and got some very strange results.

Crystal Code:
```ruby
puts "Starting Tests"
s_t = Time.now
a = 0
b = [] of Int32
c = ""
d = {} of Symbol => String
d[:string] = ""
10000.times do
  a += 1
  b << a
  c += "#{b}"
  #d[:string] << c
end
e_t = Time.now
puts "Finished testing in #{e_t - s_t} sec"
```

Ruby Code:
```ruby
puts "Starting Tests"
s_t = Time.now
a = 0
b = []
c = ""
d = {}
d[:string] = ""
10000.times do
  a += 1
  b << a
  c += "#{b}"
  #d[:string] << c
end
e_t = Time.now

puts "Finished testing in #{e_t - s_t} sec"
```

Ruby did it on my pc in 11 sec.
Crystal reached 14Gig RAM and I had to close it (after around 1.5 min).

Why is that ?

**Comment by jhass** [comment]
Because string handling, Ary will probably write a more elaborate answer. The following beats Ruby in release mode by far:
```crystal
puts "Starting Tests"
s_t = Time.now
a = 0
b = [] of Int32
d = {} of Symbol => String
String.build do |c|
  10000.times do
    b << a
    a += 1
    c << "#{b}"
  end
end
e_t = Time.now
puts "Finished testing in #{e_t - s_t} sec"
```

**Comment by asterite** [comment]
@barachy did you mean the Ruby version takes 11 minutes (not seconds). I run it and it took about 500 seconds to finish.

I don't know why Crystal allocates more memory, it's probably related to how boehm GC works.

In any case, using `+` for string concatenation in a loop is bad, both in Ruby and Crystal, because `+` creates a new string and you have to copy lots of bytes. As @jhass showed, the efficient way to build a string is using `String.build`. Also, when building a string like that there's no need for `"#{b}"`, you can just do `c << b`.

Now, let's compare Ruby and Crystal using string building. In Ruby it's:

```ruby
puts "Starting Tests"
s_t = Time.now
a = 0
b = []
c = ""
d = {}
d[:string] = ""
10000.times do
  a += 1
  b << a
  c << "#{b}"
end
puts c.length
e_t = Time.now
puts "Finished testing in #{e_t - s_t} sec"
```

Prints "289463389" and it takes 11 seconds on my machine... which makes me think this was your original benchmark, maybe? Maybe then you tried to port it to Crystal and found that `<<` doesn't exist for String, so you changed it to `+=`?

The Crystal version:

```crystal
puts "Starting Tests"
s_t = Time.now
a = 0
b = [] of Int32
d = {} of Symbol => String
c = String.build do |c|
  10000.times do
    a += 1
    b << a
    c << b
  end
end
puts c.length
e_t = Time.now
puts "Finished testing in #{e_t - s_t} sec"
```

Prints "289463389" and takes 1.71 seconds. The variant with `c << "#{b}"` takes 1.85 seconds: not a big difference, but slower.

**Comment by mverzilli** [comment]
Would it be too _radical_ to just remove the "+" operator from String? It's a common pitfall for beginners (and not-so-beginners) in many languages! 

When I was starting to learn Java I remember @asterite would always remind me not to build strings through "+", and to resort to StringBuilder instead. 

I always wondered why the most expensive way of concatenating strings got the cheapest syntax (probably a legacy from C?). 

Nothing beats "+" (or "&" or whatever operator they use to concatenate strings on your language of choice) when it comes to succinctness, yet we use it for an expensive operation! There should be some sort of commensurability between the effort to write something and how convenient it is.

**Comment by bararchy** [comment]
@asterite  point on about the "Maybe then you tried to port it to Crystal and found that << doesn't exist for String, so you changed it to +=?" I even didn't see that I haven't re-changed it back.

I guess I just need to learn the syntex more, thanks on the detailed answer !

**Comment by kirbyfan64** [comment]
@mverzill. The concatenation operator is handy for simple cases.

**Comment by asterite** [comment]
@mverzilli I thought about that many times. I just tried it with the compiler's code base but, indeed, in some cases it's handy.
