### ISSUE TITLE
[RFC] Override Tuple#map to return a Tuple

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#683]
I think that's more logical, more efficient and increases flexibility. Possible implementation:
```ruby
struct Tuple(T)
  def map
    {% if true %}
    Tuple.new(
      {% for i in 0 ... @length %}
        (yield self[{{i}}]),
      {% end %}
    )
   {% end %}
  end
end
```

Contra: It'll be inconsistent with at least part of Enumerable, we can't have things like `Tuple#select` return a tuple.

**Comment by asterite** [comment]
I agree with this. I prefer the performance gain over the small inconsistency. You can always invoke `#to_a` later to get the old behaviour.

After I changed this the compiler didn't work because apparently we were using `Tuple#map` (well, `Enumerable#map`) in the codegen phase, and then `Array#last`, but `Tuple#last` didn't exist so I added that too. But to correctly implement `Tuple#last` I needed math operations in macros, to do `self[{{@length - 1}}]` so I added that too :-P

The downside of `Tuple#map` is that it will always return a tuple where all elements have the same type, because there's a block. But I don't think this matters, most of the time the mapped tuple will come from variadic arguments that will probably all have the same type, like in the use case I found in the compiler. And now that part will be a bit more efficient :-) (although I don't think it will affect the overall performance)
