### ISSUE TITLE
How to describe before_each block in spec?

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#687]
How to properly describe before_each block in spec file?

describe Request do
  before_each do
     ....
  end

not works

**Comment by jhass** [comment]
They're only global for now http://carc.in/#/r/dt

**Comment by Codcore** [comment]
@jhass , I make it global, but variables declared in global namespace, is unseen in blocks of "it" methods. Just as planned? Look: http://carc.in/#/r/dx

**Comment by jhass** [comment]
Yes that's intentional for now and I'm not sure if stdlib spec will ever be replaced by a variant that would support things like that. The global hooks are intended for things like mocking libraries.

The alternative implementations we tried are a lot slower to compile, here's a PoC of such: https://gist.github.com/jhass/e9219dd9da24204a073d

**Comment by Codcore** [comment]
@jhass Thanks, got it

**Comment by ysbaddaden** [comment]
You may want to look at my minitest's port: https://github.com/ysbaddaden/minitest.cr which allows it.

**Comment by Codcore** [comment]
@ysbaddaden , thanks!
