### ISSUE TITLE
About functional programming

### ISSUE THREAD

**Issue by kerkomen** [manastech/crystal#728]
There seems to be no roadmap for Crystal development. However it would be great to know if there are any plans on implementing some nice features from the functional world.

There are Ruby-inherited `map`, `select` and `inject`, and the latter one has a somewhat strange name ([some ref](https://tommorris.org/posts/2595)). One more thing is that lazy evaluation seems to lack from Crystal:

```ruby
(1..10).lazy.select { |x| x % 2 == 0 }.to_a  # Works in Ruby, not in Crystal  
#=> [2, 4, 6, 8, 10]

(1..10).select { |x| x % 2 == 0 }            # Works both in Ruby and in Crystal  
#=> [2, 4, 6, 8, 10]
```

Just curious to know what do other people think about that.

// Found a cycle of articles on functional programming in Ruby: [1](http://www.sitepoint.com/functional-programming-techniques-with-ruby-part-i/), [2](http://www.sitepoint.com/functional-programming-techniques-with-ruby-part-ii/), [3](http://www.sitepoint.com/functional-programming-techniques-with-ruby-part-iii/).

**Comment by datanoise** [comment]
It's already there. http://carc.in/#/r/1fs

`each` returns an iterator that provide lazy evaluation. This design reminds me a bit of the rust-lang iterators. Contrary to ruby, crystal's lazy iterators provide quit a bit of performance boost when you compile with `--release` option.

**Comment by kerkomen** [comment]
Awesome. And it works on infinite lists as it should: http://carc.in/#/r/1g2.

And typing `1.0/0.0` is the only way construct the infinite list, isn't it?..

**Comment by datanoise** [comment]
you can use `step` as well: http://carc.in/#/r/1g7

**Comment by jhass** [comment]
I'd prefer to use https://github.com/manastech/crystal/blob/master/src/float.cr#L57 instead of constructing it manually, future proof and more readable.

**Comment by asterite** [comment]
@datanoise Yes, the iterator design is similar to that of Rust. In Rust there's a `next` method that returns an `Option`. In the beginning we tried implementing Iterator like in Ruby (well, Ruby's Enumerator), raising an exception when there are no more elements.. but this turned out to be very slow. So we tried with `Option`, using `nil` to mark the end, but that prevents us from having iterators that yield nil values. So we use another type (Iterator::Stop) to mark the end, and, thanks to union types, problem solved :-)

Actually, we first tried Java's way, where you have a `next` method and a `hasNext` method... but that is harder for iterator implementors because you need to provide two methods and I think you need more state.

We also had an `Enumerator` in the beginning, like in Ruby, that worked with channels and spawn, but it was so slow we removed.

Iterators are really cool. For example here's [Fibonacci](http://play.crystal-lang.org/#/r/1gz).

**Comment by datanoise** [comment]
I agree, type union is one of my favorite features that keeps me coming back to crystal and i'm pretty sure it is one of the unique language features out there. It makes language feel very dynamic and removes clunky stuff like `Option<T>` or constantly forgetting to check for nil return values.

**Comment by asterite** [comment]
I'll close this, we have `Iterator` for lazy functional programming :-)

Reopen if you need so.
