### ISSUE TITLE
Sleep in Threads does not work

### ISSUE THREAD

**Issue by jbye** [manastech/crystal#747]
Crystal 0.7.2 [3034ebb] (Tue May 26 16:35:46 UTC 2015)

Calling `sleep` in Threads does not work w/ Crystal 0.7.x; the thread seem to block forever at the sleep call.

Example code:

```
Thread.new {
  3.times do
    puts "Running"
    sleep 1
  end
}.join

## Produces ##

Running
Could not get the current fiber (Exception)
*Exception#initialize<Exception, String, Nil>:Array(String) +46 [3075112024]
*Exception::new<String>:Exception +149 [3075112024]
*raise<String>:NoReturn +34 [3075112024]
*Fiber::current:Fiber +82 [3075112024]
*Scheduler::sleep<Int32>:Int32 +74 [3075112024]
*sleep<Int32>:Void +84 [3075112024]
~fun_literal_11 +87 [3075112024]
~fun_literal_10 +55 [3075112024]
*Thread(Nil, Int32)@Thread(T, R)#start<Thread(Nil, Int32)>:(Int32 | Exception+) +131 [3075112024]
~fun_literal_8 +45 [3075112024]
GC_calloc_explicitly_typed +837 [3075112024]
GC_call_with_stack_base +49 [3075112024]
GC_calloc_explicitly_typed +959 [3075112024]
start_thread +227 [3075112024]
clone +94 [3075112024]
Program terminated abnormally with error code: 256
```

However, running the example code above w/ Crystal 0.6.1 produces the expected output;
```
Running
Running
Running
```

(0.7.2 ; does not work) http://play.crystal-lang.org/#/r/23m
(0.7.1 ; does not work) http://play.crystal-lang.org/#/r/23n
(0.6.1 ; works) http://play.crystal-lang.org/#/r/23o

**Comment by ysbaddaden** [comment]
Duplicate of #722

**Comment by asterite** [comment]
One thing to add to what @ysbaddaden points out: since we introduced spawn and channels, Thread doesn't make sense anymore. Well, maybe it does, but it doesn't play nicely with blocking IO. Eventually the runtime scheduler will spawn processes in multiple threads. The scheduler will be the one using the Thread class, but not end users.

I guess for now I'll add a comment like "Don't use this class, it is used internally by the event scheduler" (even though it's a lie because there's only one thread right now).

@jbye An alternative to your program using spawn and channels: http://play.crystal-lang.org/#/r/24u

**Comment by jbye** [comment]
@asterite thanks, I'll go that route
