### ISSUE TITLE
[RFC] Consider using a single colon for type declaration

### ISSUE THREAD

**Issue by asb** [manastech/crystal#758]
Currently, `::` is used for type declaration, while `:` is used for type restriction in method arguments and the like. Although I can see an argument that these are subtly separate operations, I also think it's easier for the programmer to remember "if I want to specify a type, use `:`". One of the reasons for using `::` is the potential ambiguity with the ternary operator. I would suggest dropping support for the ternary operator, and thus freeing up `:`.

Right now, I can write `a = 1 > 2 ? 3 : 4`. An alternative one-line way to write this is `a = if (1 > 2) 3 else 4 end`. Ruby doesn't accept this and requires a `then` when writing an if on a single line, which I think reads better `a = if (1 > 2) then 3 else 4 end`. Another potential variant that is not currently supported would be to allow an else after a suffixed if, e.g. `a = 3 if 1 > 2 else 4`.

This also has relevance to issue #406.

**Comment by vyp** [comment]
If it is dropped, I like the python like secondary variant. But, sorry for being a bit naive, isn't one of the the goals of crystal to have same/very similar syntax to ruby? I am new to crystal, but wouldn't this be a major change? (What other changes are there in crystal so far? I haven't seen any documentation on the differences between ruby and crystal except for https://www.reddit.com/r/crystal_programming/comments/2kpxzx/crystal_for_those_that_only_know_ruby/.)

**Comment by jhass** [comment]
-1

The difference between a restriction and a declaration isn't subtle at all, dropping core syntax like ternary solely by claiming it would be subtle is very unjustified in my opinion.

**Comment by vyp** [comment]
FWIW to clarify, I am -1 as well.

**Comment by asb** [comment]
@vyp: the aim of Crystal seems to be to be familiar to Ruby programmers, but multiple statements from @asterite indicate there isn't a desire to be limited by attempting complete Ruby syntax compatibility.

@jhass: There is a difference yes, but does the average programmer need to care about it? Type restriction is introduced at the end of http://crystal-lang.org/docs/syntax_and_semantics/instance_variables_type_inference.html for if you want to fix the type of an instance variable. My argument is that the following is more uniform and more easily guessable:

    class Person
      @age : Int32

      def initialize(@name : String)
        @age = 0
      end
    end

I have no strong affection for the ternary operator, as I point out - it only saves a few characters vs other short if/else expressions and that comes at the cost of decreased legibility.

It's not something I feel particularly strongly about and others may of course disagree about the utility of the ternary operator.

**Comment by vyp** [comment]
Thanks for the clarification regarding parity with ruby syntax. However, like jhass, I still don't see much of the advantage for what is I consider dropping a major syntax. I don't think it's subtle, and even then, the being guessable issue should become less of an issue the more you use Crystal, I think. Again, this might just be because I am not knowledgable enough in Crystal, so best to wait for those more knowledgable to give their opinion than to waste time arguing with me.

**Comment by asterite** [comment]
@asb From the issue's title it isn't clear to me: do you want to drop the ternary operator, or you want to be able to set types with a single colon? (my guess is the second)

It's true that `:` would bring a grammar ambiguity: in `a ? b : C`, it could be `a ? (b : C) ...` or `a ? (b) : (c)`. That's why we used `::` in the first place (we did use `:` in the beginning but soon found that ambiguity).

However, I now think that this could be solved if the parser knows it's inside a ternary operator branch: one wouldn't normally use a variable declaration inside it. So the ambiguity will be gone. It's a small logic that's added to the parser, but maybe it's worth it.

There's still the thing that `:` is used for type restriction and `::` is used for type declaration, which are different, but it's true that `:` is easier to type and read, and probably more intuitive.

Let's take an existing code. For example:

```crystal
module FileUtils
  def cmp(stream1 : IO, stream2 : IO)
    buf1 :: UInt8[1024]
    buf2 :: UInt8[1024]

    while true
      read1 = stream1.read buf1.to_slice
      read2 = stream2.read buf2.to_slice

      return false if read1 != read2
      return false if buf1.buffer.memcmp(buf2.buffer, read1) != 0
      return true if read1 == 0
    end
  end
end
```

vs. 

```crystal
module FileUtils
  def cmp(stream1 : IO, stream2 : IO)
    buf1 : UInt8[1024]
    buf2 : UInt8[1024]

    while true
      read1 = stream1.read buf1.to_slice
      read2 = stream2.read buf2.to_slice

      return false if read1 != read2
      return false if buf1.buffer.memcmp(buf2.buffer, read1) != 0
      return true if read1 == 0
    end
  end
end
```

Maybe it's because I'm used to `::` already, but having `:` mean "type restriction" and "type declaration", so close to each other makes it harder for me to read the last snippet.

Thoughts?

**Comment by asb** [comment]
@asterite you're correct that I don't have a particular reason to want the ternary operator gone other than wanting `:` for type restriction.

I have to say, that to my eyes as a relative newbie to Crystal the second version *does* read easier. I read it as "stream1 is an IO, stream2 is an IO, buf1 is a UINT8 array, ...".

**Comment by jhass** [comment]
But that's the point, `::` is not "is an", it's more, it's "create a of"

**Comment by PragTob** [comment]
For what it's worth, I'd be glad to see crystal drop the ternary operator for whatever reason. To me it's construct with bad readability built-in - a simple if/else is enough imo.

**Comment by vyp** [comment]
Think the title might need to be changed, @asb says it's not the ternary operator specifically, but to use a single colon for type declaration.

Because as @asterite says:

> However, I now think that this could be solved if the parser knows it's inside a ternary operator branch: one wouldn't normally use a variable declaration inside it. So the ambiguity will be gone. It's a small logic that's added to the parser, but maybe it's worth it.

could have both.

On topic, I still agree with @asterite though that two colons are easier to read because it is a declaration.

**Comment by ozra** [comment]
I'm fresh to Crystal as of today, but will opt to chip in anyway, for a handfull of two cent'ers more - a slightly lengthy comment just to add some wider "outsider" perspective on Crystal. 

For some background as for my opinions: I've coded C++ for about 16Y+, mostly with XXX transpiler in front, giving indentation-based syntax, when ever team/contractor situation has allowed me. Have coded a hoard of languages over the ~27Y I've coded, but never touched Ruby, and probably never will. _I'm simply looking for a greater language to finally replace the monster C++_ that has haunted me as the go-to language for performance projects (most my non web related code, which has been in LiveScript).

I've been evaluating Nim for a while now and in my langs investigations these last two weeks I unfortunately dismissed Crystal completely right off the bat. My recollection is that I perceived it like "just something for ruby folks who don't want to type annotate" (_I do love the extensive inference btw_), and thought it would be immature and non performant one trick pony, so I didn't even look further at that point.

Today, for whatever reasons, I stumbled upon Crystal again, tried it, and quickly got a completely different (very impressed) view on it. I got used to the "end"s that first just reminded me of horrible V.Basic contractor work, and they actually feel alright already. _So, I guess, there may be more people like me who miss out on it because of the strong "Ruby branding" one is met with atm_. To be clear: I have nothing against it as an inspiration, but Crystal clearly is a language that stands on its own feet, and would benefit from being respected in its own right.

**With that out of the way:**

I think a single `:` would be natural to annotate type in all scenarios. What the reader perceives (we read code more then code, hence the term) is all that count, and it is just a matter of subjectivity. It _does_ mean "is of type" in both cases, afaic. It's not the type annotation that declare a variable or instance variable, it's the identifiers in the _context_ (and it's obvious unless you're writing 50 line instance variable lists in vim on a 80x25 terminal). Their declaration of memory location binding isn't imperatively associated with the fact that they're type annotated, and so the distinction of `:` vs `::` is moot in that respect imo. So it still just comes down to _how you view it mentally_. "Annotating anything with type is accomplished with `: Type`" feels crystal clear in my eyes.

When it comes to dropping the ternary, while I tend to use it, I would not miss it at all. "_Infix if_" would be a great replacement (the suffix if with suffix else), or just a plain _expression-if_.

As I said: respectfully a newbie outsid'ish perspective - but those can be help too.

I'll add an issue with a feature wish for "infix-if" as per @asb 's comment, those are nifty.

**Comment by kirbyfan64** [comment]
@ozra Haha, you found this too. :O

I think it's fine as-is.

**Comment by ozra** [comment]
@kirbyfan64 - Haha, yes, luckily. Very interesting project. Think it is good to always start off with outsider perspective comment - before one is poisoned by convention and 'what ever'. ;-)

**Comment by vendethiel** [comment]
> which has been in LiveScript

@ozra @kirbyfan64 ;-)

**Comment by ozra** [comment]
Perhaps add [RFC] to title, and fix 'color' -> 'colon' typo?

**Comment by ozra** [comment]
Now, after some time using Crystal daily, I feel strongly about unifying type annotation to one colon always. Double colon is also used for namespace / module pathing which is completely unrelated. But the main reason is type annotation consistency.

**Comment by ozra** [comment]
Oh, also, regarding the ternary... #937
