### ISSUE TITLE
gsub internal loop bug 

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#787]
This code will compile, and when ran wont end and will take CPU to 100%: 

```crystal
@@options = {} of String => Bool
@@options["Binmode"] = false
string = "testing"
NULL = "\000"

string = string.gsub(/#{NULL}\n/, "") unless @@options["Binmode"]

puts string
```

**Comment by bararchy** [comment]
Somne debugging, the issue seems to originate in string.cr, line 951.

the while match loop seems to be looping endlessly 
I added BUFEER puts to see what is happening , this seems to be the output:

```crystal
def gsub(pattern : Regex)
    byte_offset = 0
    match = pattern.match_at_byte_index(self, byte_offset)
    return self unless match

    String.build(bytesize) do |buffer|
      while match
        index = match.byte_begin(0)
        puts "BUFFER: #{buffer}"
        buffer.write unsafe_byte_slice(byte_offset, index - byte_offset)
        str = match[0]
        buffer << yield str, match
        byte_offset = index + str.bytesize
        match = pattern.match_at_byte_index(self, byte_offset)
      end

      if byte_offset < bytesize
        buffer.write unsafe_byte_slice(byte_offset)
      end
    end
  end
```

```
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
BUFFER: #<String::Builder:0xd5af90>
...
...
...
```

**Comment by kirbyfan64** [comment]
Funny thing, something just like this was recently raised on the LuaJIT mailing list...

**Comment by asterite** [comment]
@bararchy Thanks for reporting this! It was fun fixing this :-)

There were two issues: the first one is that `gsub` didn't work with empty strings or regexes. Ruby is really amazing, handling all cases perfectly well. Now it works OK and behaves like Ruby.

The second issue is that PCRE doesn't allow null characters in the regex pattern... because when you [compile](https://github.com/manastech/crystal/blob/master/src/regex/lib_pcre.cr#L5) a pattern you just give a pointer and you can't specify the bytesize, so it ends at a null character. I also found [this](http://stackoverflow.com/questions/2581037/can-pcre-regex-match-a-null-character).

**Comment by asterite** [comment]
@bararchy Next time, if it's not too difficult, please try to reduce the code to the minimum that triggers the bug. The Hash, class variables and the `unless` are just noise for finding the bug. We can usually reduce it from there, but if you can do it before us it saves us a bit of time :-)
