### ISSUE TITLE
Vote to change the name of "Crystal Language"

### ISSUE THREAD

**Issue by Kentoseth** [manastech/crystal#797]
Hello there,

I really like the potential of this language.

It seems like 1 of those gems (no pun intended) that has the potential to become a power-house for rapid web/systems development without all the bloat that other modern static languages are giving.

There is just 1 issue for me right now, which is the name "Crystal".

Maybe not now, but when the language does gain steam, people looking for tutorials are going to get frustrated when they keep seeing tutorials for "Crystal reports" instead of "Crystal language", which are 2 completely separate things (and "Crystal reports" will have higher search results, due to being around longer).

I therefore ask that you guys consider changing the name to something similar to what we currently have.

Suggested names:

 - Crysp
 - Crast/ Crasp
 - Crys

These suggested names aren't too good, but getting something very unique (but still short) may be a good way to go.

Opinions welcome.

**Comment by vyp** [comment]
:-1:

I like crystal because ruby is a gemstone. A "crystal" technically isn't of course, but you get what I mean. Crysp/Crast/Crasp/Crys all suck compared to "Crystal".

The crystal reports thing will become less of an issue with time. Besides, searching for "crystal lang" works anyway for now. Rust doesn't have this search engine problem. Also, just my opinion, but I think it's way too late to change the name. Plus, changing the name of crystal will mean "shards" won't make sense.

**Comment by kirbyfan64** [comment]
NOOOOOOOOOOOOO!!!!! Crystal is an *awesome* name for a language. Most languages have names that conflict with other stuff anyway (Go - word, Felix - cat, Python - snake).

**Comment by vyp** [comment]
Oh yeah, and https://github.com/manastech/crystal/issues/684#issuecomment-105060945.

**Comment by gutenye** [comment]
NO, even the 'go' name works.

**Comment by stefanpenner** [comment]
-1 the name is fine.

**Comment by spalladino** [comment]
Pretty much every programming language is named after something else in existence; the few that are not are mostly acronyms, [as you can see for yourself](http://c2.com/cgi/wiki?ProgrammingLanguageNamingPatterns).

(by the way, it was a very pleasant surprise to see Crystal already in that list)

**Comment by matiasgarciaisaia** [comment]
> _For those who confuse crystal reports and crystal language, I feel horrible for you._

**Comment by Kentoseth** [comment]
Well some of the replies are certainly not what I was expecting.

To those that made good points, thank you.

To those that chose to voice your anger/sarcasm and toxic humour at a mere suggestion, I certainly hope you do not become the brotherhood that turns this beautiful language into a toxic community.

Issue closed.

**Comment by kirbyfan64** [comment]
> To those that chose to voice your *anger/sarcasm and toxic humour* at a mere suggestion, I certainly hope you do not become the brotherhood that turns this beautiful language into a toxic community.

I would hardly call this *toxic*. More like *funny sarcasm*. :O

**Comment by jhass** [comment]
@Kentoseth I hope you don't see us as a toxic community now already and stick to the project nonetheless :)

Maybe just try to put on a different perspective, Crystal had its first popularity spikes now, so it does ring a bell for quite a few people already. It exists as project for over two years now and some are watching it for an equally long time already. I think that some feelings may be a little bit hurt by a "stranger" appearing and doing nothing more than (I'm exaggerating) claiming "you picked the wrong name, change it asap!", is quite understandable it feels a little bit ridiculous, also because of the other more objective arguments raised here already ;)

**Comment by asterite** [comment]
@Kentoseth To add a bit more to what @jhass says, I think the answer would have been "no" by the majority of us. This probably isn't a pleasant answer for you, so one alternative is to add a joke or some humor to add. I don't think there were bad intentions here. Also, I always try to think there never are bad intention on internet comments: it's really hard to know someone's mood without the voice, the face, etc., or maybe they had a bad day. In any case, it's the best alternative one can choose :-)
