### ISSUE TITLE
bugs with *.times do spawn 

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#802]
this code:
```crystal
5.times do 
  spawn puts "hi"
end
```
should output:

```
hi
hi
hi
hi
hi
```

But it wont, is this a bug or do I miss something ?

**Comment by asterite** [comment]
@bararchy Think of `spawn` as `Thread.new { ... }` without `join`. If you do this in Ruby:

```ruby
5.times do
  Thread.new do
    puts "hi"
  end
end
```

Maybe you will see a couple of "hi" but the program will exit before, because the main thread exits. With `spawn` it's exactly the same: the main fiber exits before outputting anything.

One way to solve this is:

```crystal
5.times do
  spawn puts "hi"
end

sleep 1
```

But that's of course just a hack. Another solution is to make the main Fiber wait for all those spawned processes to finish. You use a `Channel` for this:

```crystal
# A dummy channel to count
ch = Channel(Nil).new

5.times do
  spawn do
    puts "hi"

    # Each spawn will send one value
    ch.send nil
  end
end

# Wait for 5 values to come, blocking meanwhile.
5.times { ch.receive }
```

**Comment by bararchy** [comment]
Thanks, I'll take that into account next time.
