### ISSUE TITLE
Unimplemented abstract methods don't raise error unless called

### ISSUE THREAD

**Issue by dhruvrajvanshi** [manastech/crystal#835]
```crystal
abstract class A
  abstract def a
end

class B < A
end
```
Compiles just fine even though B doesn't implement A's abstract method a. The error only shows up when you call a on B's instance. In my opinion, when a class inherits from another class, it should be obliged to implement it's methods. The current behavior may lead to bugs going undetected especially for libraries (where methods may not be called on every object in the library itself).
I know this may go against the language's philosophy and would like to hear opinions.

**Comment by asterite** [comment]
This is a valid enhancement.

We originally introduced abstract methods because in Ruby there's no such thing and people either: 1. document them in comments but it's not very nice or 2. implement them and raise "this method must be implemented" or a variant of that. In Ruby it doesn't matter much because it's always a runtime error. In Crystal we wanted to standarize this, so you document methods that must be implemented like this. However, we didn't add the "is implemented by all subclasses?" check because it might be expensive, but we don't know. I think it's worth trying adding it.

However, [Object=~](http://crystal-lang.org/api/Object.html#%3D%7E%28other%29-instance-method) is documented as abstract and not every class implements it, so I guess we'll have to document that [somewhere else](http://crystal-lang.org/docs/syntax_and_semantics/operators.html).

**Comment by waterlink** [comment]
This strikes me with idea of having 2 levels of abstract methods:

- could implement `:method_a`,
- must implement `:method_b`.

Might be good or might be bad idea. Your thoughts?

**Comment by jhass** [comment]
I'd say just redeclaring the abstract method should count as definition towards the parent, that way we don't need to add a keyword.

**Comment by technorama** [comment]
Please don't require all abstract methods to be implemented.  Many classes declare abstract methods that are not used aren't in the program.

Example:
  BufferedIOMixin has read, write, flush, close, rewind as abstract methods.
  Many times the specific instance will only need read OR write, not both.
  Flush, close and rewind may not be used at all.

If all abstract methods are required to be implemented you will probably end up with people putting fake methods that either do nothing or throw an exception.  Neither is useful and the source ends up cluttered.

**Comment by asterite** [comment]
@dhruvrajvanshi I reopened, this is a valid issue.

What @technorama is partially right, but not quite. For example if you have:

```crysta
ios = [] of IO
ios.each &.write(...)
```

then the compiler will require **all** IO types to have that write method. So it makes sense that abstract methods are definitely implemented, even if not used in particular cases.

**Comment by technorama** [comment]
Can the compiler be made smarter?  Can the compiler base the abstract requirements on the actual subtypes used rather than just the declared type?

```
ios = [] of IO
ios << MyIO # only contains MyIO
```

**Comment by kumpelblase2** [comment]
I would argue in favor or forcing abstract methods to be implemented by subclasses. If you end up having empty methods in them, then you either really want to do nothing (which an empty method would make more clear than just not implenting it) or your code is too cluttered which in term would force you to clean it up more and make smaller, simpler structures.

I like Go's mentality on this, interfaces really only have that what they REALLY need. If they need more than what's there, you either have to check if you want to force everything to require the new functionality as well or create something else that has this extension.

Also, why do we have the power of a compiler and a statically type-checked language to find issues early and not use it?

**Comment by technorama** [comment]
Doing nothing is not clear.  Did the author mean do nothing or did he create a broken untested method just to satisfy the interface?  The latter may break at runtime if you depend on it.

Many tiny interfaces solves the problem but we don't have that.  We have IO which requires read AND write.  BufferedIOMixin requires a lot more.

Why not have a smarter compiler that can see if the methods are actually used before requiring their implementation?  To me that's a smart compiler - not making me work more.

**Comment by OlegTsyba** [comment]
I completely agree with @asterite, since, if I use IO object then I rely that I can use it for all IO operations and will not face with situation when my IO object cannot behave like IO because of its author forgot(or decide that it needless for that implementation) to implement some methods. Thus, for cases when I need only read,write operations, I think it's better just to separate interfaces(as an option), something like this:

    abstract class MyBasicIO
        abstract def read
        abstract def write
    end
    
    abstract class MyIO < MyBasicIO
        abstract def flush
        abstract def close
        abstract def rewind 
    end

I think such behavior will be the great improvement comparing to Ruby

**Comment by technorama** [comment]
Splitting IO is a separate issue from implementing ALL abstract methods.

* Requiring all abstract methods breaks duck typing.
* Requiring all abstract methods does NOT guarantee the implementation works when the author doesn't use the extra methods he was forced to implement but never intends to use.  

Please tell me how this fake implementation of rewind is better than only giving an error if a) an abstract implementation is missing AND b) the method is actually used.
```
def rewind
  nil
end
```

The above code can lead to **data loss or corruption** if the implementation fakes the rewind or seek methods.  Zip files require random access reading.  Reading from the wrong location will return junk and probably crash.  Writing to the wrong location will corrupt the file.

There is a PR that starts to split IO in to different modules/interfaces in #1428 .  Some of your concerns may be handled by that.  Mine aren't.

**Comment by OlegTsyba** [comment]
Okey, imagine I have such method:

    def some_meth(io : IO)
        ...
        io.rewind
        ...
    end

Then, if we pass IO object, for which `rewind` is not implemented, then we receive such exception: `abstract def MyIO#rewind must be implemented by DontRewindItIO`. But how it can help me as to user of this weird IO object? Maybe it's better to receive exception like this : `You can't rewind it since ....`, and programmer which implemented this IO class should be obligated to give sensible exception or better to find reasonable way to implement all IO operations. So, as for me, it's better explicitly raise exception

    def rewind
        raise "You can't rewind it since ..."
    end

**Comment by technorama** [comment]
How would you enforce that? 

You can force someone to implement a method but you can't force them to implement it correctly, especially if they have no intention of testing it.  Maybe they will raise an exception if force to implement it, or maybe they will return true, false, nil, or other.  Maybe they will attempt to implement the method but be off by 1.  Maybe they will implement seek but forget to change the position attribute.  Maybe they forget to reset the read and write buffers.

There are so many things that can go wrong, it's best to NOT force implementation.  At least then you have an accurate error method and a chance of implementing it correctly.  A fake or malfunctioning functioning method could waste hours or days of your time debugging.

**Comment by OlegTsyba** [comment]
But in such case we can just write

    abstract class IO end

In such case we receive: `undefined method 'rewind' for DontRewindItIO`
instead of: `abstract def MyIO#rewind must be implemented by DontRewindItIO`
And for user of this IO object it's actually all the same! Second variant is better for one who write this IO class, but for user both variants mean: "this object can't respond to `rewind` method". Moreover, it's weird behavior for any object of any type when some method from API is useless, I think it sign what you need redesign program.

`Maybe they will raise an exception if force to implement it, or maybe they will return true, false, nil, or other. Maybe they will attempt to implement the method but be off by 1. Maybe they will implement seek but forget to change the position attribute. Maybe they forget to reset the read and write buffers.` -  There is no programming language that can entirely save programmer from mistakes.

**Comment by technorama** [comment]
Your examples are not the same.  Best case scenarios are the same but worst case scenarios are very different.

### If all methods are required
#### User's perspective if implemented correctly
Everything works.
#### User's libraries perspective if implemented incorrectly
Anything can go wrong.  Instead of a helpful "method missing" error the program may crash, refuse to compile for other reasons, corrupt data, fail nil checks or other.
#### Library developer's perspective
There is always an error.  They may put in junk just to make the error go away.  Worse they may add a method that is incorrect or doesn't work that they never test.


### If methods are not required
#### User's perspective if implemented
Everything works.
#### User's perspective if not implemented
The user receives a method missing error.  At least he know what that means and can look in to writing a method.
#### Library developer's perspective
The library appears to work and they go on their way.  Good authors will fill in all available methods and raise when the operation is not possible.


**When the author is experienced, thorough and writes complete tests both situations are the same.  When author quality is lacking the results are very different.**

**Comment by OlegTsyba** [comment]
I think second variant (**methods are not required**) is good enough from perspective of dynamic programming language(here Ruby), but, as @kumpelblase2 has mentioned, why we can't use all benefits what can give us static typing? Why we should do those ugly(from my perspective) runtime-checks like

    def meth(io : IO)
        if io.responds_to? :rewind # read, write, anything...
        ...
        end
        # or 
        if io.is_a? RewindMeIO
        ...
        end
    end

whereas we can use abilities of static typing and do like this:
**first variant (methods are required)**

    module IO
       abstract def read
       abstract def write
       abstract def rewind
       ...
    end

    # IO for which rewind make no sense, and we deliberately
    # create new IO type that can't be rewound
    class SomeIOThatCannotBeRewoundIO 
        include IO

        def read(...)
            reasonably implement this method
        end

        def rewind(...)
            raise "You can't rewind it since ..."
        end

        def write(...)
            reasonably implement this method
        end
        ...
    end

    # I don't need a common (full-fledged) IO object, I need
    # some specific IO object that cannot be rewound, and I realize
    # that 'rewind' SHOULD NOT BE USED HERE. 
    def some_meth(io : SomeIOThatCannotBeRewoundIO)
        ...
    end
    # or
    # here compiler guaranties me (in compile time) that object in 'arr' can't be rewound(reasonably)
    arr = [] as SomeIOThatCannotBeRewoundIO
    arr.each &.rewind
   

I think it makes my code much more expressive and sensible, moreover, we no need make runtime-checking, all it's done in compile time. AFAIK, Crystal not aim to copy Ruby-style entirely, but instead take the better from the Ruby world and add good abilities that the static typing can provide

So, I think, programmer should not thoughtlessly stub needless methods(which is needless in its IO implementation), the new subclass(subtype) should have some meaning, and user of its those IOs should explicitly point out (**if it necessary**) what type of objects he need in his methods, instead of doing ugly runtime-checks or receiving `abstract def MyIO#rewind must be implemented by DontRewindItIO`.
If amount of stubbed methods in IO-implementation is huge then maybe API of IO is redundant, and **we need separate interfaces**(*as I has mentioned earlier*)

**Comment by jreinert** [comment]
+1 for enforcing abstract method implementation. The worst thing right now is, that it's possible to _think_ you've implemented an abstract method, when you actually have not. Be it a typo in the method name or a wrong arg or return type. I think enforcing it will simply enable us to write better, more robust code.

right now there's no benefit of `abstract def foo` over `def foo end`

**Comment by asterite** [comment]
Yes there is: documentation and better error messages, letting you know you must implement the method.

**Comment by jreinert** [comment]
@asterite i must've missed the error messages. what do you mean?

**Comment by asterite** [comment]
http://play.crystal-lang.org/#/r/hdy

**Comment by jreinert** [comment]
alright. that's good. sorry i missed that. probably wasn't trying to call the method
