### ISSUE TITLE
gets("\0\0") crashes program

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#850]
http://carc.in/#/r/507

**Comment by asterite** [comment]
Thanks!

It turns out the String length computation was incorrect when there was a zero byte, it stopped one it found one. So the length of "\0\0" would be considered to be zero.

Now, String computes its length lazily: if it's zero and the bytesize is greater than zero, we compute it and save it in the string so later it can be reused. The compiler stores statically known strings like `"foo"` in the read-only memory and, since they are known at compile-time, store their bytesize and length beforehand. But since the length was incorrectly set to zero (and bytesize was greater than zero), the length was computed and tried to store in read-only memory, leading to a segfault.

This means that for you to try this fix you'll have to compile a compiler.

**Comment by bararchy** [comment]
@asterite Thanks :) 

I'll recompile and test
