### ISSUE TITLE
Compiler fails to deal with an alias of union type

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#860]
```crystal
alias T = (Array(Int32) | Array(Float64))
p T.new.class
```

Above code outputs

```
Array(Int32)
```

I think `Array(Int32) | Array(Float64)` is valid in this case because below code causes an error.

```crystal
alias T = (Array(Int32) | Array(Float64))
a = T.new
a << 1.0
```

**Comment by asterite** [comment]
I think in 0.7.3 we introduced this feature of being able to invoke a method on a union type if it was present in all of the types. For example [like this](http://play.crystal-lang.org/#/r/55z).

This was added so, for example, `Enumerable#sum` can use T.zero as the initial value and so if you do `[1, 2, 3].sum` then T.zero will be 0 (Int32), if you do `[1.5, 2.5, 3.5].sum` then T.zero will be 0.0 (Float64) and if you do `[1, 1.5].sum` then T.zero will be either 0 or 0.0 (doesn't matter which, really) with type (Int32 | Float64).

But with this introduction the snippets you report start to become more confusion. There's also the thing that [this](http://play.crystal-lang.org/#/r/560) is allowed now, which is totally unexpected (just `Int32.from_json` is used in both cases). I think we should review this feature, maybe it wasn't such a good idea...

**Comment by asterite** [comment]
@rhysd As a side note, what do you want to do? Or how did you find this?

**Comment by rhysd** [comment]
Please confirm my understanding is correct.

```crystal
a = 1 || 1.5
pp a
pp typeof(a)

pp a.class.zero
pp typeof(a.class.zero)
```

In above code, compiler infers the type of `a` as `Int32 | Float64` (type of `typeof(a)`).  And actually the type of `a` is `Int32` at runtime (type of `a.class`).
In above case, type of `a` is determined to `Int32` correctly.  But in my case, type `T` can't be determined `Array(Int32) | Array(Float64))` but it is wrongly used as `Array(Int32)` at runtime, right?


> As a side note, what do you want to do? Or how did you find this?

I found this while implementing #859.  Please think transposing array of array of union type.

```crystal
[[1, 2], [3.0, 4.0]].transpose
```

I expected the result `[[1, 2.0], [3, 4.0]]`.  But actually it caused an error at [here](https://github.com/rhysd/crystal/commit/505b28d9267a494df5b53d6adaf4ded3cdd0a1c1#diff-a375a8eca3c8195929f07569b36c7977R915).  It was because type of `T.new` seemed not to be `Array(Int32) | Array(Float64)` but `Array(Int32)`.

**Comment by jhass** [comment]
I'm not sure how you get to `Array(Int32)|Array(Float64)` from that example, it`s `Array(Array(Int32|Float64))` so the element type of the outer array is `Array(Int32|Float64)`, see http://carc.in/#/r/566 for a way to create a new array of it without knowing the type.

**Comment by asterite** [comment]
The problem is more subtle. Depending on the elements of each individual array, the type changes:

http://carc.in/#/r/567

That's `Array(Array(Int32) | Array(Float64))` vs. `Array(Array(Int32 | Float64))`

Now if I want to create from one of the array above a single array with all the inner types, [I can in one case](http://carc.in/#/r/568) but [can't in the other](http://play.crystal-lang.org/#/r/569). You'd need to somehow combine the types of all the arrays inside that array...

Oh, well, in fact, you can:

http://play.crystal-lang.org/#/r/56a

:-)

**Comment by asterite** [comment]
That means that `transpose` should probably be something like [this](http://play.crystal-lang.org/#/r/56c). Kind of long with all of those typeof, but you need to combine the types of the internal arrays...

**Comment by rhysd** [comment]
@jhass 

Thank you for your pointing out.  You are right, I was confused.


@asterite 

Thank you.  I understood that the 2 case of union types conflict.  I feel combining all element types is difficult because I don't know how to get the inner type of `Array`.
Although this is just an idea, it may be solved if compiler can reduce `Array(Int32) | Array(Float64)` to `Array(Int32 | Float64)` at type inference.

Finally, I have no idea if my first code is a serious problem or silly edge case...

**Comment by bcardiff** [comment]
@rhysd  Going bit formal, but assuming `<:` is the subtype relation between types
It's not true that `Array(Int32) | Array(Float64) <: Array(Int32 | Float64)`.
Because that means an `Array(Int32)` might be used as an `Array(Int32 | Float64)` and therefore assign a `Float64` to some position.
What it is true (or would be nice to be true in crystal) is that `Enumerable(Int32) | Enumerable(Float64) <: Enumerable(Int32 | Float64)`.

@asterite just to clarify, your transpose code work because a call to `#first` is forwarded to all possible types of the receiver and then merged again in an union types of the results. Since you are using `.first.first` inside a `typeof` the actual value is not used and therefor we get the union. :+1: 

http://play.crystal-lang.org/#/r/575

**Comment by asterite** [comment]
@rhysd I think it's just a difficult thing to implement because it's a functionality that's easy to implement in a dynamic language, where an array can hold any type of object, but then you want to translate that logic to a statically typed language where arrays are generics. That, and the thing that the language is still young and we are still figuring best practices and patterns. Believe me, we also scratched our head many times when trying to implement some algorithms in Ruby (algorithms you usually don't find in statically typed languages)... for example `flatten` (which right now we are missing). I don't recall seeing a `transpose` method in other languages neither, unless it's for a matrix type.

Another hard example is [Enumerable#to_h](https://github.com/manastech/crystal/blob/master/src/enumerable.cr#L704), where it is assumed that the enumerable holds arrays or collections. In Ruby you'd just invoke [0] and [1] on the arrays to build the map... and that's sort of what the method ends up doing, and it uses those methods to also know what types to return.

But, fear not. Generic classes are not very common and we'll probably have to deal with these difficulties in few places.

(I wrote the following before I saw @bcardiff's answer:)

The idea of making `Array(Int32) | Array(Float64)` be `Array(Int32 | Float64)` is not possible. Imagine this:

```crystal
a = [1, 2, 3] # Array(Int32)
b = [1.0, 2.0, 3.0] # Array(Float64)
c = rand(0..1) == 0 ? a : b
```

Suppose we make `c`'s type be `Array(Int32 | Float64)`. Then we can do this:

```crystal
c << 1 # OK?
```

If `c` is `a`, that's fine, but if `c` is `b` then we managed to introduce an `Int32` into an `Array(Float64)`, breaking the type system. So, the type of `c` should really be `Array(Int32) | Array(Float64)` and you can't push an `Int32` into that (in fact you can't push anything into that because it has to be an `Int32` and a `Float64` at the same time).

**Comment by rhysd** [comment]
@bcardiff @asterite 

Thank you very much for the formal explanation and comprehensive examples.  I googled subtype relation a bit and I understood the difference between `Array(Int32) | Array(Float64)` and `Array(Int32 | Float64)`.  
And I could implement `Array#transpose` referring to the codes in this issue.

I think Crystal is very flexible because it can deal with type as value in runtime including union types.  However, union types don't exist in runtime because all union type has its actual type at runtime.  I was confused at that point.

Anyway, the solution of my case has been clear.  And I can't judge that my first code is an edge case or not.  So, I think it is good to close this issue and more obvious and to reopen this issue when serious example emerges.
How do you think?

**Comment by bcardiff** [comment]
I think we are learning together. :-)
Just trying to make a nice comfortable language but without compromising performance.

There are some rules that try to make the compiler smart enough to mimic a programmer deduction regarding the types. But rules sometimes are not so easy. Subtyping rules can be learned, but they require a little bit of effort.

Regarding union types. The do exist in runtime. They are built automatically. Like a struct with a type discriminator plus the space required to keep all values. But with some optimizations (like`String` and `String|Nil`) in order to consume as less space as it can.

Thanks for the contribution and interest :-)

**Comment by rhysd** [comment]
@bcardiff 

Thank you for your comment and explanation of union types.
I'll try to learn more about type system of Crystal.

Then I'll close this issue.
