### ISSUE TITLE
Odd syntax thing with function definitions

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#868]
This program works:

```ruby
def f() end
f
```

This is a syntax error:

```ruby
def f end
f
```

I think Crystal is parsing the `end` as an argument name?

**Comment by ysbaddaden** [comment]
Yes, just like Ruby. You need either empty parens or a semicolon to disambiguate. Otherwise the parser expects an argument.

**Comment by kirbyfan64** [comment]
@ysbaddaden But Ruby has a better syntax error, at least.

Ruby:

```
ryan@DevPC-LX:~/langtest/cr$ ruby end.rb
end.rb:1: syntax error, unexpected keyword_end, expecting ';' or '\n'
ryan@DevPC-LX:~/langtest/cr$ 
```

Crystal:

```
ryan@DevPC-LX:~/langtest/cr$ crystal end.cr
Using compiled compiler at .build/crystal
Syntax error in ./end.cr:3: expecting identifier 'end', not 'EOF'
ryan@DevPC-LX:~/langtest/cr$ 
```

**Comment by asterite** [comment]
I think we can make `def f end` parse well, just an empty def.

**Comment by asterite** [comment]
Actually, I'm not sure, maybe without the `()` or the `;` it looks like `end` is an argument name...

**Comment by waterlink** [comment]
It is an argument name that nobody will ever be able to use inside of
method body (because it will end the method body), right? In that case I do
not see any harm in making it just work as an empty method.


--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-06-27 18:49 GMT+03:00 Ary Borenszweig <notifications@github.com>:

**Comment by kirbyfan64** [comment]
@asterite I don't think even Ruby allows `end` as an argument name...

**Comment by asterite** [comment]
@waterlink @kirbyfan64 I know, I'm just not sure it's worth it. With these you can clearly see where the arguments end:

```crystal
def foo
end

def foo() end

def foo; end
```

But with this it's not that visible:

```crystal
def foo end
```

Then, what if the method has arguments, should we allow this?

```crystal
def foo bar end
```

Now it's not very obvious if "bar" is an argument or the body...

**Comment by kirbyfan64** [comment]
@asterite At least, if it isn't changing, a better error message would be nice...

**Comment by will** [comment]
Could Crystal make parens required on method definitions? I've personally never liked when people didn't use them in Ruby.

**Comment by kirbyfan64** [comment]
@will I use those all the time...

**Comment by asterite** [comment]
@will I dislike that too, I always use parens

**Comment by jhass** [comment]
I always leave them off in my personal projects, though community standard is to add them for method definitions, yeah.

**Comment by ozra** [comment]
I think method defs are more apparent with the slight bit of formalia, the two parens ain't to much to ask. I use parens on no args methods too - I know that's not official recommendation though.

On the other hand, since some like the opposite way, and this is hardly a needed change, the rule could be "if `end` is encountered after method name - it's an end keyword". If one wants a param named 'end', you will need parens or a semicolon.

The main issue if of course that arguments and body can be ambiguous at the parsing stage.
