### ISSUE TITLE
Capturing blocks/procs raises compile error even if not evaluated (undefined methods)

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#896]
Hi everyone,

so I tried to write a new library in crystal today and stumbled upon this problem with the compiler. Basically what I want to do is I want to capture a proc for later usage and then instance_eval it later for my DSL (e.g. `with self yield`)

That doesn't seem to work as somehow method calls in procs seem to already be checked when I assign them to an instance variable. E.g. for reference, this works (throws no error/can be run/built as block is never executed):

```
class BlockStore
  def initialize(&blk)
  end
end

BlockStore.new do
  i_should_never_get_executed
end
```

This doesn't work (compile time error is thrown although block is never executed) .Only difference is that blk gets assigned to an instance variable:

```
class BlockStore
  def initialize(&@blk)
  end
end

BlockStore.new do
  i_should_never_get_executed
end
```
The second one fails with:

```
Error in ./_playground/src/block_store1.cr:7: undefined local variable or method 'i_should_never_get_executed'

  i_should_never_get_executed
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I tried it both on 0.7.4 and current master 986aca3bcfd

for future reference, what I try to do in the end is something like this (might be further errors in there as I hang on the "it is not defined" error):

```
class InstanceEval
  def initialize(@description, @blk)
  end

  def self.describe(description, &blk)
    self.new description, blk
  end

  def it(description, &blk)
    with self yield
  end

  def instance_eval(&blk)
    with self yield
  end

  def run
    instance_eval &@blk
  end
end

context = InstanceEval.describe "Trying things" do
  it "hey hey hey" do
    puts "hellooooo"
  end
end

context.run
```

Thanks!
Tobi

**Comment by asterite** [comment]
Unfortunately you can't do `with self yield` with a captured block. There's no such thing as Ruby's `instance_eval` and will probably never be.

In Ruby it's easy because it's interpreted: when interpreting the block Ruby can choose what the scope is. In Crystal this is harder, all we know about a block is it's type: what are the input types and what is the return type. We have to figure things at compile time, we can't delay these things to runtime (because we want speed).

When you do this:

```crystal
def proc(&block)
  block
end

my_proc = proc { puts "hello" }
```

Crystal will analyze `puts "hello"` in that same line, resolving `puts` to the current scope. We can't delay this. Maybe with a special notation we could, but what would the type of `my_proc` be? It should be a single unique type: "it's this particular block". Then you could instance eval it and the compiler will check the body with some particular context... But for every "it" block a new type will be created, I think that will kill the compiler very quickly.

**Comment by asterite** [comment]
@PragTob I also saw [this](https://github.com/PragTob/speccr). Unfortunately the issue you are waiting to be solved (this) will probably never be "solved" (because it's not an issue, it's a design decision). You would have to think of another way to do what you want. [This](https://github.com/waterlink/spec2.cr) is another try at a better spec framework, but I think it uses more macros rather than `with ... yield`. Then, if all you need are before/after hooks you could try using [minitest](https://github.com/ysbaddaden/minitest.cr).

**Comment by PragTob** [comment]
Hey @asterite !

Thanks for the detailed explanation, I was afraid this might be a technical limitation. 

What I really wanted to do was evaluate `it` blocks and everything in different contexts and save them so I could run them in random order or something. As well as suppport `let` statements and friends :)

Thanks for the link to @waterlink 's repo, I'll have a look.

I guess then I'll have to figure out new strategies to solve the problems I'm facing and learned more about what's good to go in compiled languages and what isn't.

Thank you very much @asterite !

(closing as a can't be fixed if I understood correctly)
