### ISSUE TITLE
Problem converting empty tuple to array

### ISSUE THREAD

**Issue by michelboaventura** [manastech/crystal#909]
Hi!

I'm trying to do something like this:

```Crystal
def foo(*args)
   args_array = args.to_a
   puts args_array + [1, 2]
end
```

If then I call ```foo(10)``` it works, but calling just ```foo``` gives me
```Crystal
Error in ./bla.cr:6: instantiating 'foo()'

foo
^~~

in ./bla.cr:3: instantiating 'Array(NoReturn)#+(Array(Int32))'

  puts args_array + [1, 2]
                  ^

in crystal/src/array.cr:212: instantiating 'Array(Int32):Class#build(Int32)'

    Array(T | U).build(new_length) do |buffer|
                 ^~~~~

in crystal/src/array.cr:212: instantiating 'Array(Int32):Class#build(Int32)'

    Array(T | U).build(new_length) do |buffer|
                 ^~~~~

in crystal/src/array.cr:213: no overload matches 'Pointer(Int32)#copy_from' with types Pointer(NoReturn), Int32
Overloads are:
 - Pointer(Int32)#copy_from(source : Pointer(T), count : Int)

      buffer.copy_from(self.buffer, length)
```

I can reproduce this with just ```Tuple.new.to_a + [1, 2]```

**Comment by Perelandric** [comment]
I believe this is covered in the [Type Restrictions docs](http://crystal-lang.org/docs/syntax_and_semantics/type_restrictions.html), under the *"Type Restrictions in Splats"* section.

**Comment by ysbaddaden** [comment]
You must specify the type of `*args` using (I think) `def foo(*args : Int32)` otherwise Crystal has no way to determine the type of arguments (since there are none) and this clashes with the array concat.

**Comment by bcardiff** [comment]
Using 

```crystal
def foo(*args : T)
   args_array = args.to_a
   puts args_array + [1, 2]
end
```

will allow any real type `T` to be used. So a `Array(T | Int)` will be created.
But right now that `T` can't be instantiated in an union type.

`foo(4)` and `foo(true)` are valid. But not `foo(4, true)` due to splats semantic. (it might be improved, but it is not the issue here)

Also as explained in http://crystal-lang.org/docs/syntax_and_semantics/type_restrictions.html if a type restriction is used, then `foo()` is no longer valid.

If foo is left without type restriction, `foo()` is valid w.r.t. splats semantic, but will fail to create an empty array since there is no clear type to use for the `T` in `Array(T)` 

This is the whole situation. There is not a clear thing that crystal can do to map an empty tuple to an empty Array. Because of the lack of type information. It depends in the usage. If we decide to force any type from the `Tuple#to_a` for the empty  tuple, then that type will propagate all around.

**Comment by asterite** [comment]
It works if `Array#+` has a different defition: http://play.crystal-lang.org/#/r/63x

The problem is that we are using some pointer methods like `copy_from` and some types are incompatible. But this should definitely work.

An empty tuple's element type, if you do for example `i = 0; Tuple.new[i]` is inferred to be `NoReturn`, because it will always raise. Then, the union of NoReturn and some T is always T, so this should definitely work.

I'll mark this as a bug, we'll try to think of a solution.

**Comment by michelboaventura** [comment]
Thank you all for the feedback. Meanwhile I will change my code to work in another way.
