### ISSUE TITLE
Autoload

### ISSUE THREAD

**Issue by Sdogruyol** [manastech/crystal#918]
As you may already know in Ruby autoload is pretty nice to use. Can we have that in Crystal ?

**Comment by jhass** [comment]
Could you elaborate on the benefit of autoload in Crystal? As I understood it in Ruby it's there to delay parsing of code which is potentially time consuming and might consume unnecessary memory. Both problems don't exist in Crystal since only what's actually called (to the method level) ends up in your binary or even goes through the semantic phase.

**Comment by Sdogruyol** [comment]
Hey there, 

As i'm pretty new to Crystal i have 2 merging questions.

1. Does the order of require matter?
2. Does requiring something more than once causes any cyclic dependency?

Thanks

**Comment by jhass** [comment]
Yes it does matter since Crystal has an open class system and allows overriding method definitions.

I haven't experienced any dependency cycle issues and I make heavy use of multiple requires (I require everything a file depends on at its top).

**Comment by asterite** [comment]
@Sdogruyol the compiler keeps track of the absolute paths of required files, so requiring a file more than once has no effect.

We did think about having an automatic type-finding system. For example if you write `Foo::Bar` that would automatically require "foo/bar". But it wasn't that trivial to do, plus there's the thing where you want to reopen type... Maybe in these cases it's better explicit than implicit.

What is the use case for autoload in Ruby?

**Comment by waterlink** [comment]
Well, from my ruby experience, autoloading is good for convenience and
creates a lot of confusion and bugs. Especially with class reopening.

**Comment by PragTob** [comment]
No, please don't do autoload, it's one of the things I'm glad crystal doesn't have :)

Also usage of `autoload` is [discouraged in Ruby and will most likely be removed from ruby in the future](https://bugs.ruby-lang.org/issues/5653).

 Matz regrets not removing it from the language when he added Threads and also:

> I strongly discourage the use of autoload in any standard libraries.

**Comment by sandelius** [comment]
@PragTob They actually succeeded making `autoload` thread-safe in recent version of Ruby (little thanks to jruby) so I doubt it will go away.

**Comment by PragTob** [comment]
@sandelius wow, interesting! Thanks for the information! Still no new comments on that issue - will be interesting to see what they do.

**Comment by jhass** [comment]
Since my initial questions for clarification and motivation never got answered, I'll vote -1 too.

**Comment by ysbaddaden** [comment]
Same here. A `require "path/**"` usually does the trick for me, as long as the required files do require what they depend on.

**Comment by sandelius** [comment]
I could see that it would be useful in web projects built on "whatever" framework where you'll have many files depending on each other.

**Comment by PragTob** [comment]
I think the main reason for autoload is delaying the time to execute a file until it is really needed, from my understanding that's not needed/useful/possible in a compiled language so that reason goes away.

The automatic loading of classes once they are encountered according to a convention over configuration scheme might be nice, but normal requires work just as fine and give you more control.

**Comment by jhass** [comment]
I feel like the consensus here is that we shouldn't do autoload. Would anybody mind closing this?

**Comment by asterite** [comment]
Yes, we can close this. Crystal's parser is pretty fast, requiring extra files has little overhead unless they are used. And if you don't use them there's no penalty, neither at compile-time nor at runtime.

**Comment by Qard** [comment]
This would be really handy for me right now. I have a shard with a bunch of optional classes that I want to use [Habitat](https://shards.info/github/luckyframework/habitat/readme) on for configs. But if they're loaded/executed _at all_ without being configured then `Habitat.raise_if_missing_settings!` will crash the process. If the classes are meant to be optional then configuring them should be possible to be skipped if not in use, however that's not the case as things are because there's no way to lazily load/execute them. 🤔
