### ISSUE TITLE
Suffix if vs undeclared var

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#946]
Compiles as expected:
```crystal
def foo(name: String?)
    if n = name
        return n
    end
    "Nope"
end

foo "Bender"
```

Doesn't compile - though I'd expect it too (same thing in practise):
```crystal
def bar(name: String?)
    return h  if h = name
    "Nope"
end

bar "Bender"
```

```
in ./src/errors-test.cr:26: undefined local variable or method 'h' (did you mean 'h'?)
    return h  if h = name
           ^
```

**Comment by PragTob** [comment]
Good catch, seems like it doesn't check the post if first :) Should definitely work :)

**Comment by asterite** [comment]
Not a bug, it fails by design. It's the same as in Ruby, if you try it.

The thing is, the parser goes from bottom to top and left to right. When it encounters a name like "foo", if there's a local variable already defined with that name, then "foo" is a variable. Otherwise it's a method. So "h" in the first case is parsed to be a call rather than a variable. And we won't change this, because otherwise you have to delay the parsing of every expression in case you later find a suffix "if" or similar.

However, I'll tag this as a bug because the error message is confusing. It should even probably tell you to use a non-suffix "if".

And before you suggest "but make it work in this case", try [this](http://play.crystal-lang.org/#/r/6k5) in Ruby and Crystal. I know it's a contrived example, but it works as expected.

**Comment by ozra** [comment]
Yeah, I figured it checked undeclared before rewriting, otherwise, "logically" I should work. But by your example I realize more comes to play.

I'll leave it to you to close it when it's appropriate, for me "it's closed" :)

**Comment by asterite** [comment]
Now for this program:

```crystal
a if a = 1
```

The compiler will tell you:

```
Error in ./foo.cr:1: undefined method 'a' (if you declared 'a' in a suffix if, declare it in a regular if for this to work)

a if a = 1
^
```

I think one of the toughest parts of a compiler is coming up with good, short sentences for error messages :-P (which I'm not good at)

**Comment by ozra** [comment]
Yeah, that's a problem in itself, haha. Can't think of a much shorter way, it's nice enough that with informative errors. When the compiler is a concise tutor of the language, it's ultimate :-P
